import { createHash } from "node:crypto";
import { gunzipSync } from "node:zlib";
import { env } from "../config/env.js";
import { requestSupabase } from "../elos/supabase.js";

type J=Record<string,unknown>;
const C=env.BOSSA_COMPANY_ID,P="ffe8b7ec-1f01-4f6c-8a03-2bd6d3ae94fc",CODE="FLOW-REV03-V4",WRITE=process.env.FLOW_IMPORT_WRITE_ENABLED==="true";
const s=(v:unknown)=>String(v??"").trim(),n=(v:unknown)=>typeof v==="number"?v:Number(v??0),qs=(o:Record<string,string>)=>new URLSearchParams(o),inf=(a:string[])=>`in.(${a.join(",")})`;
const batches=<T>(a:T[],z=160)=>Array.from({length:Math.ceil(a.length/z)},(_,i)=>a.slice(i*z,(i+1)*z));
async function get(r:string,p:Record<string,string>){return requestSupabase<J[]>(r,{query:qs(p)});}
async function post(r:string,body:J[]){const out:J[]=[];for(const b of batches(body)){const x=await requestSupabase<J[]>(r,{method:"POST",body:b,prefer:"return=representation"});if(Array.isArray(x))out.push(...x);}return out;}
async function upsert(r:string,body:J[],conflict:string){for(const b of batches(body))await requestSupabase(r,{method:"POST",query:qs({on_conflict:conflict}),body:b,prefer:"resolution=merge-duplicates,return=minimal"});}
async function patch(r:string,p:Record<string,string>,body:J){await requestSupabase(r,{method:"PATCH",query:qs(p),body,prefer:"return=minimal"});}
async function remove(r:string,p:Record<string,string>){await requestSupabase(r,{method:"DELETE",query:qs(p),prefer:"return=minimal"});}
function readPlan(){const k=Number(process.env.FLOW_IMPORT_PLAN_PARTS??0);if(k!==15)throw new Error(`Partes FLOW=${k}`);const enc=Array.from({length:k},(_,i)=>process.env[`FLOW_IMPORT_PLAN_${String(i).padStart(2,"0")}`]??"").join("");const buf=gunzipSync(Buffer.from(enc,"base64"));const sha=createHash("sha256").update(buf).digest("hex");if(sha!==process.env.FLOW_IMPORT_PLAN_SHA256)throw new Error(`Hash FLOW inválido ${sha}`);return JSON.parse(buf.toString("utf8")) as J;}
const pl=readPlan(),arr=(k:string)=>Array.isArray(pl[k])?pl[k] as J[]:[],budget=pl.budget&&typeof pl.budget==="object"?pl.budget as J:{};
const groups=arr("groups"),services=arr("services"),inputs=arr("inputs"),comps=arr("compositions"),items=arr("budget_items"),adjust=arr("adjustments").filter(r=>s(r.status||"active")==="active"),active=items.filter(r=>s(r.status||"active")==="active");
const target=n(budget.target_total),sum=(a:J[],k:string)=>a.reduce((t,r)=>t+n(r[k]),0),planTotal=sum(active,"row_total")+sum(adjust,"row_total"),groupTotal=sum(groups,"total");
if(groups.length!==34||services.length!==161||inputs.length!==242||comps.length!==102||items.length!==161||adjust.length!==6)throw new Error("Contagens FLOW divergentes");
if(Math.abs(planTotal-target)>.02||Math.abs(groupTotal-target)>.02)throw new Error(`Total FLOW divergente ${planTotal}/${groupTotal}/${target}`);
const inputCodes=new Set(inputs.map(r=>s(r.code))),serviceCodes=new Set(services.map(r=>s(r.code)));
type N={service_code:string,input_code:string,effective:number,unit_price:number,price_source:string,sort_order:number};
const raw:N[]=[];let outlierWaste=0,reconstructedZero=0;
for(const c of comps){const sc=s(c.service_code);if(!serviceCodes.has(sc))throw new Error(`Serviço ausente ${sc}`);for(const i of(Array.isArray(c.items)?c.items as J[]:[])){const ic=s(i.input_code),w=n(i.waste_percentage),coef=n(i.coefficient),eff=n(i.effective_coefficient);if(!inputCodes.has(ic))throw new Error(`Insumo ausente ${ic}`);if(!(eff>0))throw new Error(`Consumo efetivo inválido ${sc}/${ic}`);if(w<0||w>1000)outlierWaste++;if(!(coef>0))reconstructedZero++;raw.push({service_code:sc,input_code:ic,effective:eff,unit_price:n(i.unit_price),price_source:s(i.price_source)||"Orçamento FLOW",sort_order:n(i.sort_order)});}}
const pair=new Map<string,N>();
for(const r of raw){const k=`${r.service_code}|${r.input_code}`,old=pair.get(k);if(!old){pair.set(k,{...r});continue;}if(Math.abs(old.unit_price-r.unit_price)>.02)throw new Error(`Preço divergente na duplicata ${k}`);old.effective+=r.effective;old.sort_order=Math.min(old.sort_order,r.sort_order);}
const norm=[...pair.values()];if(raw.length!==343||norm.length!==333)throw new Error(`Normalização inesperada ${raw.length}->${norm.length}`);
const rawCost=raw.reduce((t,r)=>t+r.effective*r.unit_price,0),normCost=norm.reduce((t,r)=>t+r.effective*r.unit_price,0);if(Math.abs(rawCost-normCost)>.001)throw new Error(`Custo comp mudou ${rawCost}/${normCost}`);
const prices=new Map<string,{price:number,source:string}>();for(const r of raw){if(r.unit_price<=0)continue;const old=prices.get(r.input_code);if(old&&Math.abs(old.price-r.unit_price)>.02)throw new Error(`Preço conflitante ${r.input_code}: ${old.price}/${r.unit_price}`);prices.set(r.input_code,{price:r.unit_price,source:r.price_source});}
async function snap(code:string){const b=(await get("engineering_budgets",{select:"id,status,is_base",company_id:`eq.${C}`,project_id:`eq.${P}`,code:`eq.${code}`,limit:"5"}))[0];if(!b?.id)return{id:null,count:0,total:0,status:null,is_base:false};const rs=await get("engineering_budget_items",{select:"id,status,total_direct_cost",budget_id:`eq.${String(b.id)}`,limit:"2000"}),ac=rs.filter(r=>s(r.status)==="active");return{id:String(b.id),count:ac.length,total:ac.reduce((t,r)=>t+n(r.total_direct_cost),0),status:s(b.status),is_base:Boolean(b.is_base)};}
const koper0=await snap("KOPER-100");if(!koper0.id||koper0.count!==108)throw new Error(`KOPER-100 fora da base ${JSON.stringify(koper0)}`);
const existingFlow=await snap(CODE);
const existingCompHeaders=await get("engineering_service_compositions",{select:"id,service_id",company_id:`eq.${C}`,limit:"1000"});
const currentCompIds=existingCompHeaders.map(r=>String(r.id));let currentActiveCompItems=0;if(currentCompIds.length){for(const ids of batches(currentCompIds,100)){currentActiveCompItems+=(await get("engineering_service_composition_items",{select:"id",composition_id:inf(ids),status:"eq.active",limit:"2000"})).length;}}
if(!WRITE){console.log("FLOW_IMPORT_V4_DRY_RUN",JSON.stringify({ok:true,target,planTotal,groupTotal,rawCompositionRows:raw.length,normalizedCompositionRows:norm.length,duplicateRowsCollapsed:raw.length-norm.length,outlierWasteRows:outlierWaste,reconstructedZeroRows:reconstructedZero,rawCompositionCost:rawCost,normalizedCompositionCost:normCost,pricedInputs:prices.size,existingFlow,koperBefore:koper0,currentActiveCompositionItems:currentActiveCompItems}));process.exit(0);}

await upsert("engineering_services",services.map(r=>({company_id:C,code:s(r.code),description:s(r.description),unit:s(r.unit)||"un",group_code:s(r.group_code)||null,notes:s(r.notes)||null,status:"active"})),"company_id,code");
await upsert("engineering_inputs",inputs.map(r=>({company_id:C,code:s(r.code),description:s(r.description),unit:s(r.unit)||"un",category:s(r.category)||"material",notes:"Base padrão FLOW Rev.03 V4",status:"active"})),"company_id,code");
const sr=await get("engineering_services",{select:"id,code",company_id:`eq.${C}`,code:inf([...serviceCodes]),limit:"1000"}),ir=await get("engineering_inputs",{select:"id,code",company_id:`eq.${C}`,code:inf([...inputCodes]),limit:"2000"}),sm=new Map(sr.map(r=>[s(r.code),String(r.id)])),im=new Map(ir.map(r=>[s(r.code),String(r.id)]));if(sm.size!==161||im.size!==242)throw new Error(`Catálogo ${sm.size}/161 ${im.size}/242`);
await upsert("engineering_service_compositions",comps.map(c=>({company_id:C,service_id:sm.get(s(c.service_code)),notes:"Composição padrão FLOW Rev.03 V4 · coeficientes efetivos consolidados",status:"active"})),"company_id,service_id");
const wantedServiceIds=comps.map(c=>sm.get(s(c.service_code))!).filter(Boolean),cr=await get("engineering_service_compositions",{select:"id,service_id",company_id:`eq.${C}`,service_id:inf(wantedServiceIds),limit:"1000"}),cm=new Map(cr.map(r=>[String(r.service_id),String(r.id)]));if(cm.size!==102)throw new Error(`Composições ${cm.size}/102`);const compIds=[...cm.values()];
await patch("engineering_service_composition_items",{composition_id:inf(compIds),status:"eq.active"},{status:"inactive",notes:"Substituído pela composição consolidada FLOW Rev.03 V4"});
await upsert("engineering_service_composition_items",norm.map(r=>({company_id:C,composition_id:cm.get(sm.get(r.service_code)!),input_id:im.get(r.input_code),coefficient:r.effective,waste_percentage:0,sort_order:r.sort_order,notes:"Coeficiente efetivo consolidado da base FLOW Rev.03 V4",status:"active"})),"composition_id,input_id");
const pricedIds=[...prices.keys()].map(k=>im.get(k)!).filter(Boolean);if(pricedIds.length){await patch("engineering_input_prices",{company_id:`eq.${C}`,project_id:`eq.${P}`,input_id:inf(pricedIds),is_adopted:"eq.true",status:"eq.active"},{is_adopted:false});await post("engineering_input_prices",[...prices.entries()].map(([code,p])=>({company_id:C,project_id:P,input_id:im.get(code),price_date:s(budget.reference_date)||"2026-08-20",unit_price:p.price,freight_unit_cost:0,other_unit_cost:0,discount_percentage:0,currency:"BRL",is_adopted:true,source:p.source,notes:"Preço adotado FLOW Rev.03 V4",status:"active"})));}
const olds=await get("engineering_budgets",{select:"id,is_base",company_id:`eq.${C}`,project_id:`eq.${P}`,code:`eq.${CODE}`,version:`eq.${s(budget.version)}`,limit:"5"});for(const o of olds){if(o.is_base)throw new Error("FLOW alvo é base; abortado");await remove("engineering_budgets",{id:`eq.${String(o.id)}`});}
const br=await post("engineering_budgets",[{company_id:C,project_id:P,code:CODE,name:s(budget.name),version:s(budget.version),status:"review",reference_date:s(budget.reference_date),area_m2:0,bdi_percentage:0,notes:`Orçamento oficial FLOW Rev.03 V4 · total alvo R$ ${target.toFixed(2)} · Portinari excluído`,source_system:"elos_os",source_id:"flow-rev03-v4-2026-08-20"}]),bid=String(br[0]?.id??"");if(!bid)throw new Error("FLOW não criado");
const gr=await post("engineering_budget_groups",groups.map(g=>({company_id:C,project_id:P,budget_id:bid,code:s(g.code),name:s(g.name),sort_order:n(g.sort_order??g.sort),notes:`Subtotal oficial: ${n(g.total).toFixed(6)}`,status:"active"}))),gm=new Map(gr.map(g=>[s(g.code),String(g.id)]));if(gm.size!==34)throw new Error(`Grupos ${gm.size}/34`);
function costs(r:J){const u=n(r.unit_cost),x=s(r.nature).toLowerCase();if(x.includes("material"))return{material_unit_cost:u,labor_unit_cost:0,equipment_unit_cost:0,other_unit_cost:0};if(x.includes("mão")||x.includes("mao")||x.includes("labor"))return{material_unit_cost:0,labor_unit_cost:u,equipment_unit_cost:0,other_unit_cost:0};if(x.includes("equip"))return{material_unit_cost:0,labor_unit_cost:0,equipment_unit_cost:u,other_unit_cost:0};return{material_unit_cost:0,labor_unit_cost:0,equipment_unit_cost:0,other_unit_cost:u};}
const bp:J[]=items.map(r=>({company_id:C,project_id:P,budget_id:bid,group_id:gm.get(s(r.group))||null,code:s(r.code),description:s(r.description),unit:s(r.unit)||"un",quantity:n(r.quantity),...costs(r),sort_order:n(r.sort_order),notes:`FLOW Rev.03 V4 · linha ${s(r.source_line)||"-"}${s(r.parent)?` · pai ${s(r.parent)}`:""}${s(r.status)==="inactive"?" · referência fora do subtotal oficial":""}`,status:s(r.status)||"active",service_id:sm.get(s(r.code))||null}));for(const a of adjust)bp.push({company_id:C,project_id:P,budget_id:bid,group_id:gm.get(s(a.group))||null,code:s(a.code),description:s(a.description),unit:s(a.unit)||"vb",quantity:n(a.quantity),material_unit_cost:0,labor_unit_cost:0,equipment_unit_cost:0,other_unit_cost:n(a.unit_cost),sort_order:n(a.sort_order),notes:s(a.notes)||"Reconciliação do SUBTOTAL original",status:"active",service_id:null});await post("engineering_budget_items",bp);
const flow=await snap(CODE),koper1=await snap("KOPER-100"),rows=await get("engineering_budget_items",{select:"id,status,total_direct_cost",budget_id:`eq.${bid}`,limit:"2000"}),ac=rows.filter(r=>s(r.status)==="active"),ina=rows.filter(r=>s(r.status)!=="active"),final=ac.reduce((t,r)=>t+n(r.total_direct_cost),0),mc=await get("engineering_service_composition_items",{select:"id",composition_id:inf(compIds),status:"eq.active",limit:"2000"});
let ok=flow.id===bid&&ac.length===156&&ina.length===11&&Math.abs(final-target)<.02&&koper1.id===koper0.id&&koper1.count===koper0.count&&Math.abs(koper1.total-koper0.total)<.02&&mc.length===333;
if(ok){await patch("engineering_budgets",{id:`eq.${bid}`},{status:"approved"});const approved=await snap(CODE);ok=approved.id===bid&&approved.status==="approved";}
console.log("FLOW_IMPORT_V4_RESULT",JSON.stringify({ok,budgetId:bid,targetTotal:target,finalTotal:final,activeItems:ac.length,inactiveItems:ina.length,groups:gr.length,servicesResolved:sm.size,inputsResolved:im.size,serviceCompositions:cr.length,compositionItems:mc.length,rawCompositionRows:raw.length,duplicateRowsCollapsed:raw.length-norm.length,outlierWasteRows:outlierWaste,reconstructedZeroRows:reconstructedZero,adoptedProjectPrices:prices.size,koperBefore:koper0,koperAfter:koper1,status:ok?"approved":"verification_failed"}));if(!ok)throw new Error("Verificação pós-carga FLOW V4 falhou");
