import { gunzipSync } from "node:zlib";
import { env } from "../config/env.js";
import { requestSupabase } from "../elos/supabase.js";
type J=Record<string,unknown>;
const C=env.BOSSA_COMPANY_ID,P="ffe8b7ec-1f01-4f6c-8a03-2bd6d3ae94fc",CODE="FLOW-REV03-V4";
const s=(v:unknown)=>String(v??"").trim(),n=(v:unknown)=>typeof v==="number"?v:Number(v??0),q=(o:Record<string,string>)=>new URLSearchParams(o),inf=(a:string[])=>`in.(${a.join(",")})`;
async function get(r:string,p:Record<string,string>){return requestSupabase<J[]>(r,{query:q(p)});}
const k=Number(process.env.FLOW_IMPORT_PLAN_PARTS??0),enc=Array.from({length:k},(_,i)=>process.env[`FLOW_IMPORT_PLAN_${String(i).padStart(2,"0")}`]??"").join(""),pl=JSON.parse(gunzipSync(Buffer.from(enc,"base64")).toString("utf8")) as J;
const arr=(x:string)=>Array.isArray(pl[x])?pl[x] as J[]:[],pg=arr("groups"),ps=arr("services"),pi=arr("inputs"),pc=arr("compositions"),budgetMeta=pl.budget&&typeof pl.budget==="object"?pl.budget as J:{};
const budgets=await get("engineering_budgets",{select:"id,code,name,version,status,reference_date,is_base",company_id:`eq.${C}`,project_id:`eq.${P}`,code:`eq.${CODE}`,version:`eq.${s(budgetMeta.version)}`,limit:"10"});
if(budgets.length!==1)throw new Error(`Esperado 1 FLOW, encontrado ${budgets.length}`);const b=budgets[0]!,bid=String(b.id);
const groups=await get("engineering_budget_groups",{select:"id,code,name,status",budget_id:`eq.${bid}`,limit:"100"}),items=await get("engineering_budget_items",{select:"id,group_id,code,description,status,total_direct_cost",budget_id:`eq.${bid}`,limit:"2000"});
const active=items.filter(r=>s(r.status)==="active"),inactive=items.filter(r=>s(r.status)!=="active"),total=active.reduce((a,r)=>a+n(r.total_direct_cost),0),target=n(budgetMeta.target_total),groupIdCode=new Map(groups.map(g=>[String(g.id),s(g.code)])),actualByGroup=new Map<string,number>();for(const r of active){const c=groupIdCode.get(String(r.group_id))??"";actualByGroup.set(c,(actualByGroup.get(c)??0)+n(r.total_direct_cost));}
const groupChecks=pg.map(g=>{const code=s(g.code),expected=n(g.total),actual=actualByGroup.get(code)??0,diff=actual-expected;return{code,expected,actual,diff,ok:Math.abs(diff)<0.011};});
const serviceCodes=ps.map(r=>s(r.code)),inputCodes=pi.map(r=>s(r.code));
const services=await get("engineering_services",{select:"id,code,status",company_id:`eq.${C}`,code:inf(serviceCodes),limit:"1000"}),inputs=await get("engineering_inputs",{select:"id,code,description,status",company_id:`eq.${C}`,code:inf(inputCodes),limit:"1000"});
const serviceIdByCode=new Map(services.map(r=>[s(r.code),String(r.id)])),inputIds=new Set(inputs.map(r=>String(r.id))),compServiceIds=pc.map(c=>serviceIdByCode.get(s(c.service_code))!).filter(Boolean),comps=await get("engineering_service_compositions",{select:"id,service_id,status",company_id:`eq.${C}`,service_id:inf(compServiceIds),status:"eq.active",limit:"1000"}),compIds=comps.map(r=>String(r.id));
let compItems:J[]=[];if(compIds.length)compItems=await get("engineering_service_composition_items",{select:"id,composition_id,input_id,coefficient,waste_percentage,status",composition_id:inf(compIds),status:"eq.active",limit:"2000"});
const adopted=await get("engineering_input_prices",{select:"id,input_id,is_adopted,status",company_id:`eq.${C}`,project_id:`eq.${P}`,is_adopted:"eq.true",status:"eq.active",limit:"2000"}),targetAdopted=adopted.filter(r=>inputIds.has(String(r.input_id)));
const portinari=inputs.filter(r=>s(r.description).toLowerCase().includes("portinari"));
const koper=(await get("engineering_budgets",{select:"id,status",company_id:`eq.${C}`,project_id:`eq.${P}`,code:"eq.KOPER-100",limit:"2"}))[0];if(!koper?.id)throw new Error("KOPER-100 ausente");const ki=await get("engineering_budget_items",{select:"id,status,total_direct_cost",budget_id:`eq.${String(koper.id)}`,limit:"1000"}),ka=ki.filter(r=>s(r.status)==="active"),kt=ka.reduce((a,r)=>a+n(r.total_direct_cost),0);
const badWaste=compItems.filter(r=>n(r.waste_percentage)!==0),badCoeff=compItems.filter(r=>!(n(r.coefficient)>0));
const ok=s(b.status)==="approved"&&groups.length===34&&active.length===156&&inactive.length===11&&Math.abs(total-target)<0.011&&groupChecks.every(x=>x.ok)&&services.length===161&&inputs.length===242&&comps.length===102&&compItems.length===333&&badWaste.length===0&&badCoeff.length===0&&targetAdopted.length===227&&portinari.length===0&&String(koper.id)==="ba09991f-818c-486c-a7bf-97d34c294050"&&ka.length===108&&Math.abs(kt-18151335.3024)<0.001;
console.log("FLOW_FINAL_AUDIT",JSON.stringify({ok,budget:{id:bid,code:s(b.code),name:s(b.name),version:s(b.version),status:s(b.status),reference_date:s(b.reference_date),targetTotal:target,actualTotal:total,difference:total-target},counts:{groups:groups.length,activeItems:active.length,inactiveItems:inactive.length,services:services.length,inputs:inputs.length,serviceCompositions:comps.length,compositionItems:compItems.length,adoptedTargetPrices:targetAdopted.length,portinari:portinari.length,badWaste:badWaste.length,badCoefficient:badCoeff.length},groupChecks,koper:{id:String(koper.id),status:s(koper.status),activeItems:ka.length,total:kt}}));if(!ok)throw new Error("Auditoria final FLOW falhou");
