import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { fetchAllRows } from "@/lib/supabase-pagination";
import { requireCompanyPermission } from "@/lib/workspace";
import {
  cancelPurchaseOrder, closePurchaseOrder, confirmPurchaseOrder, generatePurchaseOrders,
  issuePurchaseOrder, removePurchaseOrderDocument, uploadPurchaseOrderDocuments,
} from "./actions";
import { PrintPurchaseOrderButton, PurchaseOrderHeaderDialog, type PurchaseOrderRecord } from "./order-client";
import "../../procurement-purchase-orders.css";

type Project={id:string;code:string|null;name:string};
type Supplier={id:string;legal_name:string;trade_name:string|null;tax_id:string|null};
type Quotation={id:string;quotation_number:string;title:string;status:string;desired_delivery_date:string|null;delivery_address:string|null;total_awarded_amount:number;approved_at:string|null};
type Award={id:string;quotation_id:string;supplier_id:string;awarded_total_cost:number};
type Order=PurchaseOrderRecord&{company_id:string;project_id:string;sequence_no:number;subtotal_amount:number;freight_amount:number;tax_amount:number;other_cost_amount:number;discount_amount:number;total_amount:number;received_amount:number;invoiced_amount:number;buyer_name:string|null;supplier_confirmation_reference:string|null;issued_at:string|null;confirmed_at:string|null;closed_at:string|null;cancellation_reason:string|null;created_at:string};
type OrderItem={id:string;order_id:string;award_id:string|null;request_number:string;input_code:string;input_name:string;unit_snapshot:string;cost_center_code:string;cost_center_name:string;brand:string|null;manufacturer:string|null;ordered_quantity:number;received_quantity:number;accepted_quantity:number;rejected_quantity:number;cancelled_quantity:number;unit_price:number;discount_percent:number;tax_percent:number;freight_amount:number;other_cost_amount:number;delivered_unit_cost:number;total_amount:number;expected_delivery_date:string|null;notes:string|null};
type Document={id:string;order_id:string;document_type:string;storage_path:string;file_name:string;caption:string|null;uploaded_at:string};
type SignedDocument=Document&{signed_url:string|null};

const statusLabels:Record<string,string>={draft:"Em elaboração",issued:"Emitido",confirmed:"Confirmado",partially_received:"Recebimento parcial",received:"Recebido",closed:"Encerrado",cancelled:"Cancelado"};
const documentLabels:Record<string,string>={order:"Pedido",supplier_confirmation:"Confirmação",invoice:"Nota fiscal",delivery:"Entrega",technical:"Técnico",other:"Outro"};
function money(value:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value||0));}
function qty(value:number,digits=4){return new Intl.NumberFormat("pt-BR",{maximumFractionDigits:digits}).format(Number(value||0));}
function dateBR(value?:string|null){return value?new Intl.DateTimeFormat("pt-BR",{timeZone:"UTC"}).format(new Date(`${value.slice(0,10)}T12:00:00Z`)):"—";}
function supplierName(supplier?:Supplier|null){return supplier?supplier.trade_name||supplier.legal_name:"Fornecedor não localizado";}

export default async function PurchaseOrdersPage({searchParams}:{searchParams:Promise<{order?:string;q?:string;status?:string;edit?:string;success?:string;error?:string}>}){
  const params=await searchParams;
  const {supabase,company,companyId,projectId,roleKey}=await requireCompanyPermission("procurement.orders.view");
  const privileged=roleKey==="owner"||roleKey==="admin";
  const permission=(key:string)=>privileged?Promise.resolve({data:true,error:null}):supabase.rpc("has_company_permission",{target_company_id:companyId,target_permission:key});
  const [projectResult,quotesResult,awardsResult,ordersResult,itemsResult,docsResult,suppliersResult,manageResult,issueResult,confirmResult,cancelResult]=await Promise.all([
    projectId?supabase.from("projects").select("id,code,name").eq("id",projectId).eq("company_id",companyId).maybeSingle():Promise.resolve({data:null,error:null}),
    projectId?fetchAllRows<Quotation>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_quotations").select("id,quotation_number,title,status,desired_delivery_date,delivery_address,total_awarded_amount,approved_at").eq("company_id",companyId).eq("project_id",projectId).eq("status","approved").order("approved_at",{ascending:false}).range(from,to);return{data:(data??[])as Quotation[],error};}):Promise.resolve({data:[]as Quotation[],error:null}),
    projectId?fetchAllRows<Award>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_quotation_awards").select("id,quotation_id,supplier_id,awarded_total_cost").eq("company_id",companyId).eq("project_id",projectId).range(from,to);return{data:(data??[])as Award[],error};}):Promise.resolve({data:[]as Award[],error:null}),
    projectId?fetchAllRows<Order>(async(from,to)=>{const{data,error}=await supabase.from("procurement_purchase_orders").select("id,company_id,project_id,quotation_id,supplier_id,sequence_no,order_number,status,issue_date,expected_delivery_date,delivery_address,payment_terms,freight_terms,warranty_terms,supplier_contact_name,supplier_contact_email,supplier_contact_phone,buyer_name,subtotal_amount,freight_amount,tax_amount,other_cost_amount,discount_amount,total_amount,received_amount,invoiced_amount,notes,supplier_notes,supplier_confirmation_reference,issued_at,confirmed_at,closed_at,cancellation_reason,created_at").eq("company_id",companyId).eq("project_id",projectId).order("created_at",{ascending:false}).range(from,to);return{data:(data??[])as Order[],error};}):Promise.resolve({data:[]as Order[],error:null}),
    projectId?fetchAllRows<OrderItem>(async(from,to)=>{const{data,error}=await supabase.from("procurement_purchase_order_items").select("id,order_id,award_id,request_number,input_code,input_name,unit_snapshot,cost_center_code,cost_center_name,brand,manufacturer,ordered_quantity,received_quantity,accepted_quantity,rejected_quantity,cancelled_quantity,unit_price,discount_percent,tax_percent,freight_amount,other_cost_amount,delivered_unit_cost,total_amount,expected_delivery_date,notes").eq("company_id",companyId).eq("project_id",projectId).order("sort_order").range(from,to);return{data:(data??[])as OrderItem[],error};}):Promise.resolve({data:[]as OrderItem[],error:null}),
    projectId?fetchAllRows<Document>(async(from,to)=>{const{data,error}=await supabase.from("procurement_purchase_order_documents").select("id,order_id,document_type,storage_path,file_name,caption,uploaded_at").eq("company_id",companyId).eq("project_id",projectId).order("uploaded_at",{ascending:false}).range(from,to);return{data:(data??[])as Document[],error};}):Promise.resolve({data:[]as Document[],error:null}),
    fetchAllRows<Supplier>(async(from,to)=>{const{data,error}=await supabase.from("suppliers").select("id,legal_name,trade_name,tax_id").eq("company_id",companyId).order("legal_name").range(from,to);return{data:(data??[])as Supplier[],error};}),
    permission("procurement.orders.manage"),permission("procurement.orders.issue"),permission("procurement.orders.confirm"),permission("procurement.orders.cancel"),
  ]);
  const project=projectResult.data as Project|null;
  const orders=ordersResult.data;
  const supplierMap=new Map(suppliersResult.data.map(s=>[s.id,s]));
  const quoteMap=new Map(quotesResult.data.map(q=>[q.id,q]));
  const itemMap=new Map<string,OrderItem[]>();itemsResult.data.forEach(i=>itemMap.set(i.order_id,[...(itemMap.get(i.order_id)??[]),i]));
  const docMap=new Map<string,Document[]>();docsResult.data.forEach(d=>docMap.set(d.order_id,[...(docMap.get(d.order_id)??[]),d]));
  const convertedAwards=new Set(itemsResult.data.flatMap(i=>i.award_id?[i.award_id]:[]));
  const eligibleQuotes=quotesResult.data.filter(q=>awardsResult.data.some(a=>a.quotation_id===q.id&&!convertedAwards.has(a.id)));
  const selected=params.order?orders.find(o=>o.id===params.order)??null:null;
  const selectedItems=selected?itemMap.get(selected.id)??[]:[];
  const selectedDocs=selected?docMap.get(selected.id)??[]:[];
  let signedDocs:SignedDocument[]=[];
  if(selectedDocs.length){const signed=await supabase.storage.from("purchase-order-documents").createSignedUrls(selectedDocs.map(d=>d.storage_path),3600);const urls=new Map((signed.data??[]).map(i=>[i.path,i.signedUrl]));signedDocs=selectedDocs.map(d=>({...d,signed_url:urls.get(d.storage_path)??null}));}
  const canManage=manageResult.data===true||privileged;const canIssue=issueResult.data===true||privileged;const canConfirm=confirmResult.data===true||privileged;const canCancel=cancelResult.data===true||privileged;
  const structureError=ordersResult.error||itemsResult.error||docsResult.error;
  const query=(params.q??"").trim().toLocaleLowerCase("pt-BR");
  const filtered=orders.filter(o=>!params.status||o.status===params.status).filter(o=>!query||[o.order_number,supplierName(supplierMap.get(o.supplier_id)),quoteMap.get(o.quotation_id)?.quotation_number??"",...(itemMap.get(o.id)??[]).flatMap(i=>[i.input_code,i.input_name,i.cost_center_name])].join(" ").toLocaleLowerCase("pt-BR").includes(query));
  const open=orders.filter(o=>!["closed","cancelled"].includes(o.status));
  const committed=orders.filter(o=>!["draft","cancelled"].includes(o.status)).reduce((s,o)=>s+Number(o.total_amount),0);
  const received=orders.reduce((s,o)=>s+Number(o.received_amount),0);
  const delayed=orders.filter(o=>!["received","closed","cancelled"].includes(o.status)&&o.expected_delivery_date&&o.expected_delivery_date<new Date().toISOString().slice(0,10)).length;
  const context=project?`${project.code?`${project.code} · `:""}${project.name}`:"Selecione uma obra";

  return <AppShell activeGroup="procurement" activeItem="purchase-orders" eyebrow="Suprimentos · Compras" title="Pedidos de Compras" description={`${company.name} · ${context} · compromissos por fornecedor, entrega, documentos e saldo a receber.`}>
    {params.success?<div className="auth-message success workspace-message">{params.success}</div>:null}
    {params.error?<div className="auth-message error workspace-message">{params.error}</div>:null}
    {structureError?<div className="auth-message error workspace-message">A estrutura de pedidos ainda não está instalada. Execute a migration <strong>20260729_0042_procurement_purchase_orders.sql</strong>.</div>:null}
    {!projectId?<div className="purchase-order-empty">Selecione uma obra no topo.</div>:null}
    {projectId&&selected?<OrderDetail order={selected} items={selectedItems} documents={signedDocs} supplier={supplierMap.get(selected.supplier_id)??null} quotation={quoteMap.get(selected.quotation_id)??null} canManage={canManage} canIssue={canIssue} canConfirm={canConfirm} canCancel={canCancel} autoEdit={params.edit==="1"}/>:projectId?<>
      <section className="purchase-order-kpis"><article><span>Cotações liberadas</span><strong>{eligibleQuotes.length}</strong><small>possuem vencedores sem pedido</small></article><article><span>Pedidos em aberto</span><strong>{open.length}</strong><small>da elaboração ao recebimento</small></article><article><span>Valor comprometido</span><strong>{money(committed)}</strong><small>pedidos emitidos</small></article><article><span>Valor recebido</span><strong>{money(received)}</strong><small>materiais aceitos</small></article><article><span>Entregas atrasadas</span><strong>{delayed}</strong><small>prazo previsto vencido</small></article></section>
      {eligibleQuotes.length?<section className="purchase-order-release"><div><span>Prontos para conversão</span><h2>Cotações aprovadas</h2><p>Cada fornecedor vencedor gera um pedido independente.</p></div><div>{eligibleQuotes.map(q=><article key={q.id}><div><strong>{q.quotation_number} · {q.title}</strong><small>{money(q.total_awarded_amount)} · entrega desejada {dateBR(q.desired_delivery_date)}</small></div>{canManage?<form action={generatePurchaseOrders}><input type="hidden" name="quotation_id" value={q.id}/><button type="submit">Gerar pedidos</button></form>:null}</article>)}</div></section>:null}
      <section className="purchase-order-toolbar"><form method="get"><input name="q" defaultValue={params.q??""} placeholder="Buscar pedido, fornecedor, material ou serviço"/><select name="status" defaultValue={params.status??""}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button type="submit">Filtrar</button><Link href="/suprimentos/pedidos-compras">Limpar</Link></form></section>
      <section className="purchase-order-list"><div className="budget-section-head"><div><span>Pedidos da obra</span><h2>Compras emitidas e em elaboração</h2></div><p>{filtered.length} pedido(s)</p></div><div className="registry-table-wrap"><table className="registry-table purchase-order-table"><thead><tr><th>Pedido</th><th>Fornecedor</th><th>Cotação</th><th>Entrega</th><th>Itens</th><th>Total</th><th>Recebido</th><th>Saldo</th><th>Status</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id}><td><Link href={`?order=${o.id}`}><strong>{o.order_number}</strong><span>{o.issue_date?`Emitido em ${dateBR(o.issue_date)}`:"Ainda não emitido"}</span></Link></td><td><strong>{supplierName(supplierMap.get(o.supplier_id))}</strong><span>{supplierMap.get(o.supplier_id)?.tax_id??""}</span></td><td>{quoteMap.get(o.quotation_id)?.quotation_number??"—"}<span>{quoteMap.get(o.quotation_id)?.title??""}</span></td><td className={o.expected_delivery_date&&o.expected_delivery_date<new Date().toISOString().slice(0,10)&&!["received","closed","cancelled"].includes(o.status)?"late":""}>{dateBR(o.expected_delivery_date)}</td><td>{(itemMap.get(o.id)??[]).length}</td><td><strong>{money(o.total_amount)}</strong></td><td>{money(o.received_amount)}</td><td>{money(Math.max(0,o.total_amount-o.received_amount))}</td><td><span className={`purchase-order-status ${o.status}`}>{statusLabels[o.status]}</span></td></tr>)}{!filtered.length?<tr><td colSpan={9} className="budget-empty-state">Nenhum pedido encontrado.</td></tr>:null}</tbody></table></div></section>
    </>:null}
  </AppShell>;
}

function OrderDetail({order,items,documents,supplier,quotation,canManage,canIssue,canConfirm,canCancel,autoEdit}:{order:Order;items:OrderItem[];documents:SignedDocument[];supplier:Supplier|null;quotation:Quotation|null;canManage:boolean;canIssue:boolean;canConfirm:boolean;canCancel:boolean;autoEdit:boolean}){
  const orderedQty=items.reduce((s,i)=>s+Number(i.ordered_quantity-i.cancelled_quantity),0);const receivedQty=items.reduce((s,i)=>s+Number(i.received_quantity),0);
  return <div className="purchase-order-print-area">
    <div className="purchase-order-back no-print"><Link href="/suprimentos/pedidos-compras">← Voltar aos pedidos</Link><div><PrintPurchaseOrderButton/>{canManage&&order.status==="draft"?<PurchaseOrderHeaderDialog order={order} autoOpen={autoEdit}/>:null}</div></div>
    <section className="purchase-order-hero"><div><span>Pedido de Compra</span><h2>{order.order_number}</h2><p>{supplierName(supplier)} · {supplier?.tax_id??"CPF/CNPJ não informado"}</p></div><div><span className={`purchase-order-status ${order.status}`}>{statusLabels[order.status]}</span><strong>{money(order.total_amount)}</strong></div></section>
    <section className="purchase-order-summary"><article><span>Cotação de origem</span><strong>{quotation?.quotation_number??"—"}</strong><small>{quotation?.title??""}</small></article><article><span>Emissão</span><strong>{dateBR(order.issue_date)}</strong><small>{order.buyer_name||"Comprador não informado"}</small></article><article><span>Entrega prevista</span><strong>{dateBR(order.expected_delivery_date)}</strong><small>{order.delivery_address||"Endereço não informado"}</small></article><article><span>Progresso de entrega</span><strong>{orderedQty?qty(receivedQty/orderedQty*100,1):"0"}%</strong><small>{qty(receivedQty)} de {qty(orderedQty)}</small></article><article><span>Saldo a receber</span><strong>{money(Math.max(0,order.total_amount-order.received_amount))}</strong><small>valor posto na obra</small></article></section>
    <section className="purchase-order-card"><div className="purchase-order-card-head"><div><span>Itens do pedido</span><h3>Materiais, serviços e valores</h3></div><strong>{items.length} item(ns)</strong></div><div className="registry-table-wrap"><table className="registry-table purchase-order-items"><thead><tr><th>Material</th><th>Solicitação</th><th>Centro de custo</th><th>Marca</th><th>Quantidade</th><th>Preço base</th><th>Desconto</th><th>Impostos</th><th>Custo posto</th><th>Total</th><th>Recebido</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.input_code}</strong><span>{i.input_name}</span></td><td>{i.request_number}</td><td><strong>{i.cost_center_code}</strong><span>{i.cost_center_name}</span></td><td>{i.brand||"—"}<span>{i.manufacturer||""}</span></td><td>{qty(i.ordered_quantity)} {i.unit_snapshot}</td><td>{money(i.unit_price)}</td><td>{qty(i.discount_percent,2)}%</td><td>{qty(i.tax_percent,2)}%</td><td><strong>{money(i.delivered_unit_cost)}</strong></td><td><strong>{money(i.total_amount)}</strong></td><td>{qty(i.received_quantity)}<span>aceito {qty(i.accepted_quantity)}</span></td></tr>)}</tbody></table></div></section>
    <section className="purchase-order-grid"><article className="purchase-order-card"><div className="purchase-order-card-head"><div><span>Condições comerciais</span><h3>Entrega e pagamento</h3></div></div><dl><div><dt>Pagamento</dt><dd>{order.payment_terms||"—"}</dd></div><div><dt>Frete</dt><dd>{order.freight_terms||"—"}</dd></div><div><dt>Garantia</dt><dd>{order.warranty_terms||"—"}</dd></div><div><dt>Contato</dt><dd>{order.supplier_contact_name||"—"}</dd></div><div><dt>Telefone</dt><dd>{order.supplier_contact_phone||"—"}</dd></div><div><dt>E-mail</dt><dd>{order.supplier_contact_email||"—"}</dd></div></dl>{order.supplier_notes?<div className="purchase-order-note"><strong>Instruções ao fornecedor</strong><p>{order.supplier_notes}</p></div>:null}</article><article className="purchase-order-card no-print"><div className="purchase-order-card-head"><div><span>Arquivo privado</span><h3>Documentos</h3></div><strong>{documents.length}</strong></div>{documents.length?<div className="purchase-order-docs">{documents.map(d=><div key={d.id}><div><strong>{d.file_name}</strong><small>{documentLabels[d.document_type]} · {dateBR(d.uploaded_at)}</small></div>{d.signed_url?<a href={d.signed_url} target="_blank" rel="noreferrer">Abrir</a>:null}{canManage&&order.status==="draft"?<form action={removePurchaseOrderDocument}><input type="hidden" name="order_id" value={order.id}/><input type="hidden" name="document_id" value={d.id}/><button>Remover</button></form>:null}</div>)}</div>:<p>Nenhum documento anexado.</p>}{canManage?<form action={uploadPurchaseOrderDocuments} encType="multipart/form-data" className="purchase-order-upload"><input type="hidden" name="order_id" value={order.id}/><select name="document_type"><option value="order">Pedido</option><option value="supplier_confirmation">Confirmação</option><option value="invoice">Nota fiscal</option><option value="delivery">Entrega</option><option value="technical">Técnico</option><option value="other">Outro</option></select><input name="documents" type="file" multiple accept="application/pdf,image/*,.xlsx,.docx"/><input name="caption" placeholder="Legenda"/><button type="submit">Anexar</button></form>:null}</article></section>
    <section className="purchase-order-actions no-print"><div><span>Fluxo do pedido</span><h3>Ações disponíveis</h3><p>A emissão compromete as quantidades das solicitações. O recebimento será controlado no próximo módulo.</p></div><div>{canIssue&&order.status==="draft"?<form action={issuePurchaseOrder}><input type="hidden" name="order_id" value={order.id}/><button className="primary">Emitir pedido</button></form>:null}{canConfirm&&order.status==="issued"?<form action={confirmPurchaseOrder} className="purchase-order-confirm"><input type="hidden" name="order_id" value={order.id}/><input name="reference" placeholder="Confirmação do fornecedor"/><input name="confirmed_delivery_date" type="date" defaultValue={order.expected_delivery_date??""}/><input name="notes" placeholder="Observações"/><button className="primary">Confirmar fornecedor</button></form>:null}{canIssue&&order.status==="received"?<form action={closePurchaseOrder}><input type="hidden" name="order_id" value={order.id}/><input name="notes" placeholder="Observação de encerramento"/><button>Encerrar pedido</button></form>:null}{canCancel&&!["received","closed","cancelled"].includes(order.status)?<form action={cancelPurchaseOrder} className="purchase-order-cancel"><input type="hidden" name="order_id" value={order.id}/><input name="reason" required placeholder="Motivo obrigatório"/><button>Cancelar pedido</button></form>:null}</div></section>
  </div>;
}
