import Link from "next/link";
import { generatePendingDailyLogs, saveDailyLogSettings } from "./actions";
import type { DailyLogRecord, OccurrenceRow, ServiceRow, WeatherRow, WorkforceRow } from "./daily-log-client";

export type DailyLogViewRecord = DailyLogRecord & { is_current: boolean; created_at: string; submitted_at: string | null; cancellation_reason: string | null };
export type PhotoRecord = { id: string; daily_log_id: string; storage_path: string; file_name: string; caption: string | null };
export type WithLog = { daily_log_id: string };
export type DailyLogSettingsRecord = { workdays: number[]; default_shift: string; day_end: string; auto_create: boolean; allow_complementary: boolean; required_photo_count: number; retroactive_days: number };

const labels: Record<string,string> = { pending:"Pendente",in_progress:"Em preenchimento",awaiting_approval:"Aguardando aprovação",approved:"Aprovado",approved_with_reservations:"Aprovado com ressalvas",reopened:"Reaberto",cancelled:"Cancelado" };
const icons: Record<string,string> = { sunny:"☀",partly_cloudy:"⛅",cloudy:"☁",rain:"🌧",storm:"⛈",windy:"≋",fog:"◌" };
const monthNames = ["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"];

export function mapByLog<T extends WithLog>(rows:T[]) { const map=new Map<string,T[]>(); rows.forEach(row=>map.set(row.daily_log_id,[...(map.get(row.daily_log_id)??[]),row])); return map; }
export function dateBR(value?:string|null) { return value ? new Intl.DateTimeFormat("pt-BR",{timeZone:"UTC"}).format(new Date(`${value.slice(0,10)}T12:00:00Z`)) : "—"; }
function number(value:number,digits=0) { return new Intl.NumberFormat("pt-BR",{maximumFractionDigits:digits}).format(Number(value||0)); }
function monthHref(month:string,delta:number) { const [y,m]=month.split("-").map(Number); const d=new Date(Date.UTC(y,m-1+delta,1)); return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`; }
function statusClass(log:DailyLogViewRecord,today:string) { return ["pending","in_progress","reopened"].includes(log.status)&&log.log_date<today ? "overdue" : log.status; }

export function DailyLogKpis({logs,workforceMap,today}:{logs:DailyLogViewRecord[];workforceMap:Map<string,(WorkforceRow&WithLog)[]>;today:string}) {
  const filled=logs.filter(x=>["awaiting_approval","approved","approved_with_reservations"].includes(x.status)).length;
  const pending=logs.filter(x=>["pending","in_progress","reopened"].includes(x.status)).length;
  const overdue=logs.filter(x=>["pending","in_progress","reopened"].includes(x.status)&&x.log_date<today).length;
  const workers=logs.length?logs.reduce((sum,log)=>sum+(workforceMap.get(log.id)??[]).reduce((s,row)=>s+Number(row.worker_count||0),0),0)/logs.length:0;
  const hours=logs.reduce((sum,log)=>sum+(workforceMap.get(log.id)??[]).reduce((s,row)=>{if(!row.work_start||!row.work_end)return s;const [a,b]=row.work_start.split(":").map(Number),[c,d]=row.work_end.split(":").map(Number);return s+Math.max(0,c+d/60-a-b/60-Number(row.break_hours||0))*Number(row.worker_count||0)},0),0);
  return <section className="daily-log-kpis"><article><span>Diários previstos</span><strong>{logs.length}</strong><small>registros principais no mês</small></article><article><span>Preenchidos</span><strong>{filled}</strong><small>enviados ou aprovados</small></article><article className={pending?"warning":""}><span>Pendentes</span><strong>{pending}</strong><small>ainda em preenchimento</small></article><article className={overdue?"danger":""}><span>Atrasados</span><strong>{overdue}</strong><small>data anterior sem envio</small></article><article><span>Média de trabalhadores</span><strong>{number(workers,1)}</strong><small>por diário do mês</small></article><article><span>Homem-hora</span><strong>{number(hours)}</strong><small>acumulado no período</small></article></section>;
}

export function DailyCalendar({month,logs,weatherMap,workforceMap,servicesMap,occurrencesMap,photosMap,today,canManage}:{month:string;logs:DailyLogViewRecord[];weatherMap:Map<string,(WeatherRow&WithLog)[]>;workforceMap:Map<string,(WorkforceRow&WithLog)[]>;servicesMap:Map<string,(ServiceRow&WithLog)[]>;occurrencesMap:Map<string,(OccurrenceRow&WithLog)[]>;photosMap:Map<string,PhotoRecord[]>;today:string;canManage:boolean}) {
  const [year,monthNumber]=month.split("-").map(Number),first=new Date(Date.UTC(year,monthNumber-1,1)).getUTCDay(),days=new Date(Date.UTC(year,monthNumber,0)).getUTCDate();
  const cells:React.ReactNode[]=[]; for(let i=0;i<first;i++)cells.push(<div className="daily-calendar-day blank" key={`b${i}`}/>);
  for(let day=1;day<=days;day++){const date=`${month}-${String(day).padStart(2,"0")}`,log=logs.find(x=>x.log_date===date);if(!log){cells.push(<Link className={`daily-calendar-day empty ${date===today?"today":""}`} href={canManage?`?month=${month}&tab=calendar&create=${date}`:`?month=${month}&tab=calendar`} key={date}><b>{day}</b><span>Sem diário</span>{canManage?<small>Criar registro</small>:null}</Link>);continue}const team=workforceMap.get(log.id)??[],workers=team.reduce((s,x)=>s+Number(x.worker_count||0),0),companies=new Set(team.map(x=>x.supplier_id||x.company_name)).size,weather=(weatherMap.get(log.id)??[])[0],occ=occurrencesMap.get(log.id)??[],incident=occ.some(x=>x.is_safety_event||x.is_critical),important=occ.some(x=>["high","critical"].includes(x.impact));cells.push(<Link className={`daily-calendar-day ${statusClass(log,today)} ${important?"important":""} ${incident?"incident":""} ${date===today?"today":""}`} href={`?month=${month}&tab=calendar&diary=${log.id}`} key={date}><div className="daily-calendar-day-head"><b>{day}</b><span>{weather?icons[weather.condition]:""}{incident?" ⚠":""}</span></div><strong>{labels[log.status]??log.status}{statusClass(log,today)==="overdue"?" · atrasado":""}</strong><div><span>👷 {workers}</span><span>▦ {companies}</span><span>✓ {(servicesMap.get(log.id)??[]).length}</span><span>▧ {(photosMap.get(log.id)??[]).length}</span></div>{occ.length?<small>! {occ.length} ocorrência(s)</small>:<small>{log.responsible_name}</small>}<i><em style={{width:`${Number(log.completion_percent)}%`}}/></i></Link>)}
  return <section className="daily-calendar-card"><div className="daily-calendar-head"><div><span>Calendário mensal</span><h2>{monthNames[monthNumber-1]} de {year}</h2></div><div><Link href={`?month=${monthHref(month,-1)}&tab=calendar`}>‹</Link><Link href={`?month=${today.slice(0,7)}&tab=calendar`}>Mês atual</Link><Link href={`?month=${monthHref(month,1)}&tab=calendar`}>›</Link></div></div><div className="daily-calendar-grid">{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map(x=><div className="daily-calendar-weekday" key={x}>{x}</div>)}{cells}</div><div className="daily-calendar-legend"><span><i className="pending"/>Pendente</span><span><i className="in_progress"/>Em preenchimento</span><span><i className="approved"/>Aprovado</span><span><i className="overdue"/>Atrasado</span><span><i className="important"/>Ocorrência importante</span><span>⚠ Acidente / paralisação</span></div></section>;
}

export function DailyLogList({month,logs,weatherMap,workforceMap,servicesMap,occurrencesMap,photosMap,q,status}:{month:string;logs:DailyLogViewRecord[];weatherMap:Map<string,(WeatherRow&WithLog)[]>;workforceMap:Map<string,(WorkforceRow&WithLog)[]>;servicesMap:Map<string,(ServiceRow&WithLog)[]>;occurrencesMap:Map<string,(OccurrenceRow&WithLog)[]>;photosMap:Map<string,PhotoRecord[]>;q:string;status:string}) {
  const query=q.trim().toLowerCase(),filtered=logs.filter(x=>!status||x.status===status).filter(x=>!query||[x.log_number,x.responsible_name,x.log_date,...(servicesMap.get(x.id)??[]).map(s=>s.service_name)].join(" ").toLowerCase().includes(query));
  return <><section className="daily-log-toolbar"><form method="get"><input type="hidden" name="month" value={month}/><input type="hidden" name="tab" value="list"/><input name="q" defaultValue={q} placeholder="Buscar número, data, responsável ou serviço"/><select name="status" defaultValue={status}><option value="">Todos os status</option>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><button type="submit">Filtrar</button><Link href={`?month=${month}&tab=list`}>Limpar</Link></form></section><section className="daily-log-table-card"><div className="budget-section-head"><div><span>Histórico rastreável</span><h2>Lista de diários</h2></div><p>{filtered.length} registro(s), incluindo versões preservadas.</p></div><div className="registry-table-wrap"><table className="registry-table daily-log-list-table"><thead><tr><th>Data / diário</th><th>Clima</th><th>Trabalhadores</th><th>Empresas</th><th>Serviços</th><th>Fotos</th><th>Ocorrências</th><th>Status</th><th>Responsável</th><th>Aprovação</th></tr></thead><tbody>{filtered.map(log=>{const team=workforceMap.get(log.id)??[],weather=(weatherMap.get(log.id)??[])[0];return <tr key={log.id}><td><Link href={`?month=${log.log_date.slice(0,7)}&tab=list&diary=${log.id}`}><strong>{dateBR(log.log_date)}</strong><span>{log.log_number} · v{log.version}</span></Link></td><td>{weather?`${icons[weather.condition]} ${weather.condition}`:"—"}</td><td><strong>{team.reduce((s,x)=>s+Number(x.worker_count||0),0)}</strong></td><td>{new Set(team.map(x=>x.supplier_id||x.company_name)).size}</td><td>{(servicesMap.get(log.id)??[]).length}</td><td>{(photosMap.get(log.id)??[]).length}</td><td>{(occurrencesMap.get(log.id)??[]).length}</td><td><span className={`daily-log-status ${log.status}`}>{labels[log.status]??log.status}</span><small>{Number(log.completion_percent).toFixed(0)}%</small></td><td>{log.responsible_name}</td><td>{dateBR(log.approved_at)}</td></tr>})}{!filtered.length?<tr><td colSpan={10} className="budget-empty-state">Nenhum diário encontrado.</td></tr>:null}</tbody></table></div></section></>;
}

export function DailyLogIndicators({logs,weatherMap,workforceMap,servicesMap,occurrencesMap,photosMap}:{logs:DailyLogViewRecord[];weatherMap:Map<string,(WeatherRow&WithLog)[]>;workforceMap:Map<string,(WorkforceRow&WithLog)[]>;servicesMap:Map<string,(ServiceRow&WithLog)[]>;occurrencesMap:Map<string,(OccurrenceRow&WithLog)[]>;photosMap:Map<string,PhotoRecord[]>}) {
  const valid=logs.filter(x=>x.status!=="cancelled"&&x.is_current),approved=valid.filter(x=>["approved","approved_with_reservations"].includes(x.status)).length,rain=valid.filter(x=>(weatherMap.get(x.id)??[]).some(w=>["rain","storm"].includes(w.condition))).length,stopped=valid.filter(x=>(weatherMap.get(x.id)??[]).some(w=>Number(w.stopped_hours)>0)||(occurrencesMap.get(x.id)??[]).some(o=>o.occurrence_type==="stoppage")).length,svc=new Map<string,number>(),occ=new Map<string,number>();valid.flatMap(x=>servicesMap.get(x.id)??[]).forEach(x=>svc.set(x.service_name,(svc.get(x.service_name)??0)+1));valid.flatMap(x=>occurrencesMap.get(x.id)??[]).forEach(x=>occ.set(x.occurrence_type,(occ.get(x.occurrence_type)??0)+1));
  const average=valid.length?valid.reduce((s,x)=>s+(workforceMap.get(x.id)??[]).reduce((a,b)=>a+Number(b.worker_count||0),0),0)/valid.length:0;
  return <section className="daily-log-indicator-grid"><article className="wide"><span>Taxa de aprovação</span><strong>{valid.length?number(approved/valid.length*100,1):"0"}%</strong><small>{approved} de {valid.length} diários atuais</small></article><article><span>Dias com chuva</span><strong>{rain}</strong><small>chuva ou temporal</small></article><article><span>Dias paralisados</span><strong>{stopped}</strong><small>clima ou ocorrência</small></article><article><span>Fotos registradas</span><strong>{valid.reduce((s,x)=>s+(photosMap.get(x.id)??[]).length,0)}</strong><small>evidências de campo</small></article><article><span>Média de trabalhadores</span><strong>{number(average,1)}</strong><small>por dia registrado</small></article><article className="half"><h3>Serviços mais registrados</h3>{[...svc.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([n,c])=><div key={n}><span>{n}</span><strong>{c} dia(s)</strong></div>)}</article><article className="half"><h3>Ocorrências por tipo</h3>{[...occ.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([n,c])=><div key={n}><span>{n}</span><strong>{c}</strong></div>)}</article></section>;
}

export function DailyLogSettings({settings,canSettings,month}:{settings:DailyLogSettingsRecord;canSettings:boolean;month:string}) {
  if(!canSettings)return <div className="daily-log-settings-card"><h2>Configurações restritas</h2><p>Somente usuários autorizados podem alterar as regras do Diário de Obras.</p></div>;
  return <div className="daily-log-settings-grid"><form action={saveDailyLogSettings} className="daily-log-settings-card"><div className="budget-section-head"><div><span>Regras da obra</span><h2>Configurações</h2></div></div><label>Dias previstos<div className="daily-log-workdays">{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map((x,i)=><label key={x}><input name="workdays" type="checkbox" value={i} defaultChecked={settings.workdays.includes(i)}/>{x}</label>)}</div></label><div className="daily-log-settings-fields"><label>Turno padrão<select name="default_shift" defaultValue={settings.default_shift}><option value="day">Diurno</option><option value="night">Noturno</option></select></label><label>Fim do expediente<input name="day_end" type="time" defaultValue={settings.day_end.slice(0,5)}/></label><label>Fotos obrigatórias<input name="required_photo_count" type="number" min="0" max="20" defaultValue={settings.required_photo_count}/></label><label>Dias retroativos<input name="retroactive_days" type="number" min="0" max="3650" defaultValue={settings.retroactive_days}/></label></div><label className="daily-log-check"><input name="auto_create" type="checkbox" defaultChecked={settings.auto_create}/> Criar pendências automaticamente</label><label className="daily-log-check"><input name="allow_complementary" type="checkbox" defaultChecked={settings.allow_complementary}/> Permitir diário complementar</label><button className="elos-button" type="submit">Salvar configurações</button></form><form action={generatePendingDailyLogs} className="daily-log-settings-card"><input type="hidden" name="month" value={month}/><span>Criação automática</span><h2>Gerar pendências de {month}</h2><p>Cria somente os diários principais ainda inexistentes. Nenhum registro é sobrescrito.</p><button type="submit">Gerar diários pendentes</button></form></div>;
}
