import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { fetchAllRows } from "@/lib/supabase-pagination";
import { requireCompanyPermission } from "@/lib/workspace";
import { approveMaterialReceipt, cancelMaterialReceipt, rejectMaterialReceipt, submitMaterialReceipt, uploadMaterialReceiptDocuments } from "./actions";
import { MaterialReceiptDialog, type OrderItemOption, type OrderOption, type ReceiptItemRecord, type ReceiptRecord } from "./receipt-client";
import "../../procurement-material-receipts.css";

type Project={id:string;code:string|null;name:string};
type Order={id:string;order_number:string;supplier_id:string;status:string;expected_delivery_date:string|null;total_amount:number;received_amount:number;issue_date:string|null};
type Supplier={id:string;legal_name:string;trade_name:string|null;tax_id:string|null};
type OrderItem=OrderItemOption&{order_id:string;total_amount:number};
type Receipt=ReceiptRecord&{company_id:string;project_id:string;supplier_id:string;sequence_no:number;receipt_number:string;receiver_name:string|null;approved_at:string|null;rejection_reason:string|null;cancellation_reason:string|null;created_at:string};
type ReceiptItem=ReceiptItemRecord&{id:string;receipt_id:string;input_code:string;input_name:string;unit_snapshot:string;cost_center_name:string;ordered_quantity:number;previously_accepted_quantity:number;unit_cost:number;accepted_amount:number};
type Discrepancy={id:string;receipt_id:string;receipt_item_id:string|null;discrepancy_type:string;description:string;severity:string;status:string;due_date:string|null};
type Document={id:string;receipt_id:string;document_type:string;storage_path:string;file_name:string;caption:string|null;uploaded_at:string};
const statusLabels:Record<string,string>={draft:"Em elaboração",submitted:"Aguardando aprovação",approved:"Aprovado",rejected:"Devolvido",cancelled:"Cancelado"};
const discrepancyLabels:Record<string,string>={quantity:"Quantidade",damage:"Avaria",specification:"Especificação",invoice:"Nota fiscal",documentation:"Documentação",delivery_date:"Prazo",other:"Outra"};
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value||0));
const qty=(value:number)=>new Intl.NumberFormat("pt-BR",{maximumFractionDigits:4}).format(Number(value||0));
const dateBR=(value?:string|null)=>value?new Intl.DateTimeFormat("pt-BR",{timeZone:"UTC"}).format(new Date(`${value.slice(0,10)}T12:00:00Z`)):"—";
const supplierName=(supplier?:Supplier|null)=>supplier?supplier.trade_name||supplier.legal_name:"Fornecedor não localizado";

export default async function MaterialReceiptsPage({searchParams}:{searchParams:Promise<{receipt?:string;q?:string;status?:string;new?:string;edit?:string;success?:string;error?:string}>}){
 const params=await searchParams;const{company,companyId,projectId,roleKey,supabase}=await requireCompanyPermission("procurement.receipts.view");const privileged=roleKey==="owner"||roleKey==="admin";const permission=(key:string)=>privileged?Promise.resolve({data:true,error:null}):supabase.rpc("has_company_permission",{target_company_id:companyId,target_permission:key});
 const [projectResult,ordersResult,orderItemsResult,suppliersResult,receiptsResult,receiptItemsResult,discrepanciesResult,documentsResult,manageResult,submitResult,approveResult,cancelResult]=await Promise.all([
  projectId?supabase.from("projects").select("id,code,name").eq("id",projectId).eq("company_id",companyId).maybeSingle():Promise.resolve({data:null,error:null}),
  projectId?fetchAllRows<Order>(async(from,to)=>{const{data,error}=await supabase.from("procurement_purchase_orders").select("id,order_number,supplier_id,status,expected_delivery_date,total_amount,received_amount,issue_date").eq("company_id",companyId).eq("project_id",projectId).in("status",["issued","confirmed","partially_received","received","closed"]).order("created_at",{ascending:false}).range(from,to);return{data:(data??[])as Order[],error};}):Promise.resolve({data:[]as Order[],error:null}),
  projectId?fetchAllRows<OrderItem>(async(from,to)=>{const{data,error}=await supabase.from("procurement_purchase_order_items").select("id,order_id,input_code,input_name,unit_snapshot,cost_center_code,cost_center_name,ordered_quantity,accepted_quantity,rejected_quantity,delivered_unit_cost,brand,manufacturer,total_amount").eq("company_id",companyId).eq("project_id",projectId).order("sort_order").range(from,to);return{data:(data??[])as OrderItem[],error};}):Promise.resolve({data:[]as OrderItem[],error:null}),
  fetchAllRows<Supplier>(async(from,to)=>{const{data,error}=await supabase.from("suppliers").select("id,legal_name,trade_name,tax_id").eq("company_id",companyId).order("legal_name").range(from,to);return{data:(data??[])as Supplier[],error};}),
  projectId?fetchAllRows<Receipt>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_receipts").select("id,company_id,project_id,order_id,supplier_id,sequence_no,receipt_number,status,receipt_date,arrival_time,invoice_number,invoice_series,invoice_access_key,invoice_date,invoice_amount,carrier_name,vehicle_plate,driver_name,delivery_document,warehouse_location,general_condition,notes,receiver_name,approved_at,rejection_reason,cancellation_reason,created_at").eq("company_id",companyId).eq("project_id",projectId).order("created_at",{ascending:false}).range(from,to);return{data:(data??[])as Receipt[],error};}):Promise.resolve({data:[]as Receipt[],error:null}),
  projectId?fetchAllRows<ReceiptItem>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_receipt_items").select("id,receipt_id,order_item_id,input_code,input_name,unit_snapshot,cost_center_name,ordered_quantity,previously_accepted_quantity,delivered_quantity,accepted_quantity,rejected_quantity,unit_cost,accepted_amount,batch_number,expiration_date,condition,rejection_reason,destination_location,notes").eq("company_id",companyId).eq("project_id",projectId).order("sort_order").range(from,to);return{data:(data??[])as ReceiptItem[],error};}):Promise.resolve({data:[]as ReceiptItem[],error:null}),
  projectId?fetchAllRows<Discrepancy>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_receipt_discrepancies").select("id,receipt_id,receipt_item_id,discrepancy_type,description,severity,status,due_date").eq("company_id",companyId).eq("project_id",projectId).order("created_at",{ascending:false}).range(from,to);return{data:(data??[])as Discrepancy[],error};}):Promise.resolve({data:[]as Discrepancy[],error:null}),
  projectId?fetchAllRows<Document>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_receipt_documents").select("id,receipt_id,document_type,storage_path,file_name,caption,uploaded_at").eq("company_id",companyId).eq("project_id",projectId).order("uploaded_at",{ascending:false}).range(from,to);return{data:(data??[])as Document[],error};}):Promise.resolve({data:[]as Document[],error:null}),
  permission("procurement.receipts.manage"),permission("procurement.receipts.submit"),permission("procurement.receipts.approve"),permission("procurement.receipts.cancel")]);
 const project=projectResult.data as Project|null;const supplierMap=new Map(suppliersResult.data.map(s=>[s.id,s]));const orderMap=new Map(ordersResult.data.map(o=>[o.id,o]));const orderOptions:OrderOption[]=ordersResult.data.filter(o=>["issued","confirmed","partially_received"].includes(o.status)).map(o=>({...o,supplier_name:supplierName(supplierMap.get(o.supplier_id))}));
 const itemMap=new Map<string,ReceiptItem[]>();receiptItemsResult.data.forEach(item=>itemMap.set(item.receipt_id,[...(itemMap.get(item.receipt_id)??[]),item]));const discrepancyMap=new Map<string,Discrepancy[]>();discrepanciesResult.data.forEach(item=>discrepancyMap.set(item.receipt_id,[...(discrepancyMap.get(item.receipt_id)??[]),item]));const documentMap=new Map<string,Document[]>();documentsResult.data.forEach(item=>documentMap.set(item.receipt_id,[...(documentMap.get(item.receipt_id)??[]),item]));
 const selected=params.receipt?receiptsResult.data.find(r=>r.id===params.receipt)??null:null;const selectedItems=selected?itemMap.get(selected.id)??[]:[];const selectedDiscrepancies=selected?discrepancyMap.get(selected.id)??[]:[];const selectedDocuments=selected?documentMap.get(selected.id)??[]:[];let signedDocs:(Document&{signed_url:string|null})[]=[];if(selectedDocuments.length){const signed=await supabase.storage.from("material-receipt-documents").createSignedUrls(selectedDocuments.map(d=>d.storage_path),3600);const urls=new Map((signed.data??[]).map(row=>[row.path,row.signedUrl]));signedDocs=selectedDocuments.map(d=>({...d,signed_url:urls.get(d.storage_path)??null}));}
 const canManage=manageResult.data===true||privileged,canSubmit=submitResult.data===true||privileged,canApprove=approveResult.data===true||privileged,canCancel=cancelResult.data===true||privileged;const query=(params.q??"").toLowerCase();const filtered=receiptsResult.data.filter(r=>!params.status||r.status===params.status).filter(r=>!query||[r.receipt_number,r.invoice_number??"",orderMap.get(r.order_id)?.order_number??"",supplierName(supplierMap.get(r.supplier_id)),...(itemMap.get(r.id)??[]).flatMap(i=>[i.input_code,i.input_name,i.cost_center_name])].join(" ").toLowerCase().includes(query));
 const approved=receiptsResult.data.filter(r=>r.status==="approved");const acceptedTotal=approved.reduce((sum,r)=>sum+(itemMap.get(r.id)??[]).reduce((s,i)=>s+Number(i.accepted_amount),0),0);const rejectedQty=approved.reduce((sum,r)=>sum+(itemMap.get(r.id)??[]).reduce((s,i)=>s+Number(i.rejected_quantity),0),0);const openDiscrepancies=discrepanciesResult.data.filter(d=>!["resolved","waived"].includes(d.status)).length;const structureError=receiptsResult.error||receiptItemsResult.error||discrepanciesResult.error;
 return <AppShell activeGroup="procurement" activeItem="material-receipts" eyebrow="Suprimentos · Entregas" title="Recebimento de Materiais" description={`${company.name} · ${project?`${project.code?`${project.code} · `:""}${project.name}`:"Selecione uma obra"} · conferência física, fiscal e qualitativa dos pedidos.`} actions={canManage&&orderOptions.length?<MaterialReceiptDialog orders={orderOptions} orderItems={orderItemsResult.data} autoOpen={params.new==="1"}/>:undefined}>
  {params.success?<div className="auth-message success workspace-message">{params.success}</div>:null}{params.error?<div className="auth-message error workspace-message">{params.error}</div>:null}{structureError?<div className="auth-message error workspace-message">Execute a migration <strong>20260729_0043_procurement_material_receipts.sql</strong>.</div>:null}
  {!projectId?<div className="receipt-empty">Selecione uma obra no topo.</div>:selected?<>
   <div className="receipt-back"><Link href="/suprimentos/recebimento-materiais">← Voltar aos recebimentos</Link><span>{selected.receipt_number}</span></div>
   <section className="receipt-hero"><div><span>Recebimento de materiais</span><h2>{selected.receipt_number} · {orderMap.get(selected.order_id)?.order_number}</h2><p>{supplierName(supplierMap.get(selected.supplier_id))} · {dateBR(selected.receipt_date)}</p></div><div><span className={`receipt-status ${selected.status}`}>{statusLabels[selected.status]}</span>{canManage&&["draft","rejected"].includes(selected.status)?<MaterialReceiptDialog orders={orderOptions.some(o=>o.id===selected.order_id)?orderOptions:[...orderOptions,{id:selected.order_id,order_number:orderMap.get(selected.order_id)?.order_number??"",supplier_id:selected.supplier_id,supplier_name:supplierName(supplierMap.get(selected.supplier_id)),status:orderMap.get(selected.order_id)?.status??"",expected_delivery_date:orderMap.get(selected.order_id)?.expected_delivery_date??null}]} orderItems={orderItemsResult.data} receipt={selected} items={selectedItems} autoOpen={params.edit==="1"} label="Editar"/>:null}</div></section>
   <section className="receipt-kpis"><article><span>Itens entregues</span><strong>{selectedItems.length}</strong></article><article><span>Valor aceito</span><strong>{money(selectedItems.reduce((s,i)=>s+Number(i.accepted_amount),0))}</strong></article><article><span>Quantidade rejeitada</span><strong>{qty(selectedItems.reduce((s,i)=>s+Number(i.rejected_quantity),0))}</strong></article><article><span>Divergências</span><strong>{selectedDiscrepancies.length}</strong></article></section>
   <section className="receipt-detail-grid"><article className="receipt-card"><h3>Dados da entrega</h3><dl><div><dt>Nota fiscal</dt><dd>{selected.invoice_number||"—"}</dd></div><div><dt>Valor NF</dt><dd>{selected.invoice_amount?money(selected.invoice_amount):"—"}</dd></div><div><dt>Transportadora</dt><dd>{selected.carrier_name||"—"}</dd></div><div><dt>Veículo</dt><dd>{selected.vehicle_plate||"—"}</dd></div><div><dt>Motorista</dt><dd>{selected.driver_name||"—"}</dd></div><div><dt>Destino</dt><dd>{selected.warehouse_location||"—"}</dd></div></dl>{selected.notes?<p>{selected.notes}</p>:null}</article><article className="receipt-card"><h3>Documentos</h3>{signedDocs.map(doc=><div className="receipt-document" key={doc.id}><strong>{doc.file_name}</strong>{doc.signed_url?<a href={doc.signed_url} target="_blank" rel="noreferrer">Abrir</a>:null}</div>)}{canManage?<form action={uploadMaterialReceiptDocuments} className="receipt-upload" encType="multipart/form-data"><input type="hidden" name="receipt_id" value={selected.id}/><select name="document_type"><option value="invoice">Nota fiscal</option><option value="delivery_document">Romaneio</option><option value="evidence">Evidência</option><option value="damage">Avaria</option><option value="other">Outro</option></select><input name="documents" type="file" multiple accept="application/pdf,image/*,.xml"/><input name="caption" placeholder="Legenda"/><button>Enviar</button></form>:null}</article></section>
   <section className="receipt-card"><h3>Materiais conferidos</h3><div className="registry-table-wrap"><table className="registry-table"><thead><tr><th>Material</th><th>Centro de custo</th><th>Entregue</th><th>Aceito</th><th>Rejeitado</th><th>Condição</th><th>Destino</th><th>Valor aceito</th></tr></thead><tbody>{selectedItems.map(i=><tr key={i.id}><td><strong>{i.input_code}</strong><span>{i.input_name}</span></td><td>{i.cost_center_name}</td><td>{qty(i.delivered_quantity)} {i.unit_snapshot}</td><td>{qty(i.accepted_quantity)}</td><td className={Number(i.rejected_quantity)>0?"negative":""}>{qty(i.rejected_quantity)}</td><td>{i.condition}</td><td>{i.destination_location||"—"}</td><td>{money(i.accepted_amount)}</td></tr>)}</tbody></table></div></section>
   {selectedDiscrepancies.length?<section className="receipt-card"><h3>Divergências abertas</h3>{selectedDiscrepancies.map(d=><div className="receipt-discrepancy" key={d.id}><span>{discrepancyLabels[d.discrepancy_type]} · {d.severity}</span><strong>{d.description}</strong><small>{d.status} · prazo {dateBR(d.due_date)}</small></div>)}</section>:null}
   <section className="receipt-workflow"><div><h3>Ações</h3><p>A aprovação atualiza o saldo aceito do pedido e abre divergências para itens rejeitados.</p></div><div>{canSubmit&&["draft","rejected"].includes(selected.status)?<form action={submitMaterialReceipt}><input type="hidden" name="receipt_id" value={selected.id}/><button className="primary">Enviar para aprovação</button></form>:null}{canApprove&&selected.status==="submitted"?<><form action={approveMaterialReceipt}><input type="hidden" name="receipt_id" value={selected.id}/><input name="notes" placeholder="Observações"/><button className="primary">Aprovar</button></form><form action={rejectMaterialReceipt}><input type="hidden" name="receipt_id" value={selected.id}/><input name="reason" required placeholder="Motivo da devolução"/><button>Devolver</button></form></>:null}{canCancel&&["draft","rejected"].includes(selected.status)?<form action={cancelMaterialReceipt}><input type="hidden" name="receipt_id" value={selected.id}/><input name="reason" required placeholder="Motivo do cancelamento"/><button className="danger">Cancelar</button></form>:null}</div></section>
  </>:<><section className="receipt-kpis"><article><span>Recebimentos</span><strong>{receiptsResult.data.length}</strong></article><article><span>Aguardando aprovação</span><strong>{receiptsResult.data.filter(r=>r.status==="submitted").length}</strong></article><article><span>Valor aceito</span><strong>{money(acceptedTotal)}</strong></article><article><span>Quantidade rejeitada</span><strong>{qty(rejectedQty)}</strong></article><article><span>Divergências abertas</span><strong>{openDiscrepancies}</strong></article></section><section className="receipt-toolbar"><form><input name="q" defaultValue={params.q??""} placeholder="Buscar recebimento, pedido, NF ou material"/><select name="status" defaultValue={params.status??""}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button>Filtrar</button><Link href="/suprimentos/recebimento-materiais">Limpar</Link></form></section><section className="receipt-card"><div className="registry-table-wrap"><table className="registry-table"><thead><tr><th>Recebimento</th><th>Pedido</th><th>Fornecedor</th><th>Data</th><th>Nota fiscal</th><th>Itens</th><th>Aceito</th><th>Rejeitado</th><th>Status</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><Link href={`?receipt=${r.id}`}><strong>{r.receipt_number}</strong></Link></td><td>{orderMap.get(r.order_id)?.order_number}</td><td>{supplierName(supplierMap.get(r.supplier_id))}</td><td>{dateBR(r.receipt_date)}</td><td>{r.invoice_number||"—"}</td><td>{(itemMap.get(r.id)??[]).length}</td><td>{money((itemMap.get(r.id)??[]).reduce((s,i)=>s+Number(i.accepted_amount),0))}</td><td>{qty((itemMap.get(r.id)??[]).reduce((s,i)=>s+Number(i.rejected_quantity),0))}</td><td><span className={`receipt-status ${r.status}`}>{statusLabels[r.status]}</span></td></tr>)}{!filtered.length?<tr><td colSpan={9}>Nenhum recebimento encontrado.</td></tr>:null}</tbody></table></div></section></>}
 </AppShell>;
}
