import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { fetchAllRows } from "@/lib/supabase-pagination";
import { requireCompanyPermission } from "@/lib/workspace";
import {
  cancelMaterialQuotation, openMaterialQuotation, removeMaterialQuotationDocument,
  startMaterialQuotationAnalysis, uploadMaterialQuotationDocuments,
} from "./actions";
import {
  MaterialQuotationDialog, QuotationAwardForm, SupplierOfferForm,
  type EligibleRequestItem, type OfferItemRecord, type OfferRecord, type QuotationItemRecord,
  type QuotationRecord, type QuotationSupplierRecord, type SupplierOption,
} from "./quotation-client";
import "../../procurement-material-quotations.css";

type Project = { id:string; code:string|null; name:string };
type MaterialRequest = { id:string; request_number:string; status:string; needed_date:string };
type RequestItem = { id:string; request_id:string; input_code:string; input_name:string; unit_snapshot:string; category_snapshot:string; cost_center_code:string; cost_center_name:string; requested_quantity:number; ordered_quantity:number; notes:string|null };
type Quotation = QuotationRecord & { company_id:string; project_id:string; sequence_no:number; quotation_number:string; invited_suppliers_count:number; responses_count:number; total_awarded_amount:number; opened_at:string|null; analysis_started_at:string|null; approved_at:string|null; approval_notes:string|null; cancellation_reason:string|null; created_at:string };
type Award = { id:string; quotation_id:string; quotation_item_id:string; supplier_id:string; offer_item_id:string; awarded_quantity:number; awarded_unit_cost:number; awarded_total_cost:number; justification:string|null; approved_at:string };
type Document = { id:string; quotation_id:string; supplier_id:string|null; document_type:string; storage_path:string; file_name:string; caption:string|null; uploaded_at:string };
type SignedDocument = Document & { signed_url:string|null };

const statusLabels:Record<string,string>={draft:"Em elaboração",collecting:"Recebendo propostas",analysis:"Em análise",approved:"Aprovada",cancelled:"Cancelada"};
const documentLabels:Record<string,string>={request:"Solicitação",proposal:"Proposta",technical:"Documento técnico",approval:"Aprovação",other:"Outro"};
function money(value:number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value||0));}
function quantity(value:number,digits=4){return new Intl.NumberFormat("pt-BR",{maximumFractionDigits:digits}).format(Number(value||0));}
function dateBR(value?:string|null){return value?new Intl.DateTimeFormat("pt-BR",{timeZone:"UTC"}).format(new Date(`${value.slice(0,10)}T12:00:00Z`)):"—";}
function supplierName(supplier?:SupplierOption|null){return supplier?supplier.trade_name||supplier.legal_name:"Fornecedor não localizado";}

export default async function MaterialQuotationsPage({searchParams}:{searchParams:Promise<{quotation?:string;q?:string;status?:string;new?:string;edit?:string;success?:string;error?:string}>}){
  const params=await searchParams;
  const {supabase,company,companyId,projectId,roleKey}=await requireCompanyPermission("procurement.quotations.view");
  const privileged=roleKey==="owner"||roleKey==="admin";
  const permission=(key:string)=>privileged?Promise.resolve({data:true,error:null}):supabase.rpc("has_company_permission",{target_company_id:companyId,target_permission:key});

  const [projectResult,requestsResult,requestItemsResult,quotationsResult,itemsResult,invitesResult,offersResult,offerItemsResult,awardsResult,documentsResult,suppliersResult,manageResult,approveResult,cancelResult]=await Promise.all([
    projectId?supabase.from("projects").select("id,code,name").eq("id",projectId).eq("company_id",companyId).maybeSingle():Promise.resolve({data:null,error:null}),
    projectId?fetchAllRows<MaterialRequest>(async(from,to)=>{const{data,error}=await supabase.from("execution_material_requests").select("id,request_number,status,needed_date").eq("company_id",companyId).eq("project_id",projectId).in("status",["approved","partially_ordered"]).order("needed_date").range(from,to);return{data:(data??[])as MaterialRequest[],error};}):Promise.resolve({data:[]as MaterialRequest[],error:null}),
    projectId?fetchAllRows<RequestItem>(async(from,to)=>{const{data,error}=await supabase.from("execution_material_request_items").select("id,request_id,input_code,input_name,unit_snapshot,category_snapshot,cost_center_code,cost_center_name,requested_quantity,ordered_quantity,notes").eq("company_id",companyId).eq("project_id",projectId).order("input_code").range(from,to);return{data:(data??[])as RequestItem[],error};}):Promise.resolve({data:[]as RequestItem[],error:null}),
    projectId?fetchAllRows<Quotation>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_quotations").select("id,company_id,project_id,sequence_no,quotation_number,title,status,award_mode,response_deadline,desired_delivery_date,payment_terms,delivery_address,notes,invited_suppliers_count,responses_count,total_awarded_amount,opened_at,analysis_started_at,approved_at,approval_notes,cancellation_reason,created_at").eq("company_id",companyId).eq("project_id",projectId).order("created_at",{ascending:false}).range(from,to);return{data:(data??[])as Quotation[],error};}):Promise.resolve({data:[]as Quotation[],error:null}),
    projectId?fetchAllRows<QuotationItemRecord & {quotation_id:string}>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_quotation_items").select("id,quotation_id,request_item_id,request_number,input_code,input_name,unit_snapshot,cost_center_code,cost_center_name,requested_quantity,previously_ordered_quantity,quantity_to_quote,best_delivered_unit_cost,best_total_cost,notes").eq("company_id",companyId).eq("project_id",projectId).order("sort_order").range(from,to);return{data:(data??[])as(QuotationItemRecord&{quotation_id:string})[],error};}):Promise.resolve({data:[]as(QuotationItemRecord&{quotation_id:string})[],error:null}),
    projectId?fetchAllRows<QuotationSupplierRecord & {quotation_id:string}>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_quotation_suppliers").select("id,quotation_id,supplier_id,supplier_name,contact_name,contact_email,contact_phone,status,notes").eq("company_id",companyId).eq("project_id",projectId).order("supplier_name").range(from,to);return{data:(data??[])as(QuotationSupplierRecord&{quotation_id:string})[],error};}):Promise.resolve({data:[]as(QuotationSupplierRecord&{quotation_id:string})[],error:null}),
    projectId?fetchAllRows<OfferRecord & {quotation_id:string}>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_quotation_offers").select("id,quotation_id,supplier_id,proposal_number,proposal_date,validity_date,payment_terms,delivery_days,freight_terms,warranty_terms,notes,total_delivered_cost").eq("company_id",companyId).eq("project_id",projectId).order("received_at").range(from,to);return{data:(data??[])as(OfferRecord&{quotation_id:string})[],error};}):Promise.resolve({data:[]as(OfferRecord&{quotation_id:string})[],error:null}),
    projectId?fetchAllRows<OfferItemRecord>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_quotation_offer_items").select("id,offer_id,supplier_id,quotation_item_id,quantity_offered,unit_price,discount_percent,tax_percent,freight_amount,other_cost_amount,delivered_unit_cost,total_delivered_cost,brand,manufacturer,delivery_days,meets_specification,technical_notes,is_selected").eq("company_id",companyId).eq("project_id",projectId).order("created_at").range(from,to);return{data:(data??[])as OfferItemRecord[],error};}):Promise.resolve({data:[]as OfferItemRecord[],error:null}),
    projectId?fetchAllRows<Award>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_quotation_awards").select("id,quotation_id,quotation_item_id,supplier_id,offer_item_id,awarded_quantity,awarded_unit_cost,awarded_total_cost,justification,approved_at").eq("company_id",companyId).eq("project_id",projectId).order("approved_at").range(from,to);return{data:(data??[])as Award[],error};}):Promise.resolve({data:[]as Award[],error:null}),
    projectId?fetchAllRows<Document>(async(from,to)=>{const{data,error}=await supabase.from("procurement_material_quotation_documents").select("id,quotation_id,supplier_id,document_type,storage_path,file_name,caption,uploaded_at").eq("company_id",companyId).eq("project_id",projectId).order("uploaded_at",{ascending:false}).range(from,to);return{data:(data??[])as Document[],error};}):Promise.resolve({data:[]as Document[],error:null}),
    fetchAllRows<SupplierOption>(async(from,to)=>{const{data,error}=await supabase.from("suppliers").select("id,legal_name,trade_name,tax_id").eq("company_id",companyId).eq("status","active").order("legal_name").range(from,to);return{data:(data??[])as SupplierOption[],error};}),
    permission("procurement.quotations.manage"),permission("procurement.quotations.approve"),permission("procurement.quotations.cancel"),
  ]);

  const project=projectResult.data as Project|null;
  const requestMap=new Map(requestsResult.data.map((request)=>[request.id,request]));
  const eligibleItems:EligibleRequestItem[]=requestItemsResult.data.filter((item)=>requestMap.has(item.request_id)&&Number(item.ordered_quantity)<Number(item.requested_quantity)).map((item)=>({
    ...item,request_number:requestMap.get(item.request_id)?.request_number??"",needed_date:requestMap.get(item.request_id)?.needed_date??"",
  }));
  const quotations=quotationsResult.data;
  const itemMap=new Map<string,(QuotationItemRecord&{quotation_id:string})[]>();itemsResult.data.forEach((item)=>itemMap.set(item.quotation_id,[...(itemMap.get(item.quotation_id)??[]),item]));
  const inviteMap=new Map<string,(QuotationSupplierRecord&{quotation_id:string})[]>();invitesResult.data.forEach((item)=>inviteMap.set(item.quotation_id,[...(inviteMap.get(item.quotation_id)??[]),item]));
  const offerMap=new Map<string,(OfferRecord&{quotation_id:string})[]>();offersResult.data.forEach((item)=>offerMap.set(item.quotation_id,[...(offerMap.get(item.quotation_id)??[]),item]));
  const offerItemMap=new Map<string,OfferItemRecord[]>();offerItemsResult.data.forEach((item)=>offerItemMap.set(item.offer_id,[...(offerItemMap.get(item.offer_id)??[]),item]));
  const awardMap=new Map<string,Award[]>();awardsResult.data.forEach((item)=>awardMap.set(item.quotation_id,[...(awardMap.get(item.quotation_id)??[]),item]));
  const documentMap=new Map<string,Document[]>();documentsResult.data.forEach((item)=>documentMap.set(item.quotation_id,[...(documentMap.get(item.quotation_id)??[]),item]));
  const supplierMap=new Map(suppliersResult.data.map((supplier)=>[supplier.id,supplier]));
  const selected=params.quotation?quotations.find((quotation)=>quotation.id===params.quotation)??null:null;
  const selectedItems=selected?itemMap.get(selected.id)??[]:[];
  const selectedInvites=selected?inviteMap.get(selected.id)??[]:[];
  const selectedOffers=selected?offerMap.get(selected.id)??[]:[];
  const selectedOfferItems=selectedOffers.flatMap((offer)=>offerItemMap.get(offer.id)??[]);
  const selectedAwards=selected?awardMap.get(selected.id)??[]:[];
  const selectedDocuments=selected?documentMap.get(selected.id)??[]:[];
  let signedDocuments:SignedDocument[]=[];
  if(selectedDocuments.length){const signed=await supabase.storage.from("material-quotation-documents").createSignedUrls(selectedDocuments.map((document)=>document.storage_path),3600);const urlMap=new Map((signed.data??[]).map((item)=>[item.path,item.signedUrl]));signedDocuments=selectedDocuments.map((document)=>({...document,signed_url:urlMap.get(document.storage_path)??null}));}

  const canManage=manageResult.data===true||privileged;const canApprove=approveResult.data===true||privileged;const canCancel=cancelResult.data===true||privileged;
  const structureError=quotationsResult.error||itemsResult.error||invitesResult.error||offersResult.error||offerItemsResult.error;
  const query=(params.q??"").trim().toLocaleLowerCase("pt-BR");
  const filtered=quotations.filter((quotation)=>!params.status||quotation.status===params.status).filter((quotation)=>!query||[quotation.quotation_number,quotation.title,...(inviteMap.get(quotation.id)??[]).map((invite)=>invite.supplier_name),...(itemMap.get(quotation.id)??[]).flatMap((item)=>[item.input_code,item.input_name,item.cost_center_name])].join(" ").toLocaleLowerCase("pt-BR").includes(query));
  const openQuotes=quotations.filter((quotation)=>["draft","collecting","analysis"].includes(quotation.status));
  const approvedTotal=quotations.filter((quotation)=>quotation.status==="approved").reduce((sum,quotation)=>sum+Number(quotation.total_awarded_amount),0);
  const averageCompetition=quotations.length?quotations.reduce((sum,quotation)=>sum+Number(quotation.responses_count),0)/quotations.length:0;
  const context=project?`${project.code?`${project.code} · `:""}${project.name}`:"Selecione uma obra";

  return <AppShell activeGroup="procurement" activeItem="material-quotations" eyebrow="Suprimentos · Compras" title="Orçamentos de Materiais"
    description={`${company.name} · ${context} · solicitações aprovadas, propostas, custo posto na obra e fornecedores vencedores.`}
    actions={canManage&&projectId&&eligibleItems.length?<MaterialQuotationDialog eligibleItems={eligibleItems} suppliers={suppliersResult.data} autoOpen={params.new==="1"}/>:undefined}>
    {params.success?<div className="auth-message success workspace-message">{params.success}</div>:null}
    {params.error?<div className="auth-message error workspace-message">{params.error}</div>:null}
    {structureError?<div className="auth-message error workspace-message">A estrutura de cotações ainda não está instalada. Execute a migration <strong>20260729_0041_procurement_material_quotations.sql</strong>.</div>:null}
    {!projectId?<div className="quotation-empty">Selecione uma obra no topo.</div>:null}
    {projectId&&selected?<QuotationDetail quotation={selected} items={selectedItems} invites={selectedInvites} offers={selectedOffers} offerItems={selectedOfferItems} awards={selectedAwards} documents={signedDocuments} supplierMap={supplierMap} eligibleItems={eligibleItems} allSuppliers={suppliersResult.data} canManage={canManage} canApprove={canApprove} canCancel={canCancel} autoEdit={params.edit==="1"}/>:projectId?<>
      <section className="quotation-kpis"><article><span>Itens aguardando cotação</span><strong>{eligibleItems.length}</strong><small>saldo das solicitações aprovadas</small></article><article><span>Cotações abertas</span><strong>{openQuotes.length}</strong><small>elaboração, coleta ou análise</small></article><article><span>Respostas por cotação</span><strong>{quantity(averageCompetition,1)}</strong><small>média de concorrência</small></article><article><span>Total aprovado</span><strong>{money(approvedTotal)}</strong><small>aguarda conversão em pedidos</small></article></section>
      <section className="quotation-flow">{[["1","Solicitação","Demanda aprovada da obra"],["2","Convite","Fornecedores participantes"],["3","Propostas","Preço, prazo, frete e impostos"],["4","Mapa","Comparação do custo posto"],["5","Aprovação","Vencedores seguem para pedido"]].map(([number,title,caption])=><div key={number}><i>{number}</i><strong>{title}</strong><span>{caption}</span></div>)}</section>
      <section className="quotation-toolbar"><form method="get"><input name="q" defaultValue={params.q??""} placeholder="Buscar cotação, material, serviço ou fornecedor"/><select name="status" defaultValue={params.status??""}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button type="submit">Filtrar</button><Link href="/suprimentos/orcamentos-materiais">Limpar</Link></form></section>
      <section className="quotation-list-card"><div className="budget-section-head"><div><span>Processos de compra</span><h2>Mapa das cotações da obra</h2></div><p>{filtered.length} cotação(ões)</p></div><div className="registry-table-wrap"><table className="registry-table quotation-table"><thead><tr><th>Cotação</th><th>Itens</th><th>Fornecedores</th><th>Respostas</th><th>Prazo</th><th>Fechamento</th><th>Valor aprovado</th><th>Status</th></tr></thead><tbody>{filtered.map((quotation)=><tr key={quotation.id}><td><Link href={`?quotation=${quotation.id}`}><strong>{quotation.quotation_number}</strong><span>{quotation.title}</span></Link></td><td><strong>{(itemMap.get(quotation.id)??[]).length}</strong><span>{(itemMap.get(quotation.id)??[]).slice(0,2).map((item)=>item.input_name).join(" · ")}</span></td><td>{quotation.invited_suppliers_count}<span>convidado(s)</span></td><td><strong>{quotation.responses_count}</strong><span>{quotation.invited_suppliers_count?quantity(quotation.responses_count/quotation.invited_suppliers_count*100,0):"0"}% retorno</span></td><td>{dateBR(quotation.response_deadline)}<span>entrega {dateBR(quotation.desired_delivery_date)}</span></td><td>{quotation.award_mode==="lot"?"Lote único":"Por item"}</td><td><strong>{quotation.status==="approved"?money(quotation.total_awarded_amount):"—"}</strong></td><td><span className={`quotation-status ${quotation.status}`}>{statusLabels[quotation.status]}</span></td></tr>)}{!filtered.length?<tr><td colSpan={8} className="budget-empty-state">Nenhuma cotação encontrada.</td></tr>:null}</tbody></table></div></section>
    </>:null}
  </AppShell>;
}

function QuotationDetail({quotation,items,invites,offers,offerItems,awards,documents,supplierMap,eligibleItems,allSuppliers,canManage,canApprove,canCancel,autoEdit}:{quotation:Quotation;items:QuotationItemRecord[];invites:QuotationSupplierRecord[];offers:OfferRecord[];offerItems:OfferItemRecord[];awards:Award[];documents:SignedDocument[];supplierMap:Map<string,SupplierOption>;eligibleItems:EligibleRequestItem[];allSuppliers:SupplierOption[];canManage:boolean;canApprove:boolean;canCancel:boolean;autoEdit:boolean}){
  const offerBySupplier=new Map(offers.map((offer)=>[offer.supplier_id,offer]));
  const offerItemByKey=new Map(offerItems.map((item)=>[`${item.quotation_item_id}:${item.supplier_id}`,item]));
  const awardByItem=new Map(awards.map((award)=>[award.quotation_item_id,award]));
  const supplierNames=Object.fromEntries(invites.map((invite)=>[invite.supplier_id,invite.supplier_name]));
  const bestTotal=items.reduce((sum,item)=>sum+Number(item.best_total_cost??0),0);
  const awardedTotal=awards.reduce((sum,award)=>sum+Number(award.awarded_total_cost),0);
  const potentialDifference=awardedTotal&&bestTotal?awardedTotal-bestTotal:0;
  return <>
    <div className="quotation-back"><Link href="/suprimentos/orcamentos-materiais">← Voltar às cotações</Link><span>{quotation.quotation_number}</span></div>
    <section className="quotation-hero"><div><span>Processo de cotação</span><h2>{quotation.quotation_number} · {quotation.title}</h2><p>{items.length} itens · {invites.length} fornecedores · resposta até {dateBR(quotation.response_deadline)}</p></div><div><span className={`quotation-status ${quotation.status}`}>{statusLabels[quotation.status]}</span>{canManage&&quotation.status==="draft"?<MaterialQuotationDialog eligibleItems={eligibleItems} suppliers={allSuppliers} quotation={quotation} quotationItems={items} invitedSuppliers={invites} autoOpen={autoEdit} label="Editar cotação"/>:null}</div></section>
    <section className="quotation-detail-kpis"><article><span>Itens cotados</span><strong>{items.length}</strong><small>{quantity(items.reduce((sum,item)=>sum+Number(item.quantity_to_quote),0))} unidades</small></article><article><span>Fornecedores</span><strong>{invites.length}</strong><small>{quotation.responses_count} propostas recebidas</small></article><article><span>Menor composição</span><strong>{bestTotal?money(bestTotal):"—"}</strong><small>soma do menor custo por item</small></article><article><span>Total aprovado</span><strong>{quotation.status==="approved"?money(quotation.total_awarded_amount):"—"}</strong><small>{potentialDifference?`${potentialDifference>0?"+":""}${money(potentialDifference)} vs. menor composição`:"aguarda aprovação"}</small></article><article><span>Entrega desejada</span><strong>{dateBR(quotation.desired_delivery_date)}</strong><small>{quotation.payment_terms||"condição não definida"}</small></article></section>
    <section className="quotation-detail-grid"><article className="quotation-card wide"><div className="quotation-card-title"><div><span>Mapa comparativo</span><h3>Custo posto na obra</h3></div><small>desconto + impostos + frete + outros custos</small></div><div className="quotation-map-wrap"><table className="quotation-map"><thead><tr><th>Material / centro de custo</th><th>Qtd.</th>{invites.map((invite)=><th key={invite.id}>{invite.supplier_name}<span>{offerBySupplier.has(invite.supplier_id)?"proposta recebida":"sem resposta"}</span></th>)}<th>Vencedor</th></tr></thead><tbody>{items.map((item)=>{const valid=invites.map((invite)=>offerItemByKey.get(`${item.id}:${invite.supplier_id}`)).filter((row):row is OfferItemRecord=>Boolean(row&&row.meets_specification));const best=valid.sort((a,b)=>a.delivered_unit_cost-b.delivered_unit_cost)[0];const award=awardByItem.get(item.id);return <tr key={item.id}><td><strong>{item.input_code} · {item.input_name}</strong><span>{item.request_number} · {item.cost_center_code} · {item.cost_center_name}</span></td><td>{quantity(item.quantity_to_quote)} {item.unit_snapshot}</td>{invites.map((invite)=>{const row=offerItemByKey.get(`${item.id}:${invite.supplier_id}`);return <td key={invite.id} className={row?.id===best?.id?"best":""}>{row?<><strong>{money(row.delivered_unit_cost)}</strong><span>total {money(row.delivered_unit_cost*item.quantity_to_quote)}</span><small>{row.brand||"Sem marca"} · {row.delivery_days??offerBySupplier.get(invite.supplier_id)?.delivery_days??"—"} dias</small>{!row.meets_specification?<em>Não atende</em>:null}</>:"—"}</td>})}<td>{award?<><strong>{supplierNames[award.supplier_id]}</strong><span>{money(award.awarded_total_cost)}</span></>:quotation.status==="analysis"?"Em decisão":"—"}</td></tr>})}</tbody></table></div></article><article className="quotation-card"><div className="quotation-card-title"><div><span>Condições gerais</span><h3>Processo</h3></div></div><dl className="quotation-facts"><div><dt>Fechamento</dt><dd>{quotation.award_mode==="lot"?"Lote único":"Por item"}</dd></div><div><dt>Prazo de resposta</dt><dd>{dateBR(quotation.response_deadline)}</dd></div><div><dt>Entrega desejada</dt><dd>{dateBR(quotation.desired_delivery_date)}</dd></div><div><dt>Pagamento desejado</dt><dd>{quotation.payment_terms||"—"}</dd></div><div><dt>Endereço</dt><dd>{quotation.delivery_address||"—"}</dd></div></dl>{quotation.notes?<div className="quotation-note"><strong>Observações</strong><p>{quotation.notes}</p></div>:null}</article></section>

    {quotation.status==="collecting"&&canManage?<section className="quotation-card"><div className="quotation-card-title"><div><span>Recebimento</span><h3>Propostas dos fornecedores</h3></div><strong>{quotation.responses_count}/{quotation.invited_suppliers_count}</strong></div><div className="quotation-offer-list">{invites.map((invite)=>{const offer=offerBySupplier.get(invite.supplier_id);return <SupplierOfferForm key={invite.id} quotationId={quotation.id} supplier={invite} items={items} offer={offer} offerItems={offer?offerItems.filter((item)=>item.offer_id===offer.id):[]}/>})}</div></section>:null}
    {quotation.status==="analysis"&&canApprove?<section className="quotation-card"><div className="quotation-card-title"><div><span>Decisão de compra</span><h3>Selecionar fornecedores vencedores</h3></div></div><QuotationAwardForm quotationId={quotation.id} awardMode={quotation.award_mode} items={items} offerItems={offerItems} supplierNames={supplierNames}/></section>:null}
    {quotation.status==="approved"?<section className="quotation-card"><div className="quotation-card-title"><div><span>Resultado aprovado</span><h3>Itens liberados para Pedido de Compra</h3></div><strong>{money(quotation.total_awarded_amount)}</strong></div><div className="quotation-award-list">{awards.map((award)=>{const item=items.find((row)=>row.id===award.quotation_item_id);return <article key={award.id}><div><strong>{item?.input_code} · {item?.input_name}</strong><span>{quantity(award.awarded_quantity)} {item?.unit_snapshot} · {supplierNames[award.supplier_id]}</span></div><b>{money(award.awarded_total_cost)}</b>{award.justification?<small>{award.justification}</small>:null}</article>})}</div>{quotation.approval_notes?<div className="quotation-note"><strong>Observações da aprovação</strong><p>{quotation.approval_notes}</p></div>:null}</section>:null}

    <section className="quotation-detail-grid"><article className="quotation-card wide"><div className="quotation-card-title"><div><span>Propostas recebidas</span><h3>Condições comerciais</h3></div><strong>{offers.length}</strong></div>{offers.length?<div className="quotation-commercial-list">{offers.map((offer)=><article key={offer.id}><div><strong>{supplierNames[offer.supplier_id]||supplierName(supplierMap.get(offer.supplier_id))}</strong><span>Proposta {offer.proposal_number||"sem número"} · validade {dateBR(offer.validity_date)}</span></div><dl><div><dt>Total posto</dt><dd>{money(offer.total_delivered_cost)}</dd></div><div><dt>Pagamento</dt><dd>{offer.payment_terms||"—"}</dd></div><div><dt>Prazo</dt><dd>{offer.delivery_days??"—"} dias</dd></div><div><dt>Frete</dt><dd>{offer.freight_terms||"—"}</dd></div></dl></article>)}</div>:<p className="quotation-muted">Nenhuma proposta recebida.</p>}</article><article className="quotation-card"><div className="quotation-card-title"><div><span>Arquivo privado</span><h3>Documentos</h3></div><strong>{documents.length}</strong></div>{documents.length?<div className="quotation-document-list">{documents.map((document)=><div key={document.id}><div><strong>{document.file_name}</strong><small>{documentLabels[document.document_type]}{document.supplier_id?` · ${supplierNames[document.supplier_id]||"Fornecedor"}`:""}</small></div>{document.signed_url?<a href={document.signed_url} target="_blank" rel="noreferrer">Abrir</a>:null}{canManage&&quotation.status!=="approved"?<form action={removeMaterialQuotationDocument}><input type="hidden" name="quotation_id" value={quotation.id}/><input type="hidden" name="document_id" value={document.id}/><button type="submit">Remover</button></form>:null}</div>)}</div>:<p className="quotation-muted">Nenhum documento anexado.</p>}{canManage?<form action={uploadMaterialQuotationDocuments} className="quotation-upload-form" encType="multipart/form-data"><input type="hidden" name="quotation_id" value={quotation.id}/><label>Fornecedor<select name="supplier_id"><option value="">Documento geral</option>{invites.map((invite)=><option key={invite.id} value={invite.supplier_id}>{invite.supplier_name}</option>)}</select></label><label>Tipo<select name="document_type"><option value="proposal">Proposta</option><option value="request">Solicitação</option><option value="technical">Técnico</option><option value="approval">Aprovação</option><option value="other">Outro</option></select></label><label>Arquivos<input name="documents" type="file" multiple accept="application/pdf,image/*,.xlsx,.docx"/></label><label>Legenda<input name="caption"/></label><button type="submit">Anexar</button></form>:null}</article></section>

    <section className="quotation-workflow"><div><span>Fluxo da cotação</span><h3>Ações disponíveis</h3><p>A aprovação não compromete a solicitação. A quantidade será comprometida quando o Pedido de Compra for emitido.</p></div><div className="quotation-workflow-actions">{canManage&&quotation.status==="draft"?<form action={openMaterialQuotation}><input type="hidden" name="quotation_id" value={quotation.id}/><button className="primary" type="submit">Abrir para propostas</button></form>:null}{canManage&&quotation.status==="collecting"&&quotation.responses_count>0?<form action={startMaterialQuotationAnalysis}><input type="hidden" name="quotation_id" value={quotation.id}/><button className="primary" type="submit">Encerrar e analisar</button></form>:null}{canCancel&&!["approved","cancelled"].includes(quotation.status)?<form action={cancelMaterialQuotation} className="inline-reason"><input type="hidden" name="quotation_id" value={quotation.id}/><input name="reason" required placeholder="Motivo obrigatório"/><button className="danger" type="submit">Cancelar</button></form>:null}</div></section>
  </>;
}
