import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { fetchAllRows } from "@/lib/supabase-pagination";
import { requireCompanyPermission } from "@/lib/workspace";
import "../../procurement-intelligence.css";

type Project={id:string;code:string|null;name:string};
type Request={id:string;request_number:string;status:string;created_at:string;approved_at:string|null};
type Order={id:string;quotation_id:string|null;supplier_id:string;order_number:string;status:string;issue_date:string|null;expected_delivery_date:string|null;total_amount:number;received_amount:number;invoiced_amount:number;issued_at:string|null;created_at:string};
type OrderItem={order_id:string;request_number:string;ordered_quantity:number;accepted_quantity:number;rejected_quantity:number};
type Receipt={id:string;order_id:string;supplier_id:string;status:string;receipt_date:string;approved_at:string|null;created_at:string};
type ReceiptItem={receipt_id:string;accepted_quantity:number;rejected_quantity:number;accepted_amount:number};
type Quotation={id:string;status:string;created_at:string;approved_at:string|null;total_awarded_amount:number;responses_count:number};
type OfferItem={quotation_item_id:string;total_delivered_cost:number};
type Award={quotation_item_id:string;awarded_total_cost:number};
type Invoice={id:string;supplier_id:string;status:string;validation_status:string;three_way_status:string;invoice_total:number;issue_date:string;created_at:string};
type Discrepancy={status:string;severity:string;created_at:string;resolved_at:string|null};
type Control={planned_total_cost:number;ordered_value:number;received_value:number;invoiced_value:number;consumed_quantity:number;stock_value:number;coverage_status:string;rejected_quantity:number;received_quantity:number};
type Performance={supplier_id:string;trade_name:string|null;legal_name:string;overall_score:number|null;classification:string;order_count:number;ordered_value:number;rejected_quantity:number};

const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(value||0));
const number=(value:number,digits=1)=>new Intl.NumberFormat("pt-BR",{maximumFractionDigits:digits}).format(Number(value||0));
const percent=(value:number)=>`${number(value,1)}%`;
const daysBetween=(a:string,b:string)=>Math.max(0,Math.round((new Date(b).getTime()-new Date(a).getTime())/86400000));
function average(values:number[]){return values.length?values.reduce((a,b)=>a+b,0)/values.length:0;}
function inRange(value:string|undefined|null,from:string,to:string){if(!value)return false;const date=value.slice(0,10);return(!from||date>=from)&&(!to||date<=to);}

export default async function ProcurementIndicatorsPage({searchParams}:{searchParams:Promise<{from?:string;to?:string;success?:string;error?:string}>}){
  const params=await searchParams;
  const today=new Date();
  const defaultFrom=new Date(Date.UTC(today.getUTCFullYear()-1,today.getUTCMonth(),today.getUTCDate())).toISOString().slice(0,10);
  const from=params.from??defaultFrom;
  const to=params.to??today.toISOString().slice(0,10);
  const {supabase,company,companyId,projectId}=await requireCompanyPermission("procurement.intelligence.view");
  const [projectResult,requestsResult,ordersResult,orderItemsResult,receiptsResult,receiptItemsResult,quotationsResult,offerItemsResult,awardsResult,invoicesResult,receiptDivResult,invoiceDivResult,controlResult,performanceResult]=await Promise.all([
    projectId?supabase.from("projects").select("id,code,name").eq("id",projectId).eq("company_id",companyId).maybeSingle():Promise.resolve({data:null,error:null}),
    projectId?fetchAllRows<Request>(async(a,b)=>{const{data,error}=await supabase.from("execution_material_requests").select("id,request_number,status,created_at,approved_at").eq("company_id",companyId).eq("project_id",projectId).order("created_at").range(a,b);return{data:(data??[])as Request[],error};}):Promise.resolve({data:[]as Request[],error:null}),
    projectId?fetchAllRows<Order>(async(a,b)=>{const{data,error}=await supabase.from("procurement_purchase_orders").select("id,quotation_id,supplier_id,order_number,status,issue_date,expected_delivery_date,total_amount,received_amount,invoiced_amount,issued_at,created_at").eq("company_id",companyId).eq("project_id",projectId).order("created_at").range(a,b);return{data:(data??[])as Order[],error};}):Promise.resolve({data:[]as Order[],error:null}),
    projectId?fetchAllRows<OrderItem>(async(a,b)=>{const{data,error}=await supabase.from("procurement_purchase_order_items").select("order_id,request_number,ordered_quantity,accepted_quantity,rejected_quantity").eq("company_id",companyId).eq("project_id",projectId).range(a,b);return{data:(data??[])as OrderItem[],error};}):Promise.resolve({data:[]as OrderItem[],error:null}),
    projectId?fetchAllRows<Receipt>(async(a,b)=>{const{data,error}=await supabase.from("procurement_material_receipts").select("id,order_id,supplier_id,status,receipt_date,approved_at,created_at").eq("company_id",companyId).eq("project_id",projectId).order("receipt_date").range(a,b);return{data:(data??[])as Receipt[],error};}):Promise.resolve({data:[]as Receipt[],error:null}),
    projectId?fetchAllRows<ReceiptItem>(async(a,b)=>{const{data,error}=await supabase.from("procurement_material_receipt_items").select("receipt_id,accepted_quantity,rejected_quantity,accepted_amount").eq("company_id",companyId).eq("project_id",projectId).range(a,b);return{data:(data??[])as ReceiptItem[],error};}):Promise.resolve({data:[]as ReceiptItem[],error:null}),
    projectId?fetchAllRows<Quotation>(async(a,b)=>{const{data,error}=await supabase.from("procurement_material_quotations").select("id,status,created_at,approved_at,total_awarded_amount,responses_count").eq("company_id",companyId).eq("project_id",projectId).order("created_at").range(a,b);return{data:(data??[])as Quotation[],error};}):Promise.resolve({data:[]as Quotation[],error:null}),
    projectId?fetchAllRows<OfferItem>(async(a,b)=>{const{data,error}=await supabase.from("procurement_material_quotation_offer_items").select("quotation_item_id,total_delivered_cost").eq("company_id",companyId).eq("project_id",projectId).range(a,b);return{data:(data??[])as OfferItem[],error};}):Promise.resolve({data:[]as OfferItem[],error:null}),
    projectId?fetchAllRows<Award>(async(a,b)=>{const{data,error}=await supabase.from("procurement_material_quotation_awards").select("quotation_item_id,awarded_total_cost").eq("company_id",companyId).eq("project_id",projectId).range(a,b);return{data:(data??[])as Award[],error};}):Promise.resolve({data:[]as Award[],error:null}),
    projectId?fetchAllRows<Invoice>(async(a,b)=>{const{data,error}=await supabase.from("finance_electronic_invoices").select("id,supplier_id,status,validation_status,three_way_status,invoice_total,issue_date,created_at").eq("company_id",companyId).eq("project_id",projectId).order("issue_date").range(a,b);return{data:(data??[])as Invoice[],error};}):Promise.resolve({data:[]as Invoice[],error:null}),
    projectId?fetchAllRows<Discrepancy>(async(a,b)=>{const{data,error}=await supabase.from("procurement_material_receipt_discrepancies").select("status,severity,created_at,resolved_at").eq("company_id",companyId).eq("project_id",projectId).range(a,b);return{data:(data??[])as Discrepancy[],error};}):Promise.resolve({data:[]as Discrepancy[],error:null}),
    projectId?fetchAllRows<Discrepancy>(async(a,b)=>{const{data,error}=await supabase.from("finance_electronic_invoice_divergences").select("status,severity,created_at,resolved_at").eq("company_id",companyId).eq("project_id",projectId).range(a,b);return{data:(data??[])as Discrepancy[],error};}):Promise.resolve({data:[]as Discrepancy[],error:null}),
    projectId?fetchAllRows<Control>(async(a,b)=>{const{data,error}=await supabase.from("procurement_integrated_supply_control").select("planned_total_cost,ordered_value,received_value,invoiced_value,consumed_quantity,stock_value,coverage_status,rejected_quantity,received_quantity").eq("company_id",companyId).eq("project_id",projectId).range(a,b);return{data:(data??[])as Control[],error};}):Promise.resolve({data:[]as Control[],error:null}),
    projectId?fetchAllRows<Performance>(async(a,b)=>{const{data,error}=await supabase.from("procurement_supplier_performance").select("supplier_id,trade_name,legal_name,overall_score,classification,order_count,ordered_value,rejected_quantity").eq("company_id",companyId).eq("project_id",projectId).order("overall_score",{ascending:false,nullsFirst:false}).range(a,b);return{data:(data??[])as Performance[],error};}):Promise.resolve({data:[]as Performance[],error:null}),
  ]);
  const project=projectResult.data as Project|null;
  const orders=ordersResult.data.filter(row=>inRange(row.issued_at??row.issue_date??row.created_at,from,to)&&row.status!=="cancelled");
  const requests=requestsResult.data.filter(row=>inRange(row.created_at,from,to)&&row.status!=="cancelled");
  const receipts=receiptsResult.data.filter(row=>inRange(row.approved_at??row.receipt_date,from,to)&&row.status==="approved");
  const quotations=quotationsResult.data.filter(row=>inRange(row.approved_at??row.created_at,from,to)&&row.status!=="cancelled");
  const invoices=invoicesResult.data.filter(row=>inRange(row.issue_date??row.created_at,from,to)&&row.status!=="cancelled");
  const requestMap=new Map(requestsResult.data.map(row=>[row.request_number,row]));
  const orderMap=new Map(ordersResult.data.map(row=>[row.id,row]));
  const orderItemMap=new Map<string,OrderItem[]>();orderItemsResult.data.forEach(row=>orderItemMap.set(row.order_id,[...(orderItemMap.get(row.order_id)??[]),row]));
  const requestOrderLead:number[]=[];const seenPairs=new Set<string>();
  orders.forEach(order=>(orderItemMap.get(order.id)??[]).forEach(item=>{const request=requestMap.get(item.request_number);const pair=`${order.id}:${item.request_number}`;if(request&&!seenPairs.has(pair)){seenPairs.add(pair);requestOrderLead.push(daysBetween(request.created_at,order.issued_at??order.issue_date??order.created_at));}}));
  const firstReceipt=new Map<string,Receipt>();receipts.forEach(row=>{const current=firstReceipt.get(row.order_id);if(!current||row.receipt_date<current.receipt_date)firstReceipt.set(row.order_id,row);});
  const orderReceiptLead=[...firstReceipt].flatMap(([orderId,receipt])=>{const order=orderMap.get(orderId);return order?[daysBetween(order.issued_at??order.issue_date??order.created_at,receipt.receipt_date)]:[];});
  const delayed=orders.filter(row=>!["received","closed"].includes(row.status)&&row.expected_delivery_date&&row.expected_delivery_date<to).length;
  const partial=orders.filter(row=>row.status==="partially_received").length;
  const noQuotation=orders.filter(row=>!row.quotation_id).length;
  const offerMap=new Map<string,number[]>();offerItemsResult.data.forEach(row=>offerMap.set(row.quotation_item_id,[...(offerMap.get(row.quotation_item_id)??[]),Number(row.total_delivered_cost)]));
  const estimatedSavings=awardsResult.data.reduce((sum,award)=>{const offers=offerMap.get(award.quotation_item_id)??[];const avg=average(offers);return sum+Math.max(0,avg-Number(award.awarded_total_cost));},0);
  const approvedReceipts=new Set(receipts.map(row=>row.id));
  const receiptItems=receiptItemsResult.data.filter(row=>approvedReceipts.has(row.receipt_id));
  const acceptedQty=receiptItems.reduce((s,row)=>s+Number(row.accepted_quantity),0);const rejectedQty=receiptItems.reduce((s,row)=>s+Number(row.rejected_quantity),0);
  const rejectionRate=acceptedQty+rejectedQty?100*rejectedQty/(acceptedQty+rejectedQty):0;
  const allDiv=[...receiptDivResult.data,...invoiceDivResult.data].filter(row=>inRange(row.created_at,from,to));
  const openDiv=allDiv.filter(row=>!["resolved","waived"].includes(row.status));
  const resolvedDays=allDiv.filter(row=>row.resolved_at).map(row=>daysBetween(row.created_at,row.resolved_at!));
  const blockedInvoices=invoices.filter(row=>row.validation_status==="blocked"||row.three_way_status==="blocked").length;
  const planned=controlResult.data.reduce((s,row)=>s+Number(row.planned_total_cost),0);const committed=controlResult.data.reduce((s,row)=>s+Number(row.ordered_value),0);const receivedValue=controlResult.data.reduce((s,row)=>s+Number(row.received_value),0);const invoicedValue=controlResult.data.reduce((s,row)=>s+Number(row.invoiced_value),0);const stockValue=controlResult.data.reduce((s,row)=>s+Number(row.stock_value),0);const consumed=controlResult.data.reduce((s,row)=>s+Number(row.consumed_quantity),0);const coverageRisk=controlResult.data.filter(row=>["rupture","critical","order_now"].includes(row.coverage_status)).length;
  const evaluated=performanceResult.data.filter(row=>row.overall_score!=null);const best=evaluated[0]??null;const worst=evaluated.length?[...evaluated].sort((a,b)=>Number(a.overall_score)-Number(b.overall_score))[0]:null;
  const context=project?`${project.code?`${project.code} · `:""}${project.name}`:"Selecione uma obra";

  return <AppShell activeGroup="procurement" activeItem="procurement-indicators" eyebrow="Suprimentos · Gestão" title="Indicadores de Suprimentos" description={`${company.name} · ${context} · velocidade, competição, entrega, qualidade, cobertura e desempenho financeiro do ciclo de materiais.`} actions={<><Link className="elos-button secondary" href="/suprimentos/controle-integrado">Controle integrado</Link><Link className="elos-button" href="/suprimentos/desempenho-fornecedores">Fornecedores</Link></>}>
    {controlResult.error?<div className="auth-message error workspace-message">A estrutura de indicadores ainda não está instalada. Execute a migration <strong>0066</strong>.</div>:null}
    {!projectId?<div className="intelligence-empty">Selecione uma obra no topo.</div>:<>
      <section className="indicator-filter"><form method="get"><label>De<input name="from" type="date" defaultValue={from}/></label><label>Até<input name="to" type="date" defaultValue={to}/></label><button type="submit">Atualizar período</button></form><span>Período aplicado aos fluxos concluídos; cobertura e estoque refletem o saldo atual.</span></section>
      <section className="intelligence-kpis indicators"><article><span>Solicitação → pedido</span><strong>{number(average(requestOrderLead))} dias</strong><small>{requestOrderLead.length} ciclo(s) medido(s)</small></article><article><span>Pedido → 1ª entrega</span><strong>{number(average(orderReceiptLead))} dias</strong><small>{orderReceiptLead.length} pedido(s) recebido(s)</small></article><article className={noQuotation?"warning":""}><span>Sem cotação / emergencial</span><strong>{noQuotation}</strong><small>{orders.length?percent(100*noQuotation/orders.length):"0%"} dos pedidos</small></article><article><span>Economia estimada</span><strong>{money(estimatedSavings)}</strong><small>vencedor versus média das propostas</small></article><article className={delayed?"danger":""}><span>Pedidos atrasados</span><strong>{delayed}</strong><small>{partial} com entrega parcial</small></article><article className={blockedInvoices?"danger":""}><span>NF-e bloqueadas</span><strong>{blockedInvoices}</strong><small>aguardam correção ou dispensa</small></article><article className={openDiv.length?"warning":""}><span>Divergências abertas</span><strong>{openDiv.length}</strong><small>{number(average(resolvedDays))} dias para resolver</small></article><article className={rejectionRate>2?"danger":""}><span>Rejeição de materiais</span><strong>{percent(rejectionRate)}</strong><small>{number(rejectedQty,3)} unidade(s) rejeitada(s)</small></article></section>

      <section className="indicator-financial"><div><span>Cobertura atual do ciclo</span><h2>Planejado, comprometido e realizado</h2><p>Os valores abaixo vêm do mesmo controle por insumo utilizado no planejamento da compra.</p></div><div className="financial-waterfall"><article><span>Planejado a comprar</span><strong>{money(planned)}</strong></article><i>→</i><article><span>Comprometido</span><strong>{money(committed)}</strong><small>{planned?percent(100*committed/planned):"0%"}</small></article><i>→</i><article><span>Recebido</span><strong>{money(receivedValue)}</strong></article><i>→</i><article><span>Faturado</span><strong>{money(invoicedValue)}</strong></article><i>+</i><article><span>Estoque atual</span><strong>{money(stockValue)}</strong></article></div></section>

      <section className="intelligence-grid three"><article className="intelligence-card"><span>Demanda e cobertura</span><h2>{coverageRisk} risco(s) imediato(s)</h2><dl className="indicator-list"><div><dt>Solicitações abertas no período</dt><dd>{requests.filter(row=>!["attended"].includes(row.status)).length}</dd></div><div><dt>Cotações conduzidas</dt><dd>{quotations.length}</dd></div><div><dt>Pedidos emitidos</dt><dd>{orders.length}</dd></div><div><dt>Quantidade consumida</dt><dd>{number(consumed,3)}</dd></div></dl><Link href="/suprimentos/controle-integrado?risk=critical">Abrir materiais críticos</Link></article><article className="intelligence-card"><span>Melhor desempenho</span><h2>{best?.trade_name||best?.legal_name||"Sem histórico"}</h2>{best?<><strong className="big-score">{number(best.overall_score!)} pontos</strong><p>{best.order_count} pedido(s) · {money(best.ordered_value)}</p></>:<p>Ainda não existem fornecedores com pedidos suficientes.</p>}<Link href="/suprimentos/desempenho-fornecedores">Abrir ranking completo</Link></article><article className="intelligence-card"><span>Maior atenção</span><h2>{worst?.trade_name||worst?.legal_name||"Sem histórico"}</h2>{worst?<><strong className="big-score danger-text">{number(worst.overall_score!)} pontos</strong><p>{worst.classification} · {number(worst.rejected_quantity,3)} rejeitado</p></>:<p>Nenhum fornecedor classificado.</p>}<Link href="/suprimentos/desempenho-fornecedores?sort=risk">Ver fornecedores de risco</Link></article></section>

      <section className="intelligence-card"><div className="section-heading"><div><span>Resumo do período</span><h2>Volumes processados</h2></div><p>{from.split("-").reverse().join("/")} a {to.split("-").reverse().join("/")}</p></div><div className="indicator-volume-grid"><article><span>Solicitações</span><strong>{requests.length}</strong></article><article><span>Cotações</span><strong>{quotations.length}</strong></article><article><span>Pedidos</span><strong>{orders.length}</strong><small>{money(orders.reduce((s,row)=>s+Number(row.total_amount),0))}</small></article><article><span>Recebimentos</span><strong>{receipts.length}</strong><small>{money(receiptItems.reduce((s,row)=>s+Number(row.accepted_amount),0))}</small></article><article><span>NF-e</span><strong>{invoices.length}</strong><small>{money(invoices.reduce((s,row)=>s+Number(row.invoice_total),0))}</small></article><article><span>Fornecedores avaliados</span><strong>{evaluated.length}</strong></article></div></section>
    </>}
  </AppShell>;
}
