import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";
type J=Record<string,unknown>;type Stage={koper_id:string;koper_parent_id:string|null;payload:unknown};type Order={id:string;source_id:string|null};type OI={id:string;order_id:string;input_id:string;cost_center_service_id:string|null;accepted_quantity:number;received_quantity:number;ordered_quantity:number};type Input={id:string;source_id:string|null};
const obj=(v:unknown):J=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:{};const arr=(v:unknown):J[]=>Array.isArray(v)?v.map(obj):[];const id=(v:unknown):string|null=>(typeof v==="string"||typeof v==="number")&&String(v).trim()?String(v).trim():null;const num=(v:unknown):number|null=>typeof v==="number"&&Number.isFinite(v)?v:typeof v==="string"&&v.trim()&&Number.isFinite(Number(v))?Number(v):null;const uniq=<T>(v:T[])=>[...new Set(v)];
const orderSources=(p:J)=>uniq(arr(p.purchaseOrders).flatMap(x=>{const y=id(x.purchaseOrderId??x.purchase_order_id);return y?[y]:[]}));const productSources=(p:J)=>uniq([id(p.mainProductId),id(p.productId),id(p.inputId),id(p.genericProdSeq)].filter((x):x is string=>!!x));const qty=(p:J)=>num(p.productAmount)??num(p.quantity)??num(p.amount)??num(p.invoiceProductAmount);
async function all<T>(t:string,q:Record<string,string>){const out:T[]=[];for(let o=0;;o+=1000){const rows=await requestSupabase<T[]>(t,{query:new URLSearchParams({...q,limit:"1000",offset:String(o)}),timeoutMs:30000});out.push(...rows);if(rows.length<1000)return out}}
const [resolutions,invoices,products,orders,items,inputs]=await Promise.all([all<Stage>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.bill_resolution",sync_state:"eq.present"}),all<Stage>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.xml_invoice",sync_state:"eq.present"}),all<Stage>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.xml_invoice_product",sync_state:"eq.present"}),all<Order>("procurement_purchase_orders",{select:"id,source_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper"}),all<OI>("procurement_purchase_order_items",{select:"id,order_id,input_id,cost_center_service_id,accepted_quantity,received_quantity,ordered_quantity",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper"}),all<Input>("engineering_inputs",{select:"id,source_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper"})]);
const invById=new Map(invoices.map(x=>[x.koper_id,x]));const productsByInv=new Map<string,Stage[]>();for(const x of products)if(x.koper_parent_id)productsByInv.set(x.koper_parent_id,[...(productsByInv.get(x.koper_parent_id)??[]),x]);const orderBySource=new Map(orders.flatMap(x=>x.source_id?[[x.source_id,x] as const]:[]));const itemsByOrder=new Map<string,OI[]>();for(const x of items)itemsByOrder.set(x.order_id,[...(itemsByOrder.get(x.order_id)??[]),x]);const inputBySource=new Map(inputs.flatMap(x=>x.source_id?[[x.source_id,x] as const]:[]));
const targets=resolutions.filter(r=>{const p=obj(r.payload);return Number(p.version??0)>=2&&p.status==="unresolved"&&p.route==="invoice";});let candidates=0,aggregateViolations=0;const examples:J[]=[];
for(const r of targets){const p=obj(r.payload),invoiceId=id(obj(p.ids).invoiceId);if(!invoiceId)continue;const inv=invById.get(invoiceId);if(!inv)continue;const os=orderSources(obj(inv.payload)).flatMap(s=>{const o=orderBySource.get(s);return o?[o]:[]});if(os.length!==1)continue;const order=os[0]!,prods=productsByInv.get(invoiceId)??[];if(!prods.length)continue;const sums=new Map<string,{q:number;oi:OI}>();let bad=false;for(const prod of prods){const pp=obj(prod.payload),q=qty(pp);if(q===null||q<=0){bad=true;break}const nativeInputs=new Set(productSources(pp).flatMap(s=>{const i=inputBySource.get(s);return i?[i.id]:[]}));const matches=(itemsByOrder.get(order.id)??[]).filter(x=>nativeInputs.has(x.input_id)&&!!x.cost_center_service_id);if(matches.length!==1){bad=true;break}const oi=matches[0]!,g=sums.get(oi.id)??{q:0,oi};g.q+=q;sums.set(oi.id,g);}if(bad)continue;candidates++;for(const g of sums.values()){const caps=[Number(g.oi.ordered_quantity??0),Number(g.oi.accepted_quantity??0),Number(g.oi.received_quantity??0)].filter(v=>Number.isFinite(v)&&v>0),cap=caps.length?Math.max(...caps):0,tol=Math.max(0.1,cap*0.005);if(!cap||g.q>cap+tol){aggregateViolations++;if(examples.length<20)examples.push({billId:r.koper_id,invoiceId,orderItemId:g.oi.id,aggregateQty:g.q,cap,ordered:g.oi.ordered_quantity,accepted:g.oi.accepted_quantity,received:g.oi.received_quantity});}}}
console.log("KOPER_NFE_PARTIAL_AGGREGATE_SAFETY",JSON.stringify({targets:targets.length,candidates,aggregateViolations,examples}));if(aggregateViolations>0)throw new Error(`NF-e partial aggregate safety failed: ${aggregateViolations} violations`);
