import { createHash } from "node:crypto";
import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";
type S={koper_id:string;koper_parent_id:string|null;payload:unknown};
type Inv={id:string;registry_number:string;access_key:string;status:string;validation_status:string;three_way_status:string;order_id:string|null;receipt_id:string|null;supplier_id:string;project_id:string;item_count:number;mapped_item_count:number;divergence_count:number};
type Item={id:string;invoice_id:string;mapping_status:string;input_id:string|null;order_item_id:string|null;receipt_item_id:string|null;three_way_status:string};
function stable(seed:string){const b=Buffer.from(createHash("sha256").update(seed).digest("hex").slice(0,32),"hex");b[6]=((b[6]??0)&15)|80;b[8]=((b[8]??0)&63)|128;const h=b.toString("hex");return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`}
async function all<T>(t:string,q:Record<string,string>){const out:T[]=[];for(let o=0;;o+=1000){const rows=await requestSupabase<T[]>(t,{query:new URLSearchParams({...q,limit:"1000",offset:String(o)})});out.push(...rows);if(rows.length<1000)return out}}
function dup(values:string[]){const m=new Map<string,number>();for(const x of values)m.set(x,(m.get(x)??0)+1);return [...m.entries()].filter(([,n])=>n>1).map(([value,count])=>({value,count}))}
function counts(values:string[]){const r:Record<string,number>={};for(const x of values)r[x]=(r[x]??0)+1;return r}
await import("./index.js");
const [sourceInvoices,sourceProducts,nativeInvoices,nativeItems,suppliers,payables,installments]=await Promise.all([
 all<S>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.xml_invoice",sync_state:"eq.present",order:"koper_id.asc"}),
 all<S>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.xml_invoice_product",sync_state:"eq.present",order:"koper_parent_id.asc,koper_id.asc"}),
 all<Inv>("finance_electronic_invoices",{select:"id,registry_number,access_key,status,validation_status,three_way_status,order_id,receipt_id,supplier_id,project_id,item_count,mapped_item_count,divergence_count",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),
 all<Item>("finance_electronic_invoice_items",{select:"id,invoice_id,mapping_status,input_id,order_item_id,receipt_item_id,three_way_status",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),
 all<any>("suppliers",{select:"id,source_id,legal_name,notes",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper",order:"source_id.asc"}),
 all<{id:string}>("payables",{select:"id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),
 all<{id:string}>("finance_electronic_invoice_installments",{select:"id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"})]);
const expectedInvoiceIds=new Set(sourceInvoices.map(x=>stable(`elos:koper:electronic-invoice:${x.koper_id}`)));const nativeById=new Map(nativeInvoices.map(x=>[x.id,x]));const missingInvoices=[...expectedInvoiceIds].filter(x=>!nativeById.has(x));const koperInvoices=nativeInvoices.filter(x=>expectedInvoiceIds.has(x.id));const expectedProductIds=new Set(sourceProducts.map(x=>stable(`elos:koper:electronic-invoice:${x.koper_parent_id}:product:${x.koper_id}`)));const nativeItemById=new Map(nativeItems.map(x=>[x.id,x]));const missingItems=[...expectedProductIds].filter(x=>!nativeItemById.has(x));const koperItems=nativeItems.filter(x=>expectedProductIds.has(x.id));const orphanKoperItems=koperItems.filter(x=>!expectedInvoiceIds.has(x.invoice_id));const itemCounts=new Map<string,number>();for(const it of koperItems)itemCounts.set(it.invoice_id,(itemCounts.get(it.invoice_id)??0)+1);const headerCountMismatches=koperInvoices.filter(x=>Number(x.item_count)!==(itemCounts.get(x.id)??0)).map(x=>({id:x.id,header:x.item_count,actual:itemCounts.get(x.id)??0}));const s620=suppliers.find(x=>x.source_id==="620"),s621=suppliers.find(x=>x.source_id==="621");
console.log("KOPER_NFE_COMPLETE_COVERAGE_AUDIT",JSON.stringify({ok:missingInvoices.length===0&&missingItems.length===0&&orphanKoperItems.length===0&&headerCountMismatches.length===0&&dup(koperInvoices.map(x=>x.registry_number)).length===0&&dup(koperInvoices.map(x=>x.access_key)).length===0,source:{invoices:sourceInvoices.length,products:sourceProducts.length},native:{koperInvoices:koperInvoices.length,koperItems:koperItems.length,missingInvoices:missingInvoices.length,missingItems:missingItems.length,orphanKoperItems:orphanKoperItems.length,headerCountMismatches:headerCountMismatches.length,duplicateRegistryNumbers:dup(koperInvoices.map(x=>x.registry_number)).length,duplicateAccessKeys:dup(koperInvoices.map(x=>x.access_key)).length},links:{withOrder:koperInvoices.filter(x=>x.order_id).length,withReceipt:koperInvoices.filter(x=>x.receipt_id).length,withoutOrder:koperInvoices.filter(x=>!x.order_id).length,withoutReceipt:koperInvoices.filter(x=>!x.receipt_id).length},invoiceStatuses:counts(koperInvoices.map(x=>x.status)),validationStatuses:counts(koperInvoices.map(x=>x.validation_status)),threeWayStatuses:counts(koperInvoices.map(x=>x.three_way_status)),itemMappingStatuses:counts(koperItems.map(x=>x.mapping_status)),itemThreeWayStatuses:counts(koperItems.map(x=>x.three_way_status)),items:{withInput:koperItems.filter(x=>x.input_id).length,withOrderItem:koperItems.filter(x=>x.order_item_id).length,withReceiptItem:koperItems.filter(x=>x.receipt_item_id).length},historicalSuppliers:{s620:s620??null,s621:s621??null},financialBaseline:{payables:payables.length,invoiceInstallments:installments.length},samples:{missingInvoices:missingInvoices.slice(0,10),missingItems:missingItems.slice(0,10),headerCountMismatches:headerCountMismatches.slice(0,10)}}));