import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";

type Json=Record<string,unknown>;
type Stage={koper_id:string;payload:unknown;last_seen_at:string};
type Payable={source_id:string|null;amount:number;status:string;paid_at:string|null;paid_amount:number|null};
type Supplier={id:string;source_id:string|null};
const FLOW_PROJECT_ID="ffe8b7ec-1f01-4f6c-8a03-2bd6d3ae94fc",FLOW_COST_CENTER_ID="169";
const obj=(v:unknown):Json=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as Json:{};
const text=(v:unknown):string|null=>v===null||v===undefined?null:(String(v).trim()||null);
const num=(v:unknown):number|null=>v===null||v===undefined||v===""?null:(Number.isFinite(Number(v))?Number(v):null);
const cents=(v:unknown):number|null=>{const n=num(v);return n===null?null:Math.round((n+Number.EPSILON)*100);};
const paid=(v:unknown)=>v===true||v===1||v==="1"||String(v??"").toUpperCase()==="S";
const dateOnly=(v:unknown):string|null=>{const s=text(v);const m=s?.match(/^\d{4}-\d{2}-\d{2}/);return m?.[0]??null;};
async function all<T>(table:string,q:Record<string,string>):Promise<T[]>{const out:T[]=[];for(let o=0;;o+=1000){const page=await requestSupabase<T[]>(table,{query:new URLSearchParams({...q,limit:"1000",offset:String(o)})});out.push(...page);if(page.length<1000)return out;}}

const latest=await requestSupabase<Array<{last_seen_at:string}>>("koper_staging_records",{query:new URLSearchParams({select:"last_seen_at",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.bill_to_pay",order:"last_seen_at.desc",limit:"1"})});
const snapshotAt=latest[0]?.last_seen_at;if(!snapshotAt)throw new Error("NO_PAYABLE_SOURCE_SNAPSHOT");
const [sources,details,elos,supplierRows]=await Promise.all([
 all<Stage>("koper_staging_records",{select:"koper_id,payload,last_seen_at",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.bill_to_pay",last_seen_at:`eq.${snapshotAt}`,order:"koper_id.asc"}),
 all<Stage>("koper_staging_records",{select:"koper_id,payload,last_seen_at",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.bill_to_pay_detail",order:"koper_id.asc"}),
 all<Payable>("payables",{select:"source_id,amount,status,paid_at,paid_amount",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper_flow",order:"source_id.asc"}),
 all<Supplier>("suppliers",{select:"id,source_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper",order:"source_id.asc"})]);
const source=new Map<string,Stage>();for(const r of sources){if(source.has(r.koper_id))throw new Error(`DUPLICATE_SOURCE_${r.koper_id}`);source.set(r.koper_id,r);}const detail=new Map<string,Stage>();for(const r of details){if(detail.has(r.koper_id))throw new Error(`DUPLICATE_DETAIL_${r.koper_id}`);detail.set(r.koper_id,r);}const direct=new Map<string,Payable>();const synthetic=elos.filter(r=>r.source_id?.startsWith("koper_bill:missing-")===true);for(const r of elos){const m=r.source_id?.match(/^koper_bill:(\d+)$/);if(!m)continue;if(direct.has(m[1]!))throw new Error(`DUPLICATE_ELOS_${m[1]}`);direct.set(m[1]!,r);}const suppliers=new Set(supplierRows.flatMap(r=>r.source_id?[r.source_id]:[]));
const missing=[...source.keys()].filter(id=>!direct.has(id)),elosOnly=[...direct.keys()].filter(id=>!source.has(id));let sourceAmount=0,missingAmount=0,missingPaid=0,missingOpen=0;const amountMismatch:string[]=[],statusRepairs:string[]=[],missingDetail:string[]=[],staleDetail:string[]=[],unresolvedSupplier:string[]=[],invalidCostCenter:string[]=[],invalidFinancial:string[]=[],paidWithoutDate:string[]=[],paidWithoutValue:string[]=[];
for(const[id,s]of source){const p=obj(s.payload),amount=cents(p.billValue);sourceAmount+=amount??0;const e=direct.get(id);if(e){if(amount!==cents(e.amount))amountMismatch.push(id);const target=paid(p.isPaid)?"paid":"open";if(e.status!==target||(target==="paid"&&(dateOnly(e.paid_at)!==dateOnly(p.paymentDate)||cents(e.paid_amount)!==cents(p.paymentValue))))statusRepairs.push(id);continue;}if(amount===null||amount<=0||!dateOnly(p.dueDate))invalidFinancial.push(id);else missingAmount+=amount;if(paid(p.isPaid)){missingPaid++;if(!dateOnly(p.paymentDate))paidWithoutDate.push(id);const pv=cents(p.paymentValue);if(pv===null||pv<=0)paidWithoutValue.push(id);}else missingOpen++;const d=detail.get(id);if(!d){missingDetail.push(id);continue;}if(new Date(d.last_seen_at).valueOf()<new Date(snapshotAt).valueOf())staleDetail.push(id);const dp=obj(d.payload),sid=text(dp.supplierId);if(!sid||!suppliers.has(sid))unresolvedSupplier.push(id);const cc=obj(dp.costCenter);if(text(cc.id)!==FLOW_COST_CENTER_ID)invalidCostCenter.push(id);}
const matchedAmount=[...direct.entries()].reduce((sum,[id,e])=>source.has(id)?sum+(cents(e.amount)??0):sum,0),reconciliationDiff=sourceAmount-matchedAmount-missingAmount;const blockers={elosOnly:elosOnly.length,amountMismatch:amountMismatch.length,missingDetail:missingDetail.length,staleDetail:staleDetail.length,unresolvedSupplier:unresolvedSupplier.length,invalidCostCenter:invalidCostCenter.length,invalidFinancial:invalidFinancial.length,paidWithoutDate:paidWithoutDate.length,paidWithoutValue:paidWithoutValue.length,reconciliationDiff:reconciliationDiff/100};const ready=Object.values(blockers).every(v=>v===0);
console.log("KOPER_NATIVE_PAYABLE_STAGED_PLAN",JSON.stringify({ok:true,readOnly:true,ready,snapshotAt,source:{rows:source.size,amount:sourceAmount/100},elos:{direct:direct.size,synthetic:synthetic.length},details:{rows:detail.size},plan:{missing:missing.length,missingAmount:missingAmount/100,missingPaid,missingOpen,statusRepairs:statusRepairs.length},mapping:{koperCostCenter:FLOW_COST_CENTER_ID,elosProject:FLOW_PROJECT_ID},blockers,examples:{missingDetail:missingDetail.slice(0,12),staleDetail:staleDetail.slice(0,12),unresolvedSupplier:unresolvedSupplier.slice(0,12),invalidCostCenter:invalidCostCenter.slice(0,12),invalidFinancial:invalidFinancial.slice(0,12),paidWithoutDate:paidWithoutDate.slice(0,12),paidWithoutValue:paidWithoutValue.slice(0,12),amountMismatch:amountMismatch.slice(0,12),statusRepairs:statusRepairs.slice(0,12)},safeguards:{payablesWritten:0,syntheticTouched:0,budgetAppropriationInferred:false}}));if(!ready)process.exitCode=2;