import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";
type J=Record<string,unknown>;type Stage={koper_id:string;payload:unknown};
const obj=(v:unknown):J=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:{};
const num=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:typeof v==="string"&&Number.isFinite(Number(v))?Number(v):0;
async function all<T>(){const out:T[]=[];for(let o=0;;o+=1000){const rows=await requestSupabase<T[]>("koper_staging_records",{query:new URLSearchParams({select:"koper_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.bill_resolution",sync_state:"eq.present",order:"koper_id.asc",limit:"1000",offset:String(o)}),timeoutMs:30000});out.push(...rows);if(rows.length<1000)return out}}
function bump(map:Record<string,{count:number;value:number}>,key:string,value:number){const x=map[key]??{count:0,value:0};x.count++;x.value+=value;map[key]=x;}
const rows=await all<Stage>();const valid=rows.filter(r=>Number(obj(r.payload).version??0)>=2);
const byStatus:Record<string,{count:number;value:number}>={},byRoute:Record<string,{count:number;value:number}>={},byVersion:Record<string,{count:number;value:number}>={},byMethod:Record<string,{count:number;value:number}>={},unresolvedByRoute:Record<string,{count:number;value:number}>={};
const unresolvedExamples:J[]=[];let allocatedTotal=0,allocationMismatch=0,withWbs=0,withService=0;
for(const row of valid){const p=obj(row.payload),value=num(p.billValue),status=String(p.status??"none"),route=String(p.route??"none"),version=String(p.version??"none");bump(byStatus,status,value);bump(byRoute,route,value);bump(byVersion,version,value);const allocations=Array.isArray(p.allocations)?p.allocations.map(obj):[];const methods=[...new Set(allocations.map(a=>String(a.method??"none")))];for(const method of methods)bump(byMethod,method,value);if(Array.isArray(p.wbsCodes)&&p.wbsCodes.length)withWbs++;if(Array.isArray(p.serviceSourceIds)&&p.serviceSourceIds.length)withService++;if(allocations.length){const sum=allocations.reduce((a,x)=>a+num(x.amount),0);allocatedTotal+=sum;if(Math.abs(sum-value)>0.02)allocationMismatch++;}if(status==="unresolved"){bump(unresolvedByRoute,route,value);if(unresolvedExamples.length<80){const ids=obj(p.ids);unresolvedExamples.push({billId:row.koper_id,value,route,origin:p.originName??null,invoiceId:ids.invoiceId??null,receiptId:ids.receiptId??null,releaseId:ids.releaseId??null,stageReleaseId:ids.stageReleaseId??null,buildMonitoringId:ids.buildMonitoringId??null});}}}
console.log("KOPER_NATIVE_PAYABLE_MATRIX_V4",JSON.stringify({totalNative:3838,validRows:valid.length,remaining:3838-valid.length,coveragePct:Math.round(valid.length/3838*10000)/100,byStatus,byRoute,byVersion,byMethod,unresolvedByRoute,withService,withWbs,allocatedTotal:Math.round(allocatedTotal*100)/100,allocationMismatch,unresolvedExamples}));
await new Promise(r=>setTimeout(r,1200));
