import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";
type S={koper_id:string;koper_parent_id:string|null;payload:any}; type O={source_id:string|null,supplier_id:string,project_id:string,order_number:string}; type Sup={id:string,source_id:string|null,legal_name:string,tax_id:string|null};
async function all<T>(table:string,q:Record<string,string>){const out:T[]=[];for(let o=0;;o+=1000){const rows=await requestSupabase<T[]>(table,{query:new URLSearchParams({...q,limit:"1000",offset:String(o)})});out.push(...rows);if(rows.length<1000)return out}}
const obj=(v:any)=>v&&typeof v==="object"?v:{};const ids=(v:any,k:string)=>Array.isArray(v)?v.flatMap(x=>{const z=obj(x)[k];return z===null||z===undefined?[]:[String(z)]}):[];
const [entries,invoices,orders,sups]=await Promise.all([
 all<S>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.stock_entry",sync_state:"eq.present",order:"koper_id.asc"}),
 all<S>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.xml_invoice",sync_state:"eq.present",order:"koper_id.asc"}),
 all<O>("procurement_purchase_orders",{select:"source_id,supplier_id,project_id,order_number",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper",order:"source_id.asc"}),
 all<Sup>("suppliers",{select:"id,source_id,legal_name,tax_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper",order:"source_id.asc"})]);
const invById=new Map(invoices.map(x=>[x.koper_id,x]));const orderBySource=new Map(orders.flatMap(o=>o.source_id?[[o.source_id,o] as const]:[]));const supById=new Map(sups.map(s=>[s.id,s]));
for(const origin of ["620","621"]){const es=entries.filter(e=>String(obj(e.payload).originId??"")===origin);const evidence=es.map(e=>{const p=obj(e.payload);const invs=(Array.isArray(p.invoiceIds)?p.invoiceIds:[]).map(String).map(i=>invById.get(i)).filter(Boolean) as S[];const sourceOrders=new Set<string>();for(const x of (Array.isArray(p.purchaseOrderIds)?p.purchaseOrderIds:[]))sourceOrders.add(String(x));for(const inv of invs)for(const x of ids(obj(inv.payload).purchaseOrders,"purchaseOrderId"))sourceOrders.add(x);const os=[...sourceOrders].map(x=>orderBySource.get(x)).filter(Boolean) as O[];return {entryId:e.koper_id,invoiceIds:invs.map(i=>i.koper_id),invoiceNumbers:invs.map(i=>obj(i.payload).invoiceNumber),sourceOrders:[...sourceOrders],nativeOrders:os.map(o=>({source:o.source_id,number:o.order_number,project:o.project_id,supplier:supById.get(o.supplier_id)??{id:o.supplier_id}}))}});console.log("KOPER_ORIGIN_620_621",JSON.stringify({ok:true,readOnly:true,origin,entryCount:es.length,evidence}));}