import { createHash } from "node:crypto";
import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";
type J=Record<string,unknown>;type S={koper_id:string;koper_parent_id:string|null;payload:unknown};type O={id:string;source_id:string|null;supplier_id:string;project_id:string;order_number:string};type Sup={id:string;source_id:string|null;legal_name:string;trade_name:string|null;tax_id:string|null};
const obj=(v:unknown):J=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:{};const id=(v:unknown):string|null=>typeof v==="string"||typeof v==="number"?(String(v).trim()||null):null;const arr=(v:unknown):J[]=>Array.isArray(v)?v.map(obj):[];const ids=(v:unknown,k:string)=>[...new Set(arr(v).flatMap(r=>{const x=id(r[k]);return x?[x]:[]}))];
function stable(seed:string){const b=Buffer.from(createHash("sha256").update(seed).digest("hex").slice(0,32),"hex");b[6]=((b[6]??0)&15)|80;b[8]=((b[8]??0)&63)|128;const h=b.toString("hex");return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`}
async function all<T>(t:string,q:Record<string,string>){const out:T[]=[];for(let o=0;;o+=1000){const p=await requestSupabase<T[]>(t,{query:new URLSearchParams({...q,limit:"1000",offset:String(o)})});out.push(...p);if(p.length<1000)return out}}
function invoiceIds(p:J){const nested=ids(p.invoices,"invoiceId");if(nested.length)return nested;return Array.isArray(p.invoiceIds)?[...new Set(p.invoiceIds.flatMap(x=>id(x)?[id(x)!]:[]))]:[]}
function primitiveSummary(v:unknown,depth=0):unknown{if(depth>3)return "[depth]";if(Array.isArray(v))return v.slice(0,30).map(x=>primitiveSummary(x,depth+1));if(typeof v==="object"&&v!==null){const out:J={};for(const [k,x] of Object.entries(v as J))out[k]=primitiveSummary(x,depth+1);return out}return v}
await import("./index.js");
const [invs,entries,items,products,orders,sups,existing]=await Promise.all([
all<S>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.xml_invoice",sync_state:"eq.present",order:"koper_id.asc"}),
all<S>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.stock_entry",sync_state:"eq.present",order:"koper_id.asc"}),
all<S>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.stock_entry_item",sync_state:"eq.present",order:"koper_parent_id.asc,koper_id.asc"}),
all<S>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.xml_invoice_product",sync_state:"eq.present",order:"koper_parent_id.asc,koper_id.asc"}),
all<O>("procurement_purchase_orders",{select:"id,source_id,supplier_id,project_id,order_number",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper",order:"source_id.asc"}),
all<Sup>("suppliers",{select:"id,source_id,legal_name,trade_name,tax_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper",order:"source_id.asc"}),
all<{id:string}>("finance_electronic_invoices",{select:"id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),]);
const existingIds=new Set(existing.map(x=>x.id)), orderBySource=new Map(orders.flatMap(o=>o.source_id?[[o.source_id,o] as const]:[])), supById=new Map(sups.map(s=>[s.id,s]));
const entryById=new Map(entries.map(e=>[e.koper_id,e]));const itemsByEntry=new Map<string,S[]>();for(const x of items)if(x.koper_parent_id)itemsByEntry.set(x.koper_parent_id,[...(itemsByEntry.get(x.koper_parent_id)??[]),x]);const productsByInv=new Map<string,S[]>();for(const x of products)if(x.koper_parent_id)productsByInv.set(x.koper_parent_id,[...(productsByInv.get(x.koper_parent_id)??[]),x]);const entryIdsByInv=new Map<string,Set<string>>();for(const x of items){if(!x.koper_parent_id)continue;for(const iid of invoiceIds(obj(x.payload))){const set=entryIdsByInv.get(iid)??new Set<string>();set.add(x.koper_parent_id);entryIdsByInv.set(iid,set)}}
const knownPlaceProject=new Map<string,Set<string>>();for(const inv of invs){const p=obj(inv.payload), src=ids(p.purchaseOrders,"purchaseOrderId"), os=[...new Map(src.flatMap(s=>{const o=orderBySource.get(s);return o?[[o.id,o] as const]:[]})).values()];const ps=[...new Set(os.map(o=>o.project_id))];if(ps.length!==1)continue;for(const eid of entryIdsByInv.get(inv.koper_id)??[]){const ep=obj(entryById.get(eid)?.payload);for(const k of ["placeEntryId","placeId","stockPlaceId","localStockId","constructionId","projectId"]){const v=id(ep[k]);if(v){const set=knownPlaceProject.get(`${k}:${v}`)??new Set<string>();set.add(ps[0]!);knownPlaceProject.set(`${k}:${v}`,set)}}}}
const final:any[]=[];for(const inv of invs){if(existingIds.has(stable(`elos:koper:electronic-invoice:${inv.koper_id}`)))continue;const p=obj(inv.payload);const sourceOrders=new Set(ids(p.purchaseOrders,"purchaseOrderId"));const eids=[...(entryIdsByInv.get(inv.koper_id)??[])];for(const eid of eids)for(const si of itemsByEntry.get(eid)??[]){const sp=obj(si.payload);for(const key of ["candidatePurchaseOrderIds","purchaseOrderIds"]){if(Array.isArray(sp[key]))for(const x of sp[key] as unknown[])if(id(x))sourceOrders.add(id(x)!)}const po=id(sp.purchaseOrderId);if(po)sourceOrders.add(po)}const os=[...new Map([...sourceOrders].flatMap(s=>{const o=orderBySource.get(s);return o?[[o.id,o] as const]:[]})).values()];const projectIds=[...new Set(os.map(o=>o.project_id))], supplierIds=[...new Set(os.map(o=>o.supplier_id))];if(projectIds.length===1&&supplierIds.length===1)continue;
const entryDetails=eids.map(eid=>{const ep=obj(entryById.get(eid)?.payload);const placeEvidence=Object.entries(ep).flatMap(([k,v])=>{const val=id(v);if(!val)return[];const set=knownPlaceProject.get(`${k}:${val}`);return set?[{key:k,value:val,knownProjects:[...set]}]:[]});return {entryId:eid,entryPayload:primitiveSummary(ep),placeEvidence,items:(itemsByEntry.get(eid)??[]).map(si=>({itemId:si.koper_id,payload:primitiveSummary(si.payload)}))}});
final.push({invoiceId:inv.koper_id,invoicePayload:primitiveSummary(p),invoiceProducts:(productsByInv.get(inv.koper_id)??[]).map(pr=>({id:pr.koper_id,payload:primitiveSummary(pr.payload)})),sourceOrders:[...sourceOrders],nativeOrders:os.map(o=>({sourceId:o.source_id,orderNumber:o.order_number,projectId:o.project_id,supplier:supById.get(o.supplier_id)??{id:o.supplier_id}})),entryDetails});}
console.log("KOPER_NFE_IDENTITY_MISSING_14",JSON.stringify({ok:true,readOnly:true,count:final.length,records:final}));