import { createHash } from "node:crypto";
import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";
type J=Record<string,unknown>;type Stage={koper_id:string;koper_parent_id:string|null;payload:unknown};type Order={id:string;source_id:string|null};type OI={id:string;order_id:string;input_id:string;cost_center_service_id:string|null;source_id:string|null};type Input={id:string;source_id:string|null};type Service={id:string;source_id:string|null;description:string};type Budget={id:string};type BI={id:string;budget_id:string;service_id:string|null;code:string|null};
const obj=(v:unknown):J=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:{};const arr=(v:unknown):J[]=>Array.isArray(v)?v.map(obj):[];const id=(v:unknown):string|null=>(typeof v==="string"||typeof v==="number")&&String(v).trim()?String(v).trim():null;const ids=(v:unknown)=>Array.isArray(v)?[...new Set(v.flatMap(x=>id(x)?[id(x)!]:[]))]:[];const uniq=<T>(v:T[])=>[...new Set(v)];const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
const nativeProductIds=(p:J)=>uniq([id(p.mainProductId),id(p.productId),id(p.inputId),id(p.genericProdSeq)].filter((x):x is string=>!!x));const invoiceIds=(p:J)=>{const nested=arr(p.invoices).flatMap(x=>{const y=id(x.invoiceId);return y?[y]:[]});return nested.length?uniq(nested):ids(p.invoiceIds)};const orderSources=(p:J)=>uniq(arr(p.purchaseOrders).flatMap(x=>{const y=id(x.purchaseOrderId??x.purchase_order_id);return y?[y]:[]}));
async function all<T>(t:string,q:Record<string,string>){const out:T[]=[];for(let o=0;;o+=1000){const rows=await requestSupabase<T[]>(t,{query:new URLSearchParams({...q,limit:"1000",offset:String(o)}),timeoutMs:30000});out.push(...rows);if(rows.length<1000)return out}}
await import("./index.js");
const [resolutions,invoices,stockItems,orders,ois,inputs,services,budgets,budgetItems]=await Promise.all([
 all<Stage>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.bill_resolution",sync_state:"eq.present"}),all<Stage>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.xml_invoice",sync_state:"eq.present"}),all<Stage>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.stock_entry_item",sync_state:"eq.present"}),all<Order>("procurement_purchase_orders",{select:"id,source_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper"}),all<OI>("procurement_purchase_order_items",{select:"id,order_id,input_id,cost_center_service_id,source_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper"}),all<Input>("engineering_inputs",{select:"id,source_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper"}),all<Service>("engineering_services",{select:"id,source_id,description",company_id:`eq.${env.BOSSA_COMPANY_ID}`,status:"eq.active"}),all<Budget>("engineering_budgets",{select:"id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,status:"eq.approved"}),all<BI>("engineering_budget_items",{select:"id,budget_id,service_id,code",company_id:`eq.${env.BOSSA_COMPANY_ID}`,status:"eq.active"})]);
const invById=new Map(invoices.map(x=>[x.koper_id,x]));const stockByInv=new Map<string,Stage[]>();for(const x of stockItems)for(const iid of invoiceIds(obj(x.payload)))stockByInv.set(iid,[...(stockByInv.get(iid)??[]),x]);const orderBySource=new Map(orders.flatMap(x=>x.source_id?[[x.source_id,x] as const]:[]));const oiByOrder=new Map<string,OI[]>();for(const x of ois)oiByOrder.set(x.order_id,[...(oiByOrder.get(x.order_id)??[]),x]);const inputBySource=new Map(inputs.flatMap(x=>x.source_id?[[x.source_id,x] as const]:[]));const serviceById=new Map(services.map(x=>[x.id,x]));const approved=new Set(budgets.map(x=>x.id));const wbsByService=new Map<string,BI[]>();for(const b of budgetItems)if(b.service_id&&b.code&&approved.has(b.budget_id))wbsByService.set(b.service_id,[...(wbsByService.get(b.service_id)??[]),b]);const uniqueWbs=(sid:string)=>{const rows=wbsByService.get(sid)??[],codes=uniq(rows.flatMap(x=>x.code?[x.code]:[]));return codes.length===1?rows.find(x=>x.code===codes[0])??null:null};
function resolveStock(stock:Stage,orderId:string){const sources=nativeProductIds(obj(stock.payload));const inputIds=new Set(sources.flatMap(s=>{const i=inputBySource.get(s);return i?[i.id]:[]}));const candidates=(oiByOrder.get(orderId)??[]).filter(oi=>inputIds.has(oi.input_id)&&!!oi.cost_center_service_id);return candidates.length===1?candidates[0]!:null;}
const targets=resolutions.filter(r=>{const p=obj(r.payload);return Number(p.version??0)>=2&&p.status==="unresolved"&&p.route==="invoice";});let upgraded=0,skippedNoInvoice=0,skippedOrder=0,skippedStock=0,skippedMapping=0,skippedMultiService=0;const examples:J[]=[];
for(const r of targets){const p=obj(r.payload),bid=obj(p.ids),invoiceId=id(bid.invoiceId),billValue=Number(p.billValue??0);if(!invoiceId||!Number.isFinite(billValue)||billValue<=0){skippedNoInvoice++;continue}const inv=invById.get(invoiceId);if(!inv){skippedNoInvoice++;continue}const nativeOrders=orderSources(obj(inv.payload)).flatMap(s=>{const o=orderBySource.get(s);return o?[o]:[]});if(nativeOrders.length!==1){skippedOrder++;continue}const order=nativeOrders[0]!,stocks=stockByInv.get(invoiceId)??[];if(!stocks.length){skippedStock++;continue}const mapped=stocks.map(s=>({stock:s,oi:resolveStock(s,order.id)}));if(mapped.some(x=>!x.oi)){skippedMapping++;continue}const oisResolved=mapped.map(x=>x.oi!);const serviceIds=uniq(oisResolved.flatMap(x=>x.cost_center_service_id?[x.cost_center_service_id]:[]));if(serviceIds.length!==1){skippedMultiService++;continue}const serviceId=serviceIds[0]!,service=serviceById.get(serviceId);if(!service){skippedMapping++;continue}const w=uniqueWbs(serviceId);const allocation={serviceId,serviceSourceId:service.source_id,serviceName:service.description,budgetItemId:w?.id??null,wbsCode:w?.code??null,amount:Math.round(billValue*100)/100,method:"koper_nfe_stock_entry_single_service",evidence:{invoiceId,orderSourceIds:orderSources(obj(inv.payload)),stockEntryItemIds:stocks.map(x=>x.koper_id),orderItemIds:uniq(oisResolved.map(x=>x.id)),allStockItemsMapped:true,singleServiceAcrossInvoice:true}};const next={...p,version:5,status:"exact_allocated",serviceSourceIds:service.source_id?[service.source_id]:[],wbsCodes:w?.code?[w.code]:[],allocations:[allocation],projectEvidence:{...obj(p.projectEvidence),nfeFallback:"stock_entry_single_service",nativeOrderSourceIds:orderSources(obj(inv.payload))}};const now=new Date().toISOString();await requestSupabase("koper_staging_records",{method:"POST",body:[{company_id:env.BOSSA_COMPANY_ID,source:"koper",entity:"bill_resolution",koper_id:r.koper_id,koper_parent_id:r.koper_parent_id,payload:next,payload_hash:hash(next),first_seen_at:now,last_seen_at:now,processing_status:"processed",processing_error:null,mapping_version:5,sync_state:"present",elos_id:null,updated_at:now}],prefer:"resolution=merge-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"company_id,source,entity,koper_id"})});upgraded++;if(examples.length<20)examples.push({billId:r.koper_id,invoiceId,stockItems:stocks.length,orderItems:uniq(oisResolved.map(x=>x.id)),serviceSourceId:service.source_id,wbs:w?.code??null,billValue});}
console.log("KOPER_NFE_STOCK_SAFE_ENHANCER",JSON.stringify({targets:targets.length,upgraded,skippedNoInvoice,skippedOrder,skippedStock,skippedMapping,skippedMultiService,examples}));await new Promise(r=>setTimeout(r,1200));
