import { createHash } from 'node:crypto';
import { gzipSync } from 'node:zlib';
import { env } from './config/env.js';
import { requestSupabase } from './elos/supabase.js';
type J=Record<string,unknown>; type S={koper_id:string;koper_parent_id:string|null;payload:unknown}; type E={source_id:string|null;code:string|null;description:string|null};
const o=(v:unknown):J=>typeof v==='object'&&v!==null&&!Array.isArray(v)?v as J:{}; const a=(v:unknown):J[]=>Array.isArray(v)?v.map(o):[]; const t=(v:unknown)=>v==null?'':String(v); const f=(...v:unknown[])=>v.find(x=>x!=null&&x!=='')??''; const q=(v:unknown)=>`"${t(v).replaceAll('"','""').replace(/[\r\n]+/g,' ')}"`;
async function st(e:string){const z:S[]=[];for(let n=0;;n+=1000){const r=await requestSupabase<S[]>('koper_staging_records',{query:new URLSearchParams({select:'koper_id,koper_parent_id,payload',company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:'eq.koper',entity:`eq.${e}`,sync_state:'eq.present',order:'koper_id.asc',limit:'1000',offset:String(n)}),timeoutMs:30000});z.push(...r);if(r.length<1000)return z}}
async function es(){const z:E[]=[];for(let n=0;;n+=1000){const r=await requestSupabase<E[]>('engineering_services',{query:new URLSearchParams({select:'source_id,code,description',company_id:`eq.${env.BOSSA_COMPANY_ID}`,limit:'1000',offset:String(n)}),timeoutMs:30000});z.push(...r);if(r.length<1000)return z}}
const [bs,rs,ds,ss]=await Promise.all([st('bill_to_pay'),st('bill_resolution'),st('bill_detail_enrichment'),es()]); const rm=new Map(rs.map(x=>[x.koper_id,o(x.payload)])),dm=new Map(ds.map(x=>[x.koper_id,o(x.payload)])),sm=new Map(ss.filter(x=>x.source_id).map(x=>[String(x.source_id),x])); const H=['Bill ID','BillToPay ID','Fornecedor ID','Fornecedor','Valor título','Vencimento','Pago?','Data pagamento','Valor pago','Origem','Status resolução','Rota','Método','Serviço Koper ID','Código serviço','Serviço','WBS','Centro custo ID','Cobertura detalhe']; const L=[H.map(q).join(',')]; for(const x of bs){const b=o(x.payload),r=rm.get(x.koper_id)??{},d=dm.get(x.koper_id)??{},al=a(r.allocations),ids=(Array.isArray(r.serviceSourceIds)?r.serviceSourceIds:al.map(v=>v.serviceSourceId)).filter(Boolean).map(String),us=[...new Set(ids)],sr=us.map(id=>sm.get(id)).filter(Boolean) as E[],wb=[...new Set((Array.isArray(r.wbsCodes)?r.wbsCodes:al.map(v=>f(v.wbsCode,v.budgetItemCode,v.itemReference))).filter(Boolean).map(String))],me=[...new Set(al.map(v=>t(v.method)).filter(Boolean))];const V=[x.koper_id,f(b.billToPayId,x.koper_parent_id),d.supplierId,d.supplierName,b.billValue,b.dueDate,b.isPaid,b.paymentDate,b.paymentValue,b.originName,r.status,r.route,me.join(' | '),us.join(' | '),sr.map(v=>v.code??'').filter(Boolean).join(' | '),sr.map(v=>v.description??'').filter(Boolean).join(' | '),wb.join(' | '),d.costCenterId,dm.has(x.koper_id)?'Enriquecido':'Pendente enriquecimento'];L.push(V.map(q).join(','));}
const raw=Buffer.from('\uFEFF'+L.join('\r\n'),'utf8'), gz=gzipSync(raw,{level:9}), p=gz.toString('base64'), cs=20000, total=Math.ceil(p.length/cs); console.log('KOPER_TRANSFER_META',JSON.stringify({bills:bs.length,resolutions:rs.length,details:ds.length,services:ss.length,csvBytes:raw.length,gzipBytes:gz.length,base64Chars:p.length,chunks:total,sha256:createHash('sha256').update(raw).digest('hex'),gzipSha256:createHash('sha256').update(gz).digest('hex')})); for(let i=0;i<total;i++){const part=p.slice(i*cs,(i+1)*cs),hash=createHash('sha256').update(part).digest('hex');console.log(`KOPER_TRANSFER_CHUNK ${String(i+1).padStart(3,'0')}/${String(total).padStart(3,'0')} ${part} HASH ${hash}`)} await new Promise(r=>setTimeout(r,1000));