import type { Response } from "playwright-core";
import { performKoperLogin } from "./auth/koper-auto-login.js";
import { withBrowserless } from "./browser/browserless.js";
import { selectFlow } from "./diagnostics/collect-flow-stock-requests.js";
import { isAllowedFlowSwitch } from "./diagnostics/inspect-koper-engineering.js";

type J=Record<string,unknown>;
const obj=(v:unknown):J=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:{};
function ev(v:unknown,prefix="",depth=0):Array<{path:string,value:unknown}>{if(depth>9)return[];if(Array.isArray(v))return v.flatMap((x,i)=>ev(x,`${prefix}[${i}]`,depth+1));if(typeof v!=="object"||v===null)return[];const r=obj(v),out:Array<{path:string,value:unknown}>=[];for(const[k,x]of Object.entries(r)){const p=prefix?`${prefix}.${k}`:k;if(x===null||typeof x==="string"||typeof x==="number"||typeof x==="boolean"){if(/service|item|reference|value|amount|quantity|price|total|percent|monitor|cost|order/i.test(k))out.push({path:p,value:x});}else out.push(...ev(x,p,depth+1));}return out;}
const ids=(process.env.KOPER_SERVICE_ORDER_PROBE_IDS??"2345").split(",").map(x=>x.trim()).filter(Boolean);
const result=await withBrowserless(async({page})=>{const login=await performKoperLogin(page);if(!login.authenticated)throw new Error(login.message??"LOGIN");let blockedWrites=0;await page.route("**/*",async route=>{const r=route.request();try{const u=new URL(r.url());const koper=u.hostname==="koper.com.br"||u.hostname.endsWith(".koper.com.br");if(koper&&!["GET","HEAD","OPTIONS"].includes(r.method())&&!isAllowedFlowSwitch(u,r.method(),r.postData())){blockedWrites++;await route.abort("blockedbyclient");return;}}catch{}await route.continue();});if(!await selectFlow(page))throw new Error("FLOW");const seedP=page.waitForResponse((response:Response)=>{try{const u=new URL(response.url());return response.request().method()==="GET"&&u.hostname==="api.koper.com.br"&&u.pathname==="/financial/v1/bills_to_pay"&&!u.searchParams.has("billId");}catch{return false;}},{timeout:20000}).catch(()=>null);await page.goto("https://app.koper.com.br/financeiro/contas_pagar",{waitUntil:"domcontentloaded",timeout:15000}).catch(()=>undefined);const seed=await seedP;if(!seed)throw new Error("SEED");const sh=seed.request().headers(),headers:Record<string,string>={};for(const k of["accept","origin","referer","x-accesstoken","x-koper"])if(sh[k])headers[k]=sh[k];const rows=[];for(const orderId of ids){const u=new URL("https://api.koper.com.br/purchase/v1/service_order");u.searchParams.set("orderId",orderId);u.searchParams.set("cb",String(Date.now()));const r=await page.request.get(u.toString(),{headers,timeout:12000});const body=await r.json().catch(()=>null);rows.push({orderId,status:r.status(),evidence:ev(body).slice(0,300)});}return{blockedWrites,rows};},{sessionTimeoutMs:60000});
console.log("KOPER_SERVICE_ORDER_ALLOCATION",JSON.stringify(result));
await new Promise(r=>setTimeout(r,1200));
