import type { Response } from "playwright-core";
import { performKoperLogin } from "./auth/koper-auto-login.js";
import { withBrowserless } from "./browser/browserless.js";
import { selectFlow } from "./diagnostics/collect-flow-stock-requests.js";
import { isAllowedFlowSwitch } from "./diagnostics/inspect-koper-engineering.js";
type J=Record<string,unknown>;
const obj=(v:unknown):J=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:{};
function slim(v:unknown,depth=0):unknown{if(depth>6)return undefined;if(Array.isArray(v))return v.slice(0,20).map(x=>slim(x,depth+1));if(typeof v!=="object"||v===null)return v;const r=obj(v),out:J={};for(const[k,x]of Object.entries(r)){if(/receipt|purchase|service|order|item|reference|value|amount|quantity|price|total|monitor|cost|bill/i.test(k)){if(x&&typeof x==="object")out[k]=slim(x,depth+1);else out[k]=x;}else if(x&&typeof x==="object"){const s=slim(x,depth+1);if(s&&typeof s==="object"&&Object.keys(s as J).length)out[k]=s;}}return out;}
const receiptIds=(process.env.KOPER_RECEIPT_PROBE_IDS??"8880,8888").split(",").map(x=>x.trim()).filter(Boolean);
const purchaseIds=(process.env.KOPER_PURCHASE_PROBE_IDS??"9375,9383").split(",").map(x=>x.trim()).filter(Boolean);
const result=await withBrowserless(async({page})=>{const login=await performKoperLogin(page);if(!login.authenticated)throw new Error(login.message??"LOGIN");let blockedWrites=0;await page.route("**/*",async route=>{const r=route.request();try{const u=new URL(r.url());const koper=u.hostname==="koper.com.br"||u.hostname.endsWith(".koper.com.br");if(koper&&!["GET","HEAD","OPTIONS"].includes(r.method())&&!isAllowedFlowSwitch(u,r.method(),r.postData())){blockedWrites++;await route.abort("blockedbyclient");return;}}catch{}await route.continue();});if(!await selectFlow(page))throw new Error("FLOW");const seedP=page.waitForResponse((response:Response)=>{try{const u=new URL(response.url());return response.request().method()==="GET"&&u.hostname==="api.koper.com.br"&&u.pathname==="/financial/v1/bills_to_pay"&&!u.searchParams.has("billId");}catch{return false;}},{timeout:20000}).catch(()=>null);await page.goto("https://app.koper.com.br/financeiro/contas_pagar",{waitUntil:"domcontentloaded",timeout:15000}).catch(()=>undefined);const seed=await seedP;if(!seed)throw new Error("SEED");const sh=seed.request().headers(),headers:Record<string,string>={};for(const k of["accept","origin","referer","x-accesstoken","x-koper"])if(sh[k])headers[k]=sh[k];const fetch=async(path:string,key:string,val:string)=>{const u=new URL(`https://api.koper.com.br${path}`);u.searchParams.set(key,val);u.searchParams.set("cb",String(Date.now()));const r=await page.request.get(u.toString(),{headers,timeout:12000});return{status:r.status(),body:slim(await r.json().catch(()=>null))}};const receipts=[];for(const receiptId of receiptIds)receipts.push({receiptId,...await fetch("/financial/v1/receipt","receiptId",receiptId)});const purchases=[];for(const purchaseId of purchaseIds)purchases.push({purchaseId,...await fetch("/purchase/v1/purchase","purchaseId",purchaseId)});return{blockedWrites,receipts,purchases};},{sessionTimeoutMs:60000});
console.log("KOPER_RECEIPT_PURCHASE_ALLOCATION",JSON.stringify(result));
await new Promise(r=>setTimeout(r,1200));
