import type { Response } from "playwright-core";
import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";
import { performKoperLogin } from "./auth/koper-auto-login.js";
import { withBrowserless } from "./browser/browserless.js";
import { isAllowedFlowSwitch } from "./diagnostics/inspect-koper-engineering.js";
import { selectFlow } from "./diagnostics/collect-flow-stock-requests.js";
type J=Record<string,unknown>;type Stage={koper_id:string;payload:unknown};
const obj=(v:unknown):J|null=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:null;
const scal=(v:unknown)=>v===null||["string","number","boolean"].includes(typeof v);
function scan(v:unknown,prefix="",depth=0):Array<{path:string,value:unknown}>{if(depth>12)return[];if(Array.isArray(v))return v.slice(0,100).flatMap((x,i)=>scan(x,`${prefix}[${i}]`,depth+1));const r=obj(v);if(!r)return[];const out:Array<{path:string,value:unknown}>=[];for(const[k,x]of Object.entries(r)){const p=prefix?`${prefix}.${k}`:k;if(scal(x)){if(/id|code|status|value|amount|contract|measure|service|stage|cost|center|build|monitor|supplier|bill|pay|order|receipt|invoice|item|release|quantity|price|percent|total|reference/i.test(k))out.push({path:p,value:x});}else out.push(...scan(x,p,depth+1));}return out;}
async function all(){const out:Stage[]=[];for(let o=0;;o+=1000){const rows=await requestSupabase<Stage[]>("koper_staging_records",{query:new URLSearchParams({select:"koper_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.bill_resolution",sync_state:"eq.present",limit:"1000",offset:String(o)}),timeoutMs:30000});out.push(...rows);if(rows.length<1000)return out;}}
console.log("KOPER_MEASUREMENT_CONTRACT_FINANCIAL_LINK_PROBE_START",JSON.stringify({companyId:env.BOSSA_COMPANY_ID}));
const rows=(await all()).filter(r=>{const p=obj(r.payload);return p?.route==="measurement"&&p?.status==="unresolved";});
console.log("KOPER_MEASUREMENT_CONTRACT_FINANCIAL_LINK_PROBE_TARGETS",JSON.stringify({targetCount:rows.length,billIds:rows.map(r=>r.koper_id)}));
try{const result=await withBrowserless(async({page})=>{const login=await performKoperLogin(page);if(!login.authenticated)return{ok:false,message:login.message};let blockedWrites=0;await page.route("**/*",async route=>{const q=route.request();try{const u=new URL(q.url());if((u.hostname==="koper.com.br"||u.hostname.endsWith(".koper.com.br"))&&!["GET","HEAD","OPTIONS"].includes(q.method())&&!isAllowedFlowSwitch(u,q.method(),q.postData())){blockedWrites++;await route.abort("blockedbyclient");return;}}catch{}await route.continue();});if(!await selectFlow(page))return{ok:false,message:"FLOW_NOT_SELECTED"};const seedP=page.waitForResponse((response:Response)=>{try{const u=new URL(response.url());return response.request().method()==="GET"&&u.hostname==="api.koper.com.br"&&u.pathname==="/engineering/v1/contract";}catch{return false;}},{timeout:20000}).catch(()=>null);await page.goto("https://app.koper.com.br/engenharia/contratos",{waitUntil:"domcontentloaded",timeout:12000}).catch(()=>undefined);const seed=await seedP;if(!seed)return{ok:false,message:"CONTRACT_SEED_NOT_FOUND",blockedWrites};const sh=seed.request().headers(),headers:Record<string,string>={};for(const k of["accept","origin","referer","x-accesstoken","x-koper"])if(sh[k])headers[k]=sh[k];
const details=[];for(const row of rows){const p=obj(row.payload)??{},origin=obj(p.origin)??{},ids=[p.releaseId,p.stageReleaseId,origin.fnc_release_id,origin.fnc_stage_release_id].filter(x=>x!==null&&x!==undefined).map(String);const uniq=[...new Set(ids)];const measurements=[];const contractIds=new Set<string>();for(const id of uniq){const u=new URL("https://api.koper.com.br/engineering/v1/build_measurement");u.searchParams.set("measurementId",id);u.searchParams.set("cb",String(Date.now()));const r=await page.request.get(u.toString(),{headers,timeout:8000});const body=await r.json().catch(()=>null);const ev=scan(body);for(const e of ev)if(/contractId$/i.test(e.path)&&e.value!=null)contractIds.add(String(e.value));measurements.push({candidateId:id,status:r.status(),evidence:ev.slice(0,400)});}const contracts=[];for(const cid of contractIds){for(const suffix of["contract","contract_measurement","contract_service"]){const u=new URL(`https://api.koper.com.br/engineering/v1/${suffix}`);u.searchParams.set("contractId",cid);if(suffix==="contract")u.searchParams.set("measurement","yes");u.searchParams.set("cb",String(Date.now()));const r=await page.request.get(u.toString(),{headers,timeout:10000});const body=await r.json().catch(()=>null);const ev=scan(body);const financial=ev.filter(e=>/release|stage|bill|pay|fnc|measurement|monitor|service|reference|contract/i.test(e.path));contracts.push({contractId:cid,endpoint:suffix,status:r.status(),evidence:financial.slice(0,1000)});}}details.push({billId:row.koper_id,billValue:p.billValue,releaseId:p.releaseId,stageReleaseId:p.stageReleaseId,projectEvidence:p.projectEvidence,measurements,contracts});}return{ok:true,readOnly:true,blockedWrites,targetCount:rows.length,details};},{sessionTimeoutMs:190_000});console.log("KOPER_MEASUREMENT_CONTRACT_FINANCIAL_LINK_PROBE",JSON.stringify(result));}catch(error:unknown){console.error("KOPER_MEASUREMENT_CONTRACT_FINANCIAL_LINK_PROBE_FAILED",JSON.stringify({message:error instanceof Error?error.message.slice(0,2000):"unknown"}));process.exitCode=1;}
