import type { Response } from "playwright-core";
import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";
import { performKoperLogin } from "./auth/koper-auto-login.js";
import { withBrowserless } from "./browser/browserless.js";
import { isAllowedFlowSwitch } from "./diagnostics/inspect-koper-engineering.js";
import { selectFlow } from "./diagnostics/collect-flow-stock-requests.js";
type J=Record<string,unknown>;type Stage={koper_id:string;payload:unknown};
const obj=(v:unknown):J=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:{};
async function all<T>(){const out:T[]=[];for(let o=0;;o+=1000){const rows=await requestSupabase<T[]>("koper_staging_records",{query:new URLSearchParams({select:"koper_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.bill_resolution",sync_state:"eq.present",order:"koper_id.asc",limit:"1000",offset:String(o)}),timeoutMs:30000});out.push(...rows);if(rows.length<1000)return out}}
function supplierEvidence(v:unknown,prefix="",depth=0):Array<{path:string,value:unknown}>{if(depth>7)return[];if(Array.isArray(v))return v.slice(0,20).flatMap((x,i)=>supplierEvidence(x,`${prefix}[${i}]`,depth+1));const r=obj(v),out:Array<{path:string,value:unknown}>=[];for(const[k,x]of Object.entries(r)){const p=prefix?`${prefix}.${k}`:k;if(/supplier|provider|vendor|creditor|beneficiary|favorecido|fornecedor|person|company/i.test(k)){if(x===null||typeof x==="string"||typeof x==="number"||typeof x==="boolean")out.push({path:p,value:x});else out.push(...supplierEvidence(x,p,depth+1));}else if(x&&(Array.isArray(x)||(typeof x==="object"&&x!==null)))out.push(...supplierEvidence(x,p,depth+1));}return out;}
const resolutions=await all<Stage>();const sample:Stage[]=[];const perRoute=new Map<string,number>();for(const r of resolutions){const p=obj(r.payload);if(Number(p.version??0)<2)continue;const route=String(p.route??"none");const n=perRoute.get(route)??0;if(n>=12)continue;perRoute.set(route,n+1);sample.push(r);}
try{const result=await withBrowserless(async({page})=>{const login=await performKoperLogin(page);if(!login.authenticated)return{ok:false,message:login.message};let blockedWrites=0;await page.route("**/*",async route=>{const req=route.request();try{const u=new URL(req.url());const koper=u.hostname==="koper.com.br"||u.hostname.endsWith(".koper.com.br");if(koper&&!["GET","HEAD","OPTIONS"].includes(req.method())&&!isAllowedFlowSwitch(u,req.method(),req.postData())){blockedWrites++;await route.abort("blockedbyclient");return;}}catch{}await route.continue();});if(!await selectFlow(page))return{ok:false,message:"FLOW_NOT_SELECTED",blockedWrites};const seedPromise=page.waitForResponse((response:Response)=>{try{const u=new URL(response.url());return response.request().method()==="GET"&&u.hostname==="api.koper.com.br"&&u.pathname==="/financial/v1/bills_to_pay"&&!u.searchParams.has("billId");}catch{return false;}},{timeout:20000}).catch(()=>null);await page.goto("https://app.koper.com.br/financeiro/contas_pagar",{waitUntil:"domcontentloaded",timeout:12000}).catch(()=>undefined);const seed=await seedPromise;if(!seed)return{ok:false,message:"LIST_SEED_NOT_FOUND",blockedWrites};const sh=seed.request().headers(),headers:Record<string,string>={};for(const k of["accept","origin","referer","x-accesstoken","x-koper"])if(sh[k])headers[k]=sh[k]!;const rows=[];for(const r of sample){const p=obj(r.payload),u=new URL("https://api.koper.com.br/financial/v1/bills_to_pay");u.searchParams.set("billId",r.koper_id);const rr=await page.request.get(u.toString(),{headers,timeout:8000}).catch(()=>null);const body=rr?await rr.json().catch(()=>null):null;rows.push({billId:r.koper_id,route:p.route??null,status:rr?.status()??0,evidence:supplierEvidence(body).slice(0,80)});}const pathStats:Record<string,{count:number;nonnull:number;sampleValues:unknown[]}>= {};for(const row of rows)for(const e of row.evidence){const s=pathStats[e.path]??{count:0,nonnull:0,sampleValues:[]};s.count++;if(e.value!==null&&e.value!=="")s.nonnull++;if(s.sampleValues.length<6&&!s.sampleValues.some(x=>String(x)===String(e.value)))s.sampleValues.push(e.value);pathStats[e.path]=s;}return{ok:true,readOnly:true,blockedWrites,sampleSize:rows.length,routeSamples:Object.fromEntries(perRoute),pathStats,rows};},{sessionTimeoutMs:190000});console.log("KOPER_NATIVE_PAYABLE_SUPPLIER_EVIDENCE",JSON.stringify(result));}catch(error:unknown){console.error("KOPER_NATIVE_PAYABLE_SUPPLIER_EVIDENCE_FAILED",JSON.stringify({message:error instanceof Error?error.message.slice(0,1200):"unknown",sampleSize:sample.length}));}
