import { createHash } from "node:crypto";
import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";

type Json=Record<string,unknown>; type Stage={koper_id:string;payload:unknown}; type Invoice={id:string;project_id:string;supplier_id:string;registry_number:string;invoice_number:string;invoice_total:number};
const object=(v:unknown):Json=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as Json:{}; const rows=(v:unknown):Json[]=>Array.isArray(v)?v.map(object):[];
const text=(v:unknown):string|null=>(typeof v==="string"||typeof v==="number")&&String(v).trim()?String(v).trim():null;
const numeric=(v:unknown):number|null=>typeof v==="number"&&Number.isFinite(v)?v:typeof v==="string"&&v.trim()&&Number.isFinite(Number(v))?Number(v):null;
const dateOnly=(v:unknown):string|null=>{const raw=text(v);if(!raw)return null;const p=new Date(raw.includes("T")?raw:raw.replace(" ","T"));return Number.isNaN(p.valueOf())?(/^\d{4}-\d{2}-\d{2}/.test(raw)?raw.slice(0,10):null):p.toISOString().slice(0,10)};
function uuid(seed:string){const b=Buffer.from(createHash("sha256").update(seed).digest("hex").slice(0,32),"hex");b[6]=((b[6]??0)&15)|80;b[8]=((b[8]??0)&63)|128;const h=b.toString("hex");return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
async function readAll<T>(table:string,query:Record<string,string>):Promise<T[]>{const out:T[]=[];for(let o=0;;o+=1000){const p=await requestSupabase<T[]>(table,{query:new URLSearchParams({...query,limit:"1000",offset:String(o)})});out.push(...p);if(p.length<1000)return out;}}
await import("./index.js");
try{
 const write=process.env.KOPER_PAYABLE_MISSING_ID_WRITE_ENABLED==="true";
 const [stages,invoices,actors,existing]=await Promise.all([
  readAll<Stage>("koper_staging_records",{select:"koper_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.xml_invoice",sync_state:"eq.present",order:"koper_id.asc"}),
  readAll<Invoice>("finance_electronic_invoices",{select:"id,project_id,supplier_id,registry_number,invoice_number,invoice_total",company_id:`eq.${env.BOSSA_COMPANY_ID}`}),
  requestSupabase<Array<{user_id:string}>>("company_memberships",{query:new URLSearchParams({select:"user_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,status:"eq.active",order:"created_at.asc",limit:"1"})}),
  readAll<{id:string;source_id:string|null}>("payables",{select:"id,source_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`})]);
 const actor=actors[0];if(!actor)throw new Error("No actor"); const bySource=new Map(invoices.map(i=>[i.registry_number.replace(/^KOPER-NFE-/,""),i]));const sources=new Set(existing.flatMap(r=>r.source_id?[r.source_id]:[]));
 const plans:Array<Record<string,unknown>>=[]; const blocked:Array<Record<string,unknown>>=[];
 for(const s of stages){const inv=bySource.get(s.koper_id);if(!inv)continue;const dups=rows(object(object(s.payload).bill).duplicates);for(let i=0;i<dups.length;i++){const d=dups[i]!;if(text(d.billId))continue;const due=dateOnly(d.dueDate),amount=numeric(d.billValue),isPaid=d.isPaid===true,paymentDate=dateOnly(d.paymentDate);if(!due||amount===null||amount<=0||(isPaid&&!paymentDate)){blocked.push({invoice:s.koper_id,index:i});continue;}const sourceId=`koper_bill:missing-${s.koper_id}-${i}`;plans.push({id:uuid(`elos:koper:payable:missing:${s.koper_id}:${i}`),company_id:env.BOSSA_COMPANY_ID,project_id:inv.project_id,supplier_id:inv.supplier_id,document:`NF ${inv.invoice_number}`,fiscal_class:null,payment_method:null,due_date:due,amount,status:isPaid?"paid":"open",installment_label:`${text(d.duplicateNumber)??String(i+1)} / ${dups.length}`,notes:`Importação histórica Koper · NF-e ${s.koper_id} · parcela sem billId na origem · índice ${i}`,origin:"historical_import",source_system:"koper_flow",source_category:"electronic_invoice",source_id:sourceId,beneficiary_name:null,beneficiary_tax_id:null,paid_at:isPaid?paymentDate:null,paid_amount:isPaid?(numeric(d.paymentValue)??amount):null,paid_account_name:isPaid?"Koper (histórico)":null,created_by:actor.user_id,alreadyExists:sources.has(sourceId),invoiceTotal:inv.invoice_total});}}
 console.log("KOPER_PAYABLE_MISSING_ID_PLAN",JSON.stringify({ok:true,write,plans:plans.length,blocked:blocked.length,alreadyExisting:plans.filter(p=>p.alreadyExists===true).length,rows:plans.map(p=>({source_id:p.source_id,amount:p.amount,due_date:p.due_date,invoiceTotal:p.invoiceTotal}))}));
 if(write&&plans.length){const body=plans.map(({alreadyExists,invoiceTotal,...r})=>r);await requestSupabase("payables",{method:"POST",body,prefer:"resolution=merge-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"id"})});const now=await readAll<{source_id:string|null}>("payables",{select:"source_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper_flow"});const set=new Set(now.flatMap(r=>r.source_id?[r.source_id]:[]));console.log("KOPER_PAYABLE_MISSING_ID_RESULT",JSON.stringify({ok:true,written:body.length,verified:body.filter(r=>set.has(String(r.source_id))).length,blocked:blocked.length}));}
}catch(e){console.error("KOPER_PAYABLE_MISSING_ID_ERROR",e instanceof Error?e.message:String(e));process.exitCode=1;}
