import { createHash } from "node:crypto";
import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";

type J=Record<string,unknown>;
type Stage={koper_id:string;koper_parent_id:string|null;payload:unknown};
type Order={id:string;source_id:string|null;supplier_id:string;project_id:string;invoiced_amount:number};
type Input={id:string;source_id:string|null;description:string;unit:string};
type Supplier={id:string;source_id:string|null;legal_name:string;trade_name:string|null;tax_id:string|null};
const obj=(v:unknown):J=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:{};
const id=(v:unknown):string|null=>(typeof v==="string"||typeof v==="number")?(String(v).trim()||null):null;
const n=(v:unknown):number|null=>typeof v==="number"&&Number.isFinite(v)?v:typeof v==="string"&&v.trim()&&Number.isFinite(Number(v))?Number(v):null;
const arr=(v:unknown):J[]=>Array.isArray(v)?v.map(obj):[];
const ids=(v:unknown,k:string)=>[...new Set(arr(v).flatMap(x=>{const y=id(x[k]);return y?[y]:[]}))];
function uuid(seed:string){const b=Buffer.from(createHash("sha256").update(seed).digest("hex").slice(0,32),"hex");b[6]=((b[6]??0)&15)|80;b[8]=((b[8]??0)&63)|128;const h=b.toString("hex");return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`}
function digits(seed:string,len:number){return BigInt(`0x${createHash("sha256").update(seed).digest("hex")}`).toString(10).padStart(len,"0").slice(0,len)}
const access=(x:string)=>digits(`koper-access-key:${x}`,44), tax=(x:string)=>digits(`koper-tax-id:${x}`,14);
function d(v:unknown){const r=id(v);if(!r)return null;const x=new Date(r.includes("T")?r:r.replace(" ","T"));return !Number.isNaN(x.valueOf())?x.toISOString().slice(0,10):/^\d{4}-\d{2}-\d{2}/.test(r)?r.slice(0,10):null}
function ts(v:unknown,day:string){const r=id(v);if(r){const x=new Date(r.includes("T")?r:r.replace(" ","T"));if(!Number.isNaN(x.valueOf()))return x.toISOString()}return`${day}T12:00:00.000Z`}
async function all<T>(t:string,q:Record<string,string>){const out:T[]=[];for(let o=0;;o+=1000){const rows=await requestSupabase<T[]>(t,{query:new URLSearchParams({...q,limit:"1000",offset:String(o)})});out.push(...rows);if(rows.length<1000)return out}}
function chunks<T>(a:T[],s:number){const r:T[][]=[];for(let i=0;i<a.length;i+=s)r.push(a.slice(i,i+s));return r}
function qin(a:string[]){return`in.(${a.map(x=>`"${x.replaceAll('"','\\"')}"`).join(",")})`}
async function verify(table:string,values:string[]){let z=0;for(const b of chunks(values,100)){if(!b.length)continue;z+=(await requestSupabase<{id:string}[]>(table,{query:new URLSearchParams({select:"id",id:qin(b),limit:String(b.length+5)})})).length}return z}
function sourceIds(p:J){return[...new Set([id(p.inputId),id(p.productId),id(p.mainProductId),id(p.genericProdSeq)].filter((x):x is string=>!!x))]}
function invoiceTotal(p:J,products:Stage[]){const t=obj(p.total);for(const v of[p.invoiceTotal,p.totalValue,t.totalNF,t.totalValue,t.total]){const x=n(v);if(x!==null&&x>0)return x}const s=products.reduce((a,x)=>a+Math.max(0,n(obj(x.payload).totalValue)??0),0);return s>0?s:null}
function invoiceIds(p:J){const nested=ids(p.invoices,"invoiceId");if(nested.length)return nested;return Array.isArray(p.invoiceIds)?[...new Set(p.invoiceIds.flatMap(v=>id(v)?[id(v)!]:[]))]:[]}
function equal(a:number,b:number){return Math.abs(a-b)<=Math.max(.000001,Math.abs(b)*.000001)}
await import("./index.js");
try{
 const write=process.env.KOPER_ELECTRONIC_INVOICE_COVERAGE_WRITE_ENABLED==="true";
 const offset=Math.max(0,parseInt(process.env.KOPER_ELECTRONIC_INVOICE_COVERAGE_OFFSET??"0")||0);
 const size=Math.min(337,Math.max(1,parseInt(process.env.KOPER_ELECTRONIC_INVOICE_COVERAGE_SIZE??"25")||25));
 const [invoices,products,stockItems,stockEntries,orders,inputs,suppliers,actors,existing]=await Promise.all([
  all<Stage>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.xml_invoice",sync_state:"eq.present",order:"koper_id.asc"}),
  all<Stage>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.xml_invoice_product",sync_state:"eq.present",order:"koper_parent_id.asc,koper_id.asc"}),
  all<Stage>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.stock_entry_item",sync_state:"eq.present",order:"koper_parent_id.asc,koper_id.asc"}),
  all<Stage>("koper_staging_records",{select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.stock_entry",sync_state:"eq.present",order:"koper_id.asc"}),
  all<Order>("procurement_purchase_orders",{select:"id,source_id,supplier_id,project_id,invoiced_amount",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper",order:"source_id.asc"}),
  all<Input>("engineering_inputs",{select:"id,source_id,description,unit",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper",order:"source_id.asc"}),
  all<Supplier>("suppliers",{select:"id,source_id,legal_name,trade_name,tax_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper",order:"source_id.asc"}),
  requestSupabase<{user_id:string}[]>("company_memberships",{query:new URLSearchParams({select:"user_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,status:"eq.active",order:"created_at.asc",limit:"1"})}),
  all<{id:string}>("finance_electronic_invoices",{select:"id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"})
 ]);
 const actor=actors[0];if(!actor)throw new Error("No actor");const FLOW="ffe8b7ec-1f01-4f6c-8a03-2bd6d3ae94fc";
 const existingIds=new Set(existing.map(x=>x.id)), orderBySource=new Map(orders.flatMap(o=>o.source_id?[[o.source_id,o] as const]:[])), supById=new Map(suppliers.map(s=>[s.id,s])), supBySource=new Map(suppliers.flatMap(s=>s.source_id?[[s.source_id,s] as const]:[])), inputBySource=new Map(inputs.flatMap(x=>x.source_id?[[x.source_id,x] as const]:[])), entryById=new Map(stockEntries.map(x=>[x.koper_id,x]));
 for(const sid of["620","621"])if(!supBySource.has(sid)){const sidUuid=uuid(`elos:koper:supplier:${sid}`),now=new Date().toISOString();const row:any={id:sidUuid,company_id:env.BOSSA_COMPANY_ID,person_type:"company",legal_name:`Fornecedor histórico Koper ${sid}`,trade_name:`Fornecedor histórico Koper ${sid}`,tax_id:tax(`historical-${sid}`),status:"active",notes:`Fornecedor histórico para preservar NF-e legada · Koper originId=${sid} · razão social ausente na fonte extraída`,source_system:"koper",source_id:sid,created_by:actor.user_id,created_at:now,updated_at:now};if(write)await requestSupabase("suppliers",{method:"POST",body:[row],prefer:"resolution=merge-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"id"})});const s:Supplier={id:sidUuid,source_id:sid,legal_name:row.legal_name,trade_name:row.trade_name,tax_id:row.tax_id};supBySource.set(sid,s);supById.set(sidUuid,s)}
 const productsByInvoice=new Map<string,Stage[]>();for(const p of products)if(p.koper_parent_id)productsByInvoice.set(p.koper_parent_id,[...(productsByInvoice.get(p.koper_parent_id)??[]),p]);
 const itemByInvoice=new Map<string,Stage[]>(),entriesByInvoice=new Map<string,Set<string>>();for(const s of stockItems)for(const iid of invoiceIds(obj(s.payload))){itemByInvoice.set(iid,[...(itemByInvoice.get(iid)??[]),s]);if(s.koper_parent_id){const set=entriesByInvoice.get(iid)??new Set<string>();set.add(s.koper_parent_id);entriesByInvoice.set(iid,set)}}
 const plans:any[]=[],blocked:any[]=[];
 for(let idx=0;idx<invoices.length;idx++){const st=invoices[idx]!,nativeId=uuid(`elos:koper:electronic-invoice:${st.koper_id}`);if(existingIds.has(nativeId))continue;const p=obj(st.payload),prs=productsByInvoice.get(st.koper_id)??[],eids=[...(entriesByInvoice.get(st.koper_id)??[])];const so=new Set(ids(p.purchaseOrders,"purchaseOrderId"));for(const si of itemByInvoice.get(st.koper_id)??[]){const sp=obj(si.payload);for(const key of["candidatePurchaseOrderIds","purchaseOrderIds"])if(Array.isArray(sp[key]))for(const raw of sp[key] as unknown[]){const z=id(raw);if(z)so.add(z)}const z=id(sp.purchaseOrderId);if(z)so.add(z)}const nos=[...new Map([...so].flatMap(x=>{const o=orderBySource.get(x);return o?[[o.id,o] as const]:[]})).values()];const ps=[...new Set(nos.map(o=>o.project_id))],ss=[...new Set(nos.map(o=>o.supplier_id))];let project=ps.length===1?ps[0]!:null;if(!project&&eids.some(e=>id(obj(entryById.get(e)?.payload).placeEntryId)==="169"))project=FLOW;let supplier=ss.length===1?supById.get(ss[0]!):undefined;if(!supplier){const origins=[...new Set(eids.flatMap(e=>{const z=id(obj(entryById.get(e)?.payload).originId);return z?[z]:[]}))];const found=[...new Map(origins.flatMap(x=>{const s=supBySource.get(x);return s?[[s.id,s] as const]:[]})).values()];if(found.length===1)supplier=found[0]}const day=d(p.emitDate),number=id(p.invoiceNumber),tot=invoiceTotal(p,prs);if(!project||!supplier||!day||!number||tot===null||!prs.length){blocked.push({invoiceId:st.koper_id,project:!!project,supplier:!!supplier,day:!!day,number:!!number,total:tot,products:prs.length});continue}plans.push({st,p,prs,idx,nativeId,project,supplier,order:nos.length===1?nos[0]:null,day,number,tot})}
 console.log("KOPER_NFE_COVERAGE_V2_PLAN",JSON.stringify({ok:blocked.length===0,write,sourceInvoices:invoices.length,existingInvoices:existingIds.size,readyInvoices:plans.length,readyItems:plans.reduce((a,x)=>a+x.prs.length,0),blockedInvoices:blocked.length,blocked}));if(blocked.length)process.exit(2);
 const selected=plans.slice(offset,offset+size);if(!write){console.log("KOPER_NFE_COVERAGE_V2_BATCH",JSON.stringify({offset,size,selected:selected.length,items:selected.reduce((a,x)=>a+x.prs.length,0),complete:offset+selected.length>=plans.length}));process.exit(0)}
 if(!selected.length){console.log("KOPER_NFE_COVERAGE_V2_RESULT",JSON.stringify({ok:true,selectedInvoices:0,complete:true}));process.exit(0)}
 const beforeOrders=new Map(orders.map(o=>[o.id,Number(o.invoiced_amount??0)]));const [pb,ib]=await Promise.all([all<{id:string}>("payables",{select:"id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),all<{id:string}>("finance_electronic_invoice_installments",{select:"id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"})]);const now=new Date().toISOString();
 const headers=selected.map(x=>{const t=obj(x.p.total);return{id:x.nativeId,company_id:env.BOSSA_COMPANY_ID,project_id:x.project,legal_entity_id:null,supplier_id:x.supplier.id,order_id:x.order?.id??null,receipt_id:null,sequence_no:6_000_000+x.idx,registry_number:`KOPER-NFE-${x.st.koper_id}`,access_key:access(x.st.koper_id),model:id(x.p.invoiceType)??"KOPER-XML",series:null,invoice_number:x.number,issue_date:x.day,issue_datetime:ts(x.p.emitDate,x.day),operation_nature:null,issuer_tax_id:x.supplier.tax_id??tax(x.supplier.source_id??x.supplier.id),issuer_name:x.supplier.legal_name,issuer_trade_name:x.supplier.trade_name,issuer_state_registration:null,recipient_tax_id:null,recipient_name:null,products_amount:n(t.totalValue)??x.prs.reduce((a:number,r:Stage)=>a+(n(obj(r.payload).totalValue)??0),0),freight_amount:n(t.shippingValue)??0,insurance_amount:0,discount_amount:n(t.totalDiscount)??0,import_tax_amount:0,ipi_amount:n(t.ipi)??0,pis_amount:n(t.pis)??0,cofins_amount:n(t.cofins)??0,icms_amount:0,other_amount:(n(t.otherValues)??0)+(n(t.st)??0),invoice_total:x.tot,payment_total:0,item_count:x.prs.length,mapped_item_count:0,divergence_count:x.prs.length,xml_storage_path:`koper/xml-invoice/${x.st.koper_id}`,xml_file_name:`${x.st.koper_id}.json`,xml_hash:createHash("sha256").update(JSON.stringify(x.st.payload)).digest("hex"),imported_by:actor.user_id,imported_at:now,created_at:ts(x.p.emitDate,x.day),updated_at:now}});
 const items=selected.flatMap(x=>{const used=new Set<number>();return x.prs.map((ps:Stage,i:number)=>{const p=obj(ps.payload);let line=parseInt(id(p.numberItem)??String(i+1));if(!Number.isInteger(line)||line<=0||used.has(line))line=i+1;while(used.has(line))line++;used.add(line);const candidates=[...new Map(sourceIds(p).flatMap(s=>{const z=inputBySource.get(s);return z?[[z.id,z] as const]:[]})).values()];const input=candidates.length===1?candidates[0]:null;const qty=n(p.amount)??0,unit=n(p.unitValue)??0,amt=n(p.totalValue)??qty*unit;return{id:uuid(`elos:koper:electronic-invoice:${x.st.koper_id}:product:${ps.koper_id}`),company_id:env.BOSSA_COMPANY_ID,project_id:x.project,invoice_id:x.nativeId,line_number:line,supplier_product_code:id(p.productId)??id(p.inputId)??id(p.mainProductId),ean:null,description:input?.description??`Item histórico Koper ${id(p.productId)??id(p.inputId)??line}`,ncm:null,cfop:id(p.invoiceCfop),unit_snapshot:id(p.inputUnit)??input?.unit??"un",quantity:qty,unit_price:unit,gross_amount:qty*unit,discount_amount:Math.max(0,qty*unit-amt),freight_amount:0,other_amount:0,total_amount:amt,icms_amount:0,ipi_amount:0,pis_amount:0,cofins_amount:0,input_id:input?.id??null,cost_center_service_id:null,order_item_id:null,receipt_item_id:null,mapping_status:"unmapped",order_quantity:null,order_unit_price:null,quantity_variance:null,unit_price_variance:null,notes:`Importado do Koper · sourceInvoiceProductId=${ps.koper_id} · vínculo histórico pendente`,created_at:ts(x.p.emitDate,x.day),updated_at:now,receipt_quantity:null,receipt_unit_cost:null,previously_invoiced_quantity:0,invoiceable_quantity:0,three_way_status:"pending"}}) });
 for(const b of chunks(headers,100))await requestSupabase("finance_electronic_invoices",{method:"POST",body:b,prefer:"resolution=merge-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"id"})});for(const b of chunks(items,100))await requestSupabase("finance_electronic_invoice_items",{method:"POST",body:b,prefer:"resolution=merge-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"id"})});
 const [vi,vitems,pa,ia,oa]=await Promise.all([verify("finance_electronic_invoices",headers.map(x=>x.id)),verify("finance_electronic_invoice_items",items.map(x=>x.id)),all<{id:string}>("payables",{select:"id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),all<{id:string}>("finance_electronic_invoice_installments",{select:"id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),all<Order>("procurement_purchase_orders",{select:"id,source_id,supplier_id,project_id,invoiced_amount",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper",order:"id.asc"})]);if(vi!==headers.length||vitems!==items.length)throw new Error(`verification ${vi}/${headers.length} ${vitems}/${items.length}`);if(pa.length!==pb.length||ia.length!==ib.length)throw new Error("financial side effect");for(const o of oa){const b=beforeOrders.get(o.id);if(b!==undefined&&!equal(b,Number(o.invoiced_amount??0)))throw new Error(`order amount changed ${o.id}`)}console.log("KOPER_NFE_COVERAGE_V2_RESULT",JSON.stringify({ok:true,selectedInvoices:headers.length,selectedItems:items.length,verifiedInvoices:vi,verifiedItems:vitems,payablesCreated:0,installmentsCreated:0,orderInvoicedAmountsUnchanged:true,nextOffset:offset+selected.length,complete:offset+selected.length>=plans.length}));
}catch(e){console.error("KOPER_NFE_COVERAGE_V2_FAILED",e instanceof Error?e.message:String(e));process.exit(1)}