import { createHash } from "node:crypto";
import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";
type J=Record<string,unknown>;type Stage={koper_id:string;koper_parent_id:string|null;payload:unknown};
const obj=(v:unknown):J=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:{};
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
async function all<T>(){const out:T[]=[];for(let o=0;;o+=1000){const rows=await requestSupabase<T[]>("koper_staging_records",{query:new URLSearchParams({select:"koper_id,koper_parent_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:"eq.bill_resolution",sync_state:"eq.present",limit:"1000",offset:String(o)}),timeoutMs:30000});out.push(...rows);if(rows.length<1000)return out}}
const rows=await all<Stage>();const targets=rows.filter(r=>{const p=obj(r.payload);if(Number(p.version??0)!==5||p.status!=="exact_allocated")return false;const ids=Array.isArray(p.serviceSourceIds)?p.serviceSourceIds.map(String):[];return ids.some(x=>!/^\d+$/.test(x));});let reverted=0,value=0;const examples:J[]=[];
for(const r of targets){const p=obj(r.payload),billValue=Number(p.billValue??0);const rejected=Array.isArray(p.serviceSourceIds)?p.serviceSourceIds.map(String).filter(x=>!/^\d+$/.test(x)):[];const next={...p,version:6,status:"unresolved",serviceSourceIds:[],wbsCodes:[],allocations:[],projectEvidence:{...obj(p.projectEvidence),stockFallbackRejected:"non_native_placeholder_service",rejectedServiceSourceIds:rejected}};const now=new Date().toISOString();await requestSupabase("koper_staging_records",{method:"POST",body:[{company_id:env.BOSSA_COMPANY_ID,source:"koper",entity:"bill_resolution",koper_id:r.koper_id,koper_parent_id:r.koper_parent_id,payload:next,payload_hash:hash(next),first_seen_at:now,last_seen_at:now,processing_status:"processed",processing_error:null,mapping_version:6,sync_state:"present",elos_id:null,updated_at:now}],prefer:"resolution=merge-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"company_id,source,entity,koper_id"})});reverted++;value+=Number.isFinite(billValue)?billValue:0;if(examples.length<30)examples.push({billId:r.koper_id,billValue,rejected});}
console.log("KOPER_NFE_STOCK_PLACEHOLDER_REJECT",JSON.stringify({candidates:targets.length,reverted,value:Math.round(value*100)/100,examples}));