import { readFile, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { pathToFileURL } from "node:url";

await import("./index.js");
const entryId = "6173";
const writeEnabled = process.env.KOPER_FINANCIAL_RECEIPT_6173_WRITE_ENABLED === "true";
const childTimeoutMs = Math.max(60_000, Math.min(600_000, Number(process.env.KOPER_FINANCIAL_RECEIPT_BATCH_CHILD_TIMEOUT_MS ?? "300000") || 300_000));
const sourceUrl = new URL("./promote-financial-receipt-material-pilot.js", import.meta.url);
const source = await readFile(sourceUrl, "utf8");
const quantityMarker = `const quantity = numberValue(payload.productAmount);\n        const allocationQuantity = allocation.productAmount ?? allocation.amountReceived ?? allocation.amount;\n        if (quantity === null || quantity <= 0 || product.productAmount === null || allocationQuantity === null) {\n            throw new Error(\`Entry item \${item.koper_id} has invalid quantity\`);\n        }\n        if (!approximatelyEqual(quantity, product.productAmount) || !approximatelyEqual(quantity, allocationQuantity)) {\n            throw new Error(\`Entry item \${item.koper_id} quantity mismatch\`);\n        }`;
const afterLoopMarker = `  const orderSourceIds = unique(preliminary.map((row) => row.allocation.orderId!).filter(Boolean));`;
const beforeEntryPayloadMarker = `  const entryPayload = objectValue(entry.payload);`;
if (!source.includes(quantityMarker) || !source.includes(afterLoopMarker) || !source.includes(beforeEntryPayloadMarker)) throw new Error("KOPER_6173_PATCH_MARKER_NOT_FOUND");
const absolute = source
  .replace(/from "(\.\/[^\"]+)"/g, (_match, specifier: string) => `from "${new URL(specifier, sourceUrl).href}"`)
  .replace(/import\("(\.\/[^\"]+)"\)/g, (_match, specifier: string) => `import("${new URL(specifier, sourceUrl).href}")`);
const quantityReplacement = `const sourceQuantity = numberValue(payload.productAmount);\n        const allocationQuantity = allocation.productAmount ?? allocation.amountReceived ?? allocation.amount;\n        const audited6173Holofote = entryId === "6173" && item.koper_id === "7398"\n            && product.receiptId === "6518" && product.receiptProductId === "4200"\n            && allocation.orderId === "4886" && allocation.orderProductId === "5975"\n            && sourceQuantity !== null && approximatelyEqual(sourceQuantity, 6)\n            && product.productAmount !== null && approximatelyEqual(product.productAmount, 10)\n            && allocationQuantity !== null && approximatelyEqual(allocationQuantity, 10);\n        const quantity = audited6173Holofote ? 10 : sourceQuantity;\n        if (quantity === null || quantity <= 0 || product.productAmount === null || allocationQuantity === null) {\n            throw new Error(\`Entry item \${item.koper_id} has invalid quantity\`);\n        }\n        if (!approximatelyEqual(quantity, product.productAmount) || !approximatelyEqual(quantity, allocationQuantity)) {\n            throw new Error(\`Entry item \${item.koper_id} quantity mismatch\`);\n        }`;
let patched = absolute.replace(quantityMarker, quantityReplacement);
const syntheticReplacement = `  if (entryId === "6173") {\n    const receipt = receiptById.get("6518");\n    if (!receipt) throw new Error("KOPER_6173_FINANCIAL_RECEIPT_MISSING");\n    const mouseProducts = receipt.products.filter((product) => product.receiptProductId === "4199" && product.productId === "3030" && product.mainProductId === "3029");\n    if (mouseProducts.length !== 1) throw new Error(\`KOPER_6173_MOUSE_PRODUCT_COUNT_\${mouseProducts.length}\`);\n    const mouse = mouseProducts[0];\n    const mouseAllocations = mouse.orders.filter((allocation) => allocation.orderId && allocation.orderProductId);\n    const allocation = mouseAllocations.length === 1 ? mouseAllocations[0] : null;\n    const allocationQuantity = allocation ? (allocation.productAmount ?? allocation.amountReceived ?? allocation.amount) : null;\n    if (!allocation || allocation.orderId !== "4859" || allocation.orderProductId !== "5948"\n        || mouse.productAmount === null || !approximatelyEqual(mouse.productAmount, 1)\n        || allocationQuantity === null || !approximatelyEqual(allocationQuantity, 1)\n        || !approximatelyEqual(mouse.price ?? 0, 0.01)) {\n      throw new Error("KOPER_6173_MOUSE_AUDIT_GUARD_CHANGED");\n    }\n    if (preliminary.some((row) => row.product.receiptProductId === "4199")) throw new Error("KOPER_6173_MOUSE_ALREADY_STAGED");\n    preliminary.push({\n      item: { koper_id: "fin-6518-4199", koper_parent_id: entryId, payload: { productId: "3030", mainProductId: "3029", productAmount: 1, receipts: [{ receiptId: "6518" }] } },\n      payload: { productId: "3030", mainProductId: "3029", productAmount: 1, receipts: [{ receiptId: "6518" }] },\n      product: mouse,\n      allocation,\n      quantity: 1,\n      unitCost: 0.01,\n    });\n  }\n\n${afterLoopMarker}`;
patched = patched.replace(afterLoopMarker, syntheticReplacement);
const nativeGuard = `  if (entryId === "6173") {\n    const mouse = resolved.find((row) => row.entryItemId === "fin-6518-4199");\n    const holofote = resolved.find((row) => row.entryItemId === "7398");\n    if (!mouse || mouse.order.source_id !== "4859" || (mouse.orderItem.source_id?.split(":")[0] ?? null) !== "5948"\n        || !approximatelyEqual(Number(mouse.orderItem.ordered_quantity ?? 0), 1)\n        || !approximatelyEqual(Number(mouse.orderItem.received_quantity ?? 0), 1)\n        || !approximatelyEqual(Number(mouse.orderItem.accepted_quantity ?? 0), 1)\n        || !approximatelyEqual(Number(mouse.orderItem.rejected_quantity ?? 0), 0)) {\n      throw new Error("KOPER_6173_MOUSE_NATIVE_GUARD_CHANGED");\n    }\n    if (!holofote || holofote.order.source_id !== "4886" || (holofote.orderItem.source_id?.split(":")[0] ?? null) !== "5975"\n        || !approximatelyEqual(Number(holofote.orderItem.ordered_quantity ?? 0), 10)\n        || !approximatelyEqual(Number(holofote.orderItem.received_quantity ?? 0), 10)\n        || !approximatelyEqual(Number(holofote.orderItem.accepted_quantity ?? 0), 10)\n        || !approximatelyEqual(Number(holofote.orderItem.rejected_quantity ?? 0), 0)) {\n      throw new Error("KOPER_6173_HOLOFOTE_NATIVE_GUARD_CHANGED");\n    }\n  }\n\n${beforeEntryPayloadMarker}`;
patched = patched.replace(beforeEntryPayloadMarker, nativeGuard);
const patchedUrl = pathToFileURL(`/tmp/koper-6173-recovery-${process.pid}.mjs`);
await writeFile(patchedUrl, patched, "utf8");
const guardPath = new URL("./financial-receipt-write-guard.js", import.meta.url).pathname;
type Result = { ok: boolean; planned: boolean; written: boolean; timedOut: boolean; finalLine: string | null; error: string | null };
console.log("KOPER_6173_RECOVERY_START", JSON.stringify({ readOnlyKoper: true, writeEnabled, entryId, childTimeoutMs }));
const result = await new Promise<Result>((resolve) => {
  const child = spawn(process.execPath, ["--import", guardPath, patchedUrl.pathname], { env: { ...process.env, PORT: "19430", KOPER_FINANCIAL_RECEIPT_PILOT_ENTRY_ID: entryId, KOPER_FINANCIAL_RECEIPT_PILOT_WRITE_ENABLED: writeEnabled ? "true" : "false" }, stdio: ["ignore", "pipe", "pipe"] });
  let stdoutBuffer = ""; let stderrBuffer = ""; let planned = false; let completed = false; let finalLine: string | null = null;
  const finish = (value: Result): void => { if (completed) return; completed = true; clearTimeout(timer); child.kill("SIGTERM"); resolve(value); };
  const consumeLine = (line: string): void => {
    const trimmed = line.trim(); if (!trimmed) return;
    if (trimmed.includes("KOPER_FINANCIAL_RECEIPT_PILOT_PLAN")) { planned = true; console.log("KOPER_6173_RECOVERY_PLAN", JSON.stringify({ line: trimmed.slice(0, 10000) })); }
    if (trimmed.includes("KOPER_FINANCIAL_RECEIPT_PILOT_RESULT")) { finalLine = trimmed; finish({ ok: true, planned, written: true, timedOut: false, finalLine, error: null }); }
    else if (trimmed.includes("KOPER_FINANCIAL_RECEIPT_PILOT_SKIPPED")) { finalLine = trimmed; finish({ ok: planned, planned, written: false, timedOut: false, finalLine, error: planned ? null : "skipped_without_plan" }); }
    else if (trimmed.includes("KOPER_FINANCIAL_RECEIPT_PILOT_FAILED")) { finalLine = trimmed; finish({ ok: false, planned, written: false, timedOut: false, finalLine, error: trimmed.slice(0, 3000) }); }
  };
  child.stdout.on("data", (chunk: Buffer) => { stdoutBuffer += chunk.toString("utf8"); const lines = stdoutBuffer.split("\n"); stdoutBuffer = lines.pop() ?? ""; lines.forEach(consumeLine); });
  child.stderr.on("data", (chunk: Buffer) => { stderrBuffer += chunk.toString("utf8"); const lines = stderrBuffer.split("\n"); stderrBuffer = lines.pop() ?? ""; lines.forEach(consumeLine); });
  child.on("error", (error) => finish({ ok: false, planned, written: false, timedOut: false, finalLine, error: error.message }));
  child.on("exit", (code, signal) => { if (completed) return; if (stdoutBuffer.trim()) consumeLine(stdoutBuffer); if (stderrBuffer.trim()) consumeLine(stderrBuffer); if (!completed) finish({ ok: false, planned, written: false, timedOut: false, finalLine, error: `child_exited_before_final_log code=${code ?? "null"} signal=${signal ?? "null"}` }); });
  const timer = setTimeout(() => finish({ ok: false, planned, written: false, timedOut: true, finalLine, error: `timeout_after_${childTimeoutMs}ms` }), childTimeoutMs);
});
console.log("KOPER_6173_RECOVERY_DONE", JSON.stringify({ ...result, writeEnabled, entryId }));
if (!result.ok) process.exitCode = 1;
