import { createHash } from "node:crypto";
import type { Response } from "playwright-core";
import { env } from "./config/env.js";
import { requestSupabase } from "./elos/supabase.js";
import { performKoperLogin } from "./auth/koper-auto-login.js";
import { withBrowserless } from "./browser/browserless.js";
import { isAllowedFlowSwitch } from "./diagnostics/inspect-koper-engineering.js";
import { selectFlow } from "./diagnostics/collect-flow-stock-requests.js";
type J=Record<string,unknown>;type Stage={koper_id:string;koper_parent_id:string|null;payload:unknown};
const obj=(v:unknown):J=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:{};
const first=(...v:unknown[])=>v.find(x=>x!==undefined&&x!==null)??null;
const id=(v:unknown)=>v===null||v===undefined||v===""?null:String(v);
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
async function all<T>(entity:string,select:string){const out:T[]=[];for(let o=0;;o+=1000){const rows=await requestSupabase<T[]>("koper_staging_records",{query:new URLSearchParams({select,company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:`eq.${entity}`,sync_state:"eq.present",limit:"1000",offset:String(o),order:"koper_id.asc"}),timeoutMs:30000});out.push(...rows);if(rows.length<1000)return out;}}
function compact(detail:J){const beneficiary=obj(detail.beneficiary),origins=obj(detail.origins),billOrigin=obj(first(detail.bill_origin,detail.billOrigin)),costCenter=obj(first(detail.cost_center,detail.costCenter));return{
 billId:id(first(detail.bill_id,detail.billId,detail.id)),billToPayId:id(first(detail.bill_to_pay_id,detail.billToPayId)),fatherBillId:id(first(detail.father_bill_id,detail.fatherBillId)),joinBillId:id(first(detail.join_bill_id,detail.joinBillId)),
 supplierId:id(first(detail.supplier_id,detail.supplierId,beneficiary.supplier_id,beneficiary.supplierId)),supplierName:first(detail.supplier_name,detail.supplierName,beneficiary.supplier_name,beneficiary.supplierName),supplierCreditId:id(first(detail.supplier_credit_id,detail.supplierCreditId,beneficiary.supplier_credit_id)),
 dueDate:first(detail.due_date,detail.dueDate),paidAt:first(detail.paid_at,detail.paidAt),paymentValue:first(detail.payment_value,detail.paymentValue),status:first(detail.status,detail.bill_status,detail.billStatus),isPaid:first(detail.is_paid,detail.isPaid),billValue:first(detail.bill_value,detail.billValue,detail.value),installmentAmount:first(detail.installment_amount,detail.installmentAmount),billType:first(detail.bill_type,detail.billType),
 accountId:id(first(detail.account_id,detail.accountId)),chartAccountId:id(first(detail.chart_account_id,detail.chartAccountId)),itemChartAccountId:id(first(detail.item_chart_account_id,detail.itemChartAccountId)),costCenterId:id(first(costCenter.id,detail.cost_center_id,detail.costCenterId)),
 originName:first(billOrigin.origin_name,billOrigin.originName,detail.origin_name,detail.originName),originId:id(first(billOrigin.origin_id,billOrigin.originId)),receiptId:id(first(origins.receipt_id,origins.receiptId,detail.receipt_id)),invoiceId:id(first(origins.invoice_id,origins.invoiceId,detail.invoice_id)),releaseId:id(first(origins.fnc_release_id,origins.fncReleaseId,detail.fnc_release_id)),stageReleaseId:id(first(origins.fnc_stage_release_id,origins.fncStageReleaseId,detail.fnc_stage_release_id)),buildMonitoringId:id(first(origins.build_monitoring_id,origins.buildMonitoringId,detail.build_monitoring_id)),
 beneficiarySupplierId:id(first(beneficiary.supplier_id,beneficiary.supplierId)),beneficiarySupplierName:first(beneficiary.supplier_name,beneficiary.supplierName)
};}
async function main(){const [bills,doneRows]=await Promise.all([all<Stage>("bill_to_pay","koper_id,koper_parent_id,payload"),all<Stage>("bill_detail_enrichment","koper_id,koper_parent_id,payload")]);const done=new Set(doneRows.map(x=>x.koper_id));const raw=Number(process.env.KOPER_DETAIL_BATCH_SIZE??100),batch=Number.isFinite(raw)&&raw>0?Math.min(150,Math.floor(raw)):100;const selected=bills.filter(x=>!done.has(x.koper_id)).slice(0,batch);console.log("KOPER_PAYABLE_DETAIL_ENRICHMENT_START",JSON.stringify({nativeBills:bills.length,done:done.size,remaining:bills.length-done.size,selected:selected.length,batch}));if(!selected.length){console.log("KOPER_PAYABLE_DETAIL_ENRICHMENT_DONE",JSON.stringify({complete:true,total:bills.length,done:done.size}));return;}
 const result=await withBrowserless(async({page})=>{const login=await performKoperLogin(page);if(!login.authenticated)throw new Error(login.message??"KOPER_LOGIN_FAILED");let blockedWrites=0;await page.route("**/*",async route=>{const r=route.request();try{const u=new URL(r.url()),koper=u.hostname==="koper.com.br"||u.hostname.endsWith(".koper.com.br");if(koper&&!["GET","HEAD","OPTIONS"].includes(r.method())&&!isAllowedFlowSwitch(u,r.method(),r.postData())){blockedWrites++;await route.abort("blockedbyclient");return;}}catch{}await route.continue();});if(!await selectFlow(page))throw new Error("KOPER_FLOW_COMPANY_NOT_SELECTED");const seedP=page.waitForResponse((response:Response)=>{try{const u=new URL(response.url());return response.request().method()==="GET"&&u.hostname==="api.koper.com.br"&&u.pathname==="/financial/v1/bills_to_pay"&&!u.searchParams.has("billId");}catch{return false;}},{timeout:20000}).catch(()=>null);await page.goto("https://app.koper.com.br/financeiro/contas_pagar",{waitUntil:"domcontentloaded",timeout:15000}).catch(()=>undefined);const seed=await seedP;if(!seed)throw new Error("KOPER_PAYABLE_SEED_NOT_FOUND");const sh=seed.request().headers(),headers:Record<string,string>={};for(const k of["accept","origin","referer","x-accesstoken","x-koper"])if(sh[k])headers[k]=sh[k];let cursor=0,success=0,failed=0;const failures:Array<{billId:string;error:string}>=[];const workers=Array.from({length:Math.min(8,selected.length)},async()=>{while(true){const i=cursor++;if(i>=selected.length)return;const row=selected[i]!;try{const u=new URL("https://api.koper.com.br/financial/v1/bills_to_pay");u.searchParams.set("billId",row.koper_id);u.searchParams.set("cb",String(Date.now()+i));const response=await page.request.get(u.toString(),{headers,timeout:12000});if(!response.ok())throw new Error(`HTTP_${response.status()}`);const detail=obj(await response.json().catch(()=>null));const payload={version:1,...compact(detail)};const now=new Date().toISOString();await requestSupabase("koper_staging_records",{method:"POST",body:[{company_id:env.BOSSA_COMPANY_ID,source:"koper",entity:"bill_detail_enrichment",koper_id:row.koper_id,koper_parent_id:row.koper_parent_id,payload,payload_hash:hash(payload),first_seen_at:now,last_seen_at:now,processing_status:"processed",processing_error:null,mapping_version:1,sync_state:"present",elos_id:null,updated_at:now}],prefer:"resolution=merge-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"company_id,source,entity,koper_id"}),timeoutMs:30000});success++;}catch(e){failed++;if(failures.length<30)failures.push({billId:row.koper_id,error:e instanceof Error?e.message.slice(0,300):"unknown"});}}});await Promise.all(workers);return{readOnlyKoper:true,blockedWrites,success,failed,failures};},{sessionTimeoutMs:175000});console.log("KOPER_PAYABLE_DETAIL_ENRICHMENT_RESULT",JSON.stringify(result));}
main().catch(e=>{console.error("KOPER_PAYABLE_DETAIL_ENRICHMENT_FAILED",JSON.stringify({message:e instanceof Error?e.message.slice(0,2000):"unknown"}));process.exitCode=1;});