import { createHash } from "node:crypto";
import type { Response } from "playwright-core";
import { performKoperLogin } from "./auth/koper-auto-login.js";
import { withBrowserless } from "./browser/browserless.js";
import { env } from "./config/env.js";
import { isAllowedFlowSwitch } from "./diagnostics/inspect-koper-engineering.js";
import { selectFlow } from "./diagnostics/collect-flow-stock-requests.js";
import { requestSupabase } from "./elos/supabase.js";
import { createKoperStagingRecord } from "./sync/staging-record.js";

type J=Record<string,unknown>;
type Bill={billId:string;billToPayId:string|null;billValue:number;dueDate:string|null;isPaid:boolean;paymentDate:string|null;paymentValue:number|null;invoiceNumber:string|null;receiptNumber:string|null;originName:string|null};
type Detail={supplierId:string|null;supplierName:string|null;costCenterId:string|null;invoiceId:string|null};
type Stage={id:string;koper_id:string;payload:J};
type Payable={id:string;source_id:string|null;project_id:string;supplier_id:string;amount:number;due_date:string;status:string;paid_at:string|null;paid_amount:number|null;notes:string|null};
type Invoice={registry_number:string;project_id:string;supplier_id:string;invoice_number:string};
type Supplier={id:string;source_id:string|null;source_system:string|null;legal_name:string};
const o=(v:unknown):J=>typeof v==="object"&&v!==null&&!Array.isArray(v)?v as J:{};
const s=(v:unknown):string|null=>v==null||String(v).trim()===""?null:String(v).trim();
const cents=(v:unknown):number=>Math.round(Number(v??0)*100);
const date=(v:unknown):string|null=>{const raw=s(v);return raw&&/^\d{4}-\d{2}-\d{2}/.test(raw)?raw.slice(0,10):null;};
const uuid=(seed:string)=>{const b=Buffer.from(createHash("sha256").update(seed).digest("hex").slice(0,32),"hex");b[6]=((b[6]??0)&15)|80;b[8]=((b[8]??0)&63)|128;const h=b.toString("hex");return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};
async function all<T>(table:string,query:Record<string,string>):Promise<T[]>{const out:T[]=[];for(let offset=0;;offset+=1000){const rows=await requestSupabase<T[]>(table,{query:new URLSearchParams({...query,limit:"1000",offset:String(offset)}),timeoutMs:30000});out.push(...rows);if(rows.length<1000)return out;}}
const stage=(entity:string)=>all<Stage>("koper_staging_records",{select:"id,koper_id,payload",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source:"eq.koper",entity:`eq.${entity}`,sync_state:"eq.present",order:"koper_id.asc"});
const parseBill=(row:J):Bill=>({billId:s(row.billId)??"",billToPayId:s(row.billToPayId),billValue:Number(row.billValue),dueDate:date(row.dueDate),isPaid:row.isPaid===true,paymentDate:date(row.paymentDate),paymentValue:row.paymentValue==null?null:Number(row.paymentValue),invoiceNumber:s(row.invoiceNumber),receiptNumber:s(row.receiptNumber),originName:s(row.originName)});
const parseDetail=(raw:J):Detail=>{const beneficiary=o(raw.beneficiary),cost=o(raw.cost_center??raw.costCenter),origins=o(raw.origins);return{supplierId:s(raw.supplier_id??raw.supplierId??beneficiary.supplier_id??beneficiary.supplierId),supplierName:s(raw.supplier_name??raw.supplierName??beneficiary.supplier_name??beneficiary.supplierName),costCenterId:s(cost.id??raw.cost_center_id??raw.costCenterId),invoiceId:s(origins.invoice_id??origins.invoiceId??raw.invoice_id??raw.invoiceId)};};

async function capture():Promise<{bills:Bill[];details:Map<string,Detail>;blockedWrites:number;headerTotal:number;computedTotal:number}> {
 return withBrowserless(async({page})=>{
  const login=await performKoperLogin(page);if(!login.authenticated)throw new Error(`KOPER_AUTH_FAILED: ${login.message??"unknown"}`);
  let blockedWrites=0;
  await page.route("**/*",async route=>{const req=route.request();try{const u=new URL(req.url());const koper=u.hostname==="koper.com.br"||u.hostname.endsWith(".koper.com.br");if(koper&&!(["GET","HEAD","OPTIONS"].includes(req.method()))&&!isAllowedFlowSwitch(u,req.method(),req.postData())){blockedWrites++;await route.abort("blockedbyclient");return;}}catch{}await route.continue();});
  if(!await selectFlow(page))throw new Error("KOPER_FLOW_NOT_SELECTED");
  const seedPromise=page.waitForResponse((response:Response)=>{try{const u=new URL(response.url());return response.request().method()==="GET"&&u.hostname==="api.koper.com.br"&&u.pathname==="/financial/v1/bills_to_pay"&&!u.searchParams.has("billId");}catch{return false;}},{timeout:20000}).catch(()=>null);
  await page.goto("https://app.koper.com.br/financeiro/contas_pagar",{waitUntil:"domcontentloaded",timeout:15000}).catch(()=>undefined);
  const seed=await seedPromise;if(!seed)throw new Error("KOPER_PAYABLE_LIST_SEED_MISSING");
  const original=seed.request().headers(),headers:Record<string,string>={};for(const k of ["accept","origin","referer","x-accesstoken","x-koper"])if(original[k])headers[k]=original[k]!;
  const template=new URL(seed.url());for(const[k,v]of Object.entries({allBills:"yes",initialDate:"",finalDate:"",limit:"500",offset:"0",orderFlag:"asc",orderby:"dueDate",typeDate:"dueDate"}))template.searchParams.set(k,v);
  const bills:Bill[]=[];let expected=-1,headerTotal=0,headerOpenTotal=0;
  for(let offset=0;offset<20000;offset+=500){const u=new URL(template);u.searchParams.set("offset",String(offset));u.searchParams.set("cb",String(Date.now()));const res=await page.request.get(u.toString(),{headers,timeout:12000});if(!res.ok())throw new Error(`KOPER_LIST_HTTP_${res.status()}`);const body=o(await res.json().catch(()=>null));if(offset===0){expected=Number(body.billsAmount);headerTotal=cents(body.totalBills);headerOpenTotal=cents(body.totalNotPaid);}const list=Array.isArray(body.bills)?body.bills.map(o):[];bills.push(...list.map(parseBill));if(!list.length||bills.length>=expected||list.length<500)break;}
  if(!Number.isInteger(expected)||expected<0||bills.length!==expected||new Set(bills.map(x=>x.billId)).size!==expected||bills.some(x=>!x.billId||!Number.isFinite(x.billValue)))throw new Error(`KOPER_LIST_INCOMPLETE_${bills.length}_${expected}`);
  const computedTotal=bills.reduce((v,x)=>v+cents(x.billValue),0);
  const openTotal=bills.filter(x=>!x.isPaid).reduce((v,x)=>v+cents(x.billValue),0);
  if(!Number.isFinite(headerOpenTotal)||openTotal!==headerOpenTotal)throw new Error(`KOPER_LIST_OPEN_TOTAL_MISMATCH_${openTotal}_${headerOpenTotal}`);
  const signature=(items:Bill[])=>createHash("sha256").update(JSON.stringify(items.map(x=>[x.billId,cents(x.billValue),x.dueDate,x.isPaid,x.paymentDate,x.paymentValue==null?null:cents(x.paymentValue)]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))))).digest("hex");
  const repeated:Bill[]=[];let repeatedCount=-1,repeatedTotal=0,repeatedOpenTotal=0;
  for(let offset=0;offset<20000;offset+=500){const u=new URL(template);u.searchParams.set("offset",String(offset));u.searchParams.set("cb",String(Date.now()));const res=await page.request.get(u.toString(),{headers,timeout:12000});if(!res.ok())throw new Error(`KOPER_REPEAT_HTTP_${res.status()}`);const body=o(await res.json().catch(()=>null));if(offset===0){repeatedCount=Number(body.billsAmount);repeatedTotal=cents(body.totalBills);repeatedOpenTotal=cents(body.totalNotPaid);}const list=Array.isArray(body.bills)?body.bills.map(o):[];repeated.push(...list.map(parseBill));if(!list.length||repeated.length>=repeatedCount||list.length<500)break;}
  if(repeatedCount!==expected||repeated.length!==expected||new Set(repeated.map(x=>x.billId)).size!==expected||repeatedTotal!==headerTotal||repeatedOpenTotal!==headerOpenTotal||signature(repeated)!==signature(bills))throw new Error("KOPER_LIST_REPEAT_MISMATCH");
  const [posted,storedDetails]=await Promise.all([all<{source_id:string|null}>("payables",{select:"source_id",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper_flow",order:"id.asc"}),stage("bill_detail_enrichment")]);const known=new Set(posted.map(x=>x.source_id)),detailIds=new Set(storedDetails.map(x=>x.koper_id));const newBills=bills.filter(x=>!known.has(`koper_bill:${x.billId}`)&&!detailIds.has(x.billId));
  const cap=Math.max(1,Math.min(500,Number(process.env.KOPER_DAILY_NEW_LIMIT??"250")||250));
  const selected=newBills.slice(0,cap);const details=new Map<string,Detail>();let cursor=0;
  await Promise.all(Array.from({length:Math.min(8,selected.length)},async()=>{while(true){const i=cursor++;if(i>=selected.length)return;const bill=selected[i]!;const u=new URL("https://api.koper.com.br/financial/v1/bills_to_pay");u.searchParams.set("billId",bill.billId);const res=await page.request.get(u.toString(),{headers,timeout:12000});if(!res.ok())throw new Error(`KOPER_DETAIL_HTTP_${res.status()}_${bill.billId}`);details.set(bill.billId,parseDetail(o(await res.json().catch(()=>null))));}}));
  return{bills,details,blockedWrites,headerTotal:headerTotal/100,computedTotal:computedTotal/100};
 },{sessionTimeoutMs:180000});
}

try{
 const source=await capture();
 const [previous,oldDetails,resolutions,payables,invoices,suppliers,projects]=await Promise.all([
  stage("bill_to_pay"),stage("bill_detail_enrichment"),stage("bill_resolution"),
  all<Payable>("payables",{select:"id,source_id,project_id,supplier_id,amount,due_date,status,paid_at,paid_amount,notes",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper_flow",order:"id.asc"}),
  all<Invoice>("finance_electronic_invoices",{select:"registry_number,project_id,supplier_id,invoice_number",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"registry_number.asc"}),
  all<Supplier>("suppliers",{select:"id,source_id,source_system,legal_name",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),
  all<{id:string;name:string}>("projects",{select:"id,name",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),
 ]);
 const byStage=new Map(previous.map(x=>[x.koper_id,x])),byPayable=new Map(payables.filter(x=>x.source_id).map(x=>[x.source_id!,x]));
 const invoiceBySource=new Map(invoices.map(x=>[x.registry_number,x]));const supplierBySource=new Map(suppliers.filter(x=>x.source_id&&x.source_system==="koper").map(x=>[x.source_id!,x]));
 const flowProjects=projects.filter(x=>/\bflow\b/i.test(x.name));if(flowProjects.length!==1)throw new Error(`KOPER_FLOW_PROJECT_AMBIGUOUS_${flowProjects.length}`);const flowProjectId=flowProjects[0]!.id;
 const normalized=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().replace(/\s+/g," ");const supplierByName=new Map<string,Supplier[]>();for(const row of suppliers){const key=normalized(row.legal_name);supplierByName.set(key,[...(supplierByName.get(key)??[]),row]);}
 const projectIds=new Set(projects.map(x=>x.id));const projectByCenter=new Map<string,Set<string>>();const resolutionByBill=new Map(resolutions.map(x=>[x.koper_id,o(x.payload)]));
 for(const row of oldDetails){const center=s(o(row.payload).costCenterId),p=byPayable.get(`koper_bill:${row.koper_id}`),evidenceProject=s(o(o(resolutionByBill.get(row.koper_id)).projectEvidence).projectId);if(center&&p&&evidenceProject===p.project_id){const set=projectByCenter.get(center)??new Set<string>();set.add(p.project_id);projectByCenter.set(center,set);}}
 const newBills=source.bills.filter(x=>!byPayable.has(`koper_bill:${x.billId}`));const detailByBill=new Map(oldDetails.map(x=>[x.koper_id,o(x.payload) as Detail]));for(const[id,detail]of source.details)detailByBill.set(id,detail);const selected=newBills.filter(x=>detailByBill.has(x.billId));
 const override=process.argv.includes("--flow-override");type AllocationRow={id:string;payable_id:string;allocation_amount:number};const allocationByPayable=new Map<string,{total:number;rows:AllocationRow[]}>();if(override){const allocations=await all<AllocationRow>("payable_cost_allocations",{select:"id,payable_id,allocation_amount",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"});for(const row of allocations){const state=allocationByPayable.get(row.payable_id)??{total:0,rows:[]};state.total+=cents(row.allocation_amount);state.rows.push(row);allocationByPayable.set(row.payable_id,state);}}
 const exceptions:Array<{billId:string;reason:string;amount:number}>=[];const creates:J[]=[];const newSuppliers=new Map<string,J>();const conflictUpdates:Array<{payable:Payable;bill:Bill;amount:number;overallocated:boolean;allocationToReduce:AllocationRow|null}>=[];const paymentUpdates:Array<{payable:Payable;bill:Bill}>=[];let unchanged=0;
 for(const bill of source.bills){const posted=byPayable.get(`koper_bill:${bill.billId}`);if(posted){if(cents(posted.amount)!==cents(bill.billValue)||posted.due_date!==bill.dueDate){if(override&&bill.dueDate&&(!bill.isPaid||bill.paymentDate)&&(posted.status==="open"||(posted.status==="paid"&&bill.isPaid))){const allocation=allocationByPayable.get(posted.id),allocated=allocation?.total??0;const overallocated=allocated>cents(bill.billValue);const allocationToReduce=overallocated&&cents(bill.billValue)>0&&allocation?.rows.length===1&&allocated===cents(posted.amount)?allocation.rows[0]!:null;conflictUpdates.push({payable:posted,bill,amount:overallocated&&!allocationToReduce?posted.amount:bill.billValue,overallocated:overallocated&&!allocationToReduce,allocationToReduce});if(overallocated&&!allocationToReduce)exceptions.push({billId:bill.billId,reason:"allocation_exceeds_koper_amount",amount:bill.billValue});}else exceptions.push({billId:bill.billId,reason:"existing_value_or_due_date_conflict",amount:bill.billValue});continue;}if(posted.status==="open"&&bill.isPaid&&bill.paymentDate)paymentUpdates.push({payable:posted,bill});else if(posted.status==="paid"&&!bill.isPaid)exceptions.push({billId:bill.billId,reason:"payment_reversal_requires_review",amount:bill.billValue});else unchanged++;continue;}
  if(!detailByBill.has(bill.billId))continue;const detail=detailByBill.get(bill.billId)!;const inv=detail.invoiceId?invoiceBySource.get(`KOPER-NFE-${detail.invoiceId}`):undefined;const centerProjects=detail.costCenterId?projectByCenter.get(detail.costCenterId):undefined;
  const projectId=override?flowProjectId:inv?.project_id??(centerProjects?.size===1?[...centerProjects][0]:flowProjectId);
  const nameMatches=detail.supplierName?supplierByName.get(normalized(detail.supplierName))??[]:[];let supplierId=inv?.supplier_id??(detail.supplierId?supplierBySource.get(detail.supplierId)?.id:null)??(nameMatches.length===1?nameMatches[0]!.id:null);
  if(!supplierId&&detail.supplierId&&detail.supplierName){supplierId=uuid(`elos:koper:supplier:${detail.supplierId}`);newSuppliers.set(detail.supplierId,{id:supplierId,company_id:env.BOSSA_COMPANY_ID,legal_name:detail.supplierName,person_type:"other",source_system:"koper",source_id:detail.supplierId,notes:"Cadastro vinculado à importação de contas a pagar do Koper"});}
  const reason=!projectId||!projectIds.has(projectId)?"project_unresolved":!supplierId?"supplier_unresolved":!bill.dueDate||cents(bill.billValue)<0?"invalid_amount_or_due_date":bill.isPaid&&!bill.paymentDate?"paid_without_payment_date":null;
  if(reason){exceptions.push({billId:bill.billId,reason,amount:bill.billValue});continue;}
  creates.push({id:uuid(`elos:koper:payable:${bill.billId}`),company_id:env.BOSSA_COMPANY_ID,project_id:projectId,supplier_id:supplierId,document:inv?`NF ${inv.invoice_number}`:bill.invoiceNumber?`NF ${bill.invoiceNumber}`:bill.receiptNumber?`Recibo ${bill.receiptNumber}`:`Koper ${bill.billToPayId??bill.billId}`,due_date:bill.dueDate,amount:bill.billValue,status:bill.isPaid?"paid":"open",paid_at:bill.isPaid?bill.paymentDate:null,paid_amount:bill.isPaid?(bill.paymentValue??bill.billValue):null,paid_account_name:bill.isPaid?"Koper (sincronização)":null,notes:`À Apropriar · Sincronização Koper · título ${bill.billToPayId??bill.billId} · parcela ${bill.billId}`,origin:"historical_import",source_system:"koper_flow",source_category:inv?"electronic_invoice":"daily_import",source_id:`koper_bill:${bill.billId}`});
 }
 const write=process.argv.includes("--write");const summary={write,override,flowProjectId,source:source.bills.length,sourceTotal:source.computedTotal,headerReportedTotal:source.headerTotal,headerDifference:Math.round((source.computedTotal-source.headerTotal)*100)/100,previousStage:previous.length,previousPayables:payables.length,newInSource:newBills.length,detailsFetched:source.details.size,detailsAvailable:selected.length,remainingDetails:newBills.length-selected.length,newSuppliers:newSuppliers.size,toCreate:creates.length,conflictUpdates:conflictUpdates.length,allocationsToReduce:conflictUpdates.filter(x=>x.allocationToReduce).length,overallocatedConflicts:conflictUpdates.filter(x=>x.overallocated).length,paymentUpdates:paymentUpdates.length,unchanged,exceptions:exceptions.length,exceptionsByReason:exceptions.reduce<Record<string,number>>((m,x)=>(m[x.reason]=(m[x.reason]??0)+1,m),{}),examples:exceptions.slice(0,12),blockedKoperWrites:source.blockedWrites};
 console.log("KOPER_DAILY_SYNC_PLAN",JSON.stringify(summary));
 if(process.argv.includes("--reconcile")){
  const sourceIds=new Set(source.bills.map(x=>`koper_bill:${x.billId}`));
  const extra=payables.filter(x=>!x.source_id||!sourceIds.has(x.source_id));
  const missing=source.bills.filter(x=>!byPayable.has(`koper_bill:${x.billId}`));
  const mismatched=source.bills.flatMap(x=>{const p=byPayable.get(`koper_bill:${x.billId}`);return p&&cents(p.amount)!==cents(x.billValue)?[{billId:x.billId,koper:x.billValue,elos:p.amount,delta:Math.round((p.amount-x.billValue)*100)/100,projectId:p.project_id}]:[];});
  const projectTotals=new Map<string,{count:number,cents:number}>();for(const p of payables){const v=projectTotals.get(p.project_id)??{count:0,cents:0};v.count++;v.cents+=cents(p.amount);projectTotals.set(p.project_id,v);}
  console.log("KOPER_DAILY_RECONCILIATION",JSON.stringify({sourceCount:source.bills.length,sourceTotal:source.computedTotal,payablesCount:payables.length,payablesTotal:payables.reduce((n,p)=>n+cents(p.amount),0)/100,projectTotals:[...projectTotals].map(([projectId,v])=>({projectId,count:v.count,total:v.cents/100})),extra:extra.map(p=>({sourceId:p.source_id,amount:p.amount,projectId:p.project_id,status:p.status})),extraTotal:extra.reduce((n,p)=>n+cents(p.amount),0)/100,missing:missing.map(b=>({billId:b.billId,amount:b.billValue})),missingTotal:missing.reduce((n,b)=>n+cents(b.billValue),0)/100,mismatched}));
  if(process.argv.includes("--details")&&extra.length){
   const ids=extra.map(p=>p.source_id?.replace(/^koper_bill:/,"")??"").filter(Boolean);
   const payableIds=extra.map(p=>p.id);
   const supplierIds=[...new Set(extra.map(p=>p.supplier_id).filter(Boolean))];
   const [fullPayables,fullSuppliers,staged,allocations,bankTransactions]=await Promise.all([
    all<J>("payables",{select:"*",company_id:`eq.${env.BOSSA_COMPANY_ID}`,id:`in.(${payableIds.join(",")})`,order:"id.asc"}),
    all<J>("suppliers",{select:"*",company_id:`eq.${env.BOSSA_COMPANY_ID}`,id:`in.(${supplierIds.join(",")})`,order:"id.asc"}),
    all<J>("koper_staging_records",{select:"*",company_id:`eq.${env.BOSSA_COMPANY_ID}`,koper_id:`in.(${ids.join(",")})`,order:"koper_id.asc"}),
    all<J>("payable_cost_allocations",{select:"*",company_id:`eq.${env.BOSSA_COMPANY_ID}`,payable_id:`in.(${payableIds.join(",")})`,order:"id.asc"}),
    all<J>("finance_bank_transactions",{select:"*",company_id:`eq.${env.BOSSA_COMPANY_ID}`,payable_id:`in.(${payableIds.join(",")})`,order:"id.asc"}),
   ]);
   const payableMap=new Map(fullPayables.map(x=>[String(x.id),x])),supplierMap=new Map(fullSuppliers.map(x=>[String(x.id),x]));
   for(const p of extra){const billId=p.source_id?.replace(/^koper_bill:/,"")??"";console.log("KOPER_EXTRA_DETAIL",JSON.stringify({billId,payable:payableMap.get(p.id)??p,supplier:supplierMap.get(p.supplier_id)??null,staging:staged.filter(x=>x.koper_id===billId),allocations:allocations.filter(x=>x.payable_id===p.id),bankTransactions:bankTransactions.filter(x=>x.payable_id===p.id)}));}
   console.log("KOPER_EXTRA_DETAIL_SUMMARY",JSON.stringify({count:extra.length,payables:fullPayables.length,suppliers:fullSuppliers.length,staging:staged.length,allocations:allocations.length,bankTransactions:bankTransactions.length}));
  }
 }
 if(process.argv.includes("--report")){
  const [allocationRows,bankRows,supplierRows,projectRows]=await Promise.all([
   all<{payable_id:string;allocation_amount:number}>("payable_cost_allocations",{select:"payable_id,allocation_amount",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),
   all<{payable_id:string|null;amount:number;status:string}>("finance_bank_transactions",{select:"payable_id,amount,status",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),
   all<{id:string;legal_name:string;source_id:string|null;source_system:string|null}>("suppliers",{select:"id,legal_name,source_id,source_system",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),
   all<{id:string;name:string}>("projects",{select:"id,name",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"}),
  ]);
  const allocationByPayable=new Map<string,{amount:number;count:number}>();for(const row of allocationRows){const state=allocationByPayable.get(row.payable_id)??{amount:0,count:0};state.amount+=cents(row.allocation_amount);state.count++;allocationByPayable.set(row.payable_id,state);}
  const bankByPayable=new Map<string,{amount:number;count:number}>();for(const row of bankRows){if(!row.payable_id||row.status==="cancelled")continue;const state=bankByPayable.get(row.payable_id)??{amount:0,count:0};state.amount+=cents(row.amount);state.count++;bankByPayable.set(row.payable_id,state);}
  const normalized=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().replace(/\s+/g," ");const supplierByName=new Map<string,string[]>();for(const row of supplierRows){const key=normalized(row.legal_name);supplierByName.set(key,[...(supplierByName.get(key)??[]),row.id]);}
  const projectNames=new Map(projectRows.map(x=>[x.id,x.name]));const flowProjects=projectRows.filter(x=>/\bflow\b/i.test(x.name));
  console.log("KOPER_DAILY_SYNC_REPORT_CONTEXT",JSON.stringify({flowProjects,allocationRows:allocationRows.length,bankRows:bankRows.length}));
  const billById=new Map(source.bills.map(x=>[x.billId,x]));
  console.log("KOPER_DAILY_SYNC_EXCEPTIONS",JSON.stringify(exceptions.map(item=>{const bill=billById.get(item.billId),detail=detailByBill.get(item.billId),posted=byPayable.get(`koper_bill:${item.billId}`),invoice=detail?.invoiceId?invoiceBySource.get(`KOPER-NFE-${detail.invoiceId}`):undefined,allocation=posted?allocationByPayable.get(posted.id):undefined,bank=posted?bankByPayable.get(posted.id):undefined,matches=detail?.supplierName?supplierByName.get(normalized(detail.supplierName))??[]:[];return{...item,billToPayId:bill?.billToPayId??null,dueDateKoper:bill?.dueDate??null,paidKoper:bill?.isPaid??null,paymentDateKoper:bill?.paymentDate??null,paymentValueKoper:bill?.paymentValue??null,invoiceNumber:bill?.invoiceNumber??null,receiptNumber:bill?.receiptNumber??null,originName:bill?.originName??null,supplierNameKoper:detail?.supplierName??null,supplierIdKoper:detail?.supplierId??null,costCenterIdKoper:detail?.costCenterId??null,invoiceIdKoper:detail?.invoiceId??null,projectIdElos:posted?.project_id??invoice?.project_id??null,projectNameElos:posted?projectNames.get(posted.project_id)??null:null,supplierIdElos:posted?.supplier_id??invoice?.supplier_id??null,supplierNameMatches:matches,amountElos:posted?.amount??null,dueDateElos:posted?.due_date??null,statusElos:posted?.status??null,allocationAmountElos:(allocation?.amount??0)/100,allocationCountElos:allocation?.count??0,bankAmountElos:(bank?.amount??0)/100,bankCountElos:bank?.count??0};})));
 }
 if(write){
 for(const supplier of newSuppliers.values())await requestSupabase("suppliers",{method:"POST",body:supplier,prefer:"resolution=ignore-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"company_id,source_system,source_id"})});
 if(newSuppliers.size){const checkedSuppliers=await all<Supplier>("suppliers",{select:"id,source_id,source_system,legal_name",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"});const supplierMap=new Map(checkedSuppliers.filter(x=>x.source_system==="koper"&&x.source_id).map(x=>[x.source_id!,x]));if([...newSuppliers].some(([sourceId,row])=>supplierMap.get(sourceId)?.id!==row.id))throw new Error("KOPER_SUPPLIER_POST_VERIFICATION_FAILED");}
 // Persist the source snapshot before promotion so a failed mapping remains reviewable.
 const now=new Date();for(let i=0;i<selected.length;i+=100){const batch=selected.slice(i,i+100).map(b=>createKoperStagingRecord({companyId:env.BOSSA_COMPANY_ID,entity:"bill_to_pay",koperId:b.billId,koperParentId:b.billToPayId,sanitizedPayload:{...b},mappingVersion:9,seenAt:now}));await requestSupabase("koper_staging_records",{method:"POST",body:batch,prefer:"resolution=ignore-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"company_id,source,entity,koper_id"}),timeoutMs:30000});}
 for(const bill of selected){const detail=source.details.get(bill.billId);if(!detail)continue;const row=createKoperStagingRecord({companyId:env.BOSSA_COMPANY_ID,entity:"bill_detail_enrichment",koperId:bill.billId,koperParentId:bill.billToPayId,sanitizedPayload:detail,mappingVersion:9,seenAt:now});await requestSupabase("koper_staging_records",{method:"POST",body:row,prefer:"resolution=ignore-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"company_id,source,entity,koper_id"})});}
 for(const item of exceptions.filter(x=>!byStage.has(x.billId))){const row=createKoperStagingRecord({companyId:env.BOSSA_COMPANY_ID,entity:"bill_daily_exception",koperId:item.billId,sanitizedPayload:{reason:item.reason,amount:item.amount,observedAt:now.toISOString()},mappingVersion:1,seenAt:now});await requestSupabase("koper_staging_records",{method:"POST",body:row,prefer:"resolution=ignore-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"company_id,source,entity,koper_id"})});}
 for(let i=0;i<creates.length;i+=50)await requestSupabase("payables",{method:"POST",body:creates.slice(i,i+50),prefer:"resolution=ignore-duplicates,return=minimal",query:new URLSearchParams({on_conflict:"id"}),timeoutMs:30000});
 for(const {payable,bill,allocationToReduce} of conflictUpdates){if(!allocationToReduce)continue;await requestSupabase("payable_cost_allocations",{method:"PATCH",body:{allocation_amount:bill.billValue},query:new URLSearchParams({id:`eq.${allocationToReduce.id}`,company_id:`eq.${env.BOSSA_COMPANY_ID}`,payable_id:`eq.${payable.id}`,allocation_amount:`eq.${allocationToReduce.allocation_amount}`}),prefer:"return=minimal"});}
 if(conflictUpdates.some(x=>x.allocationToReduce)){const checkedAllocations=await all<AllocationRow>("payable_cost_allocations",{select:"id,payable_id,allocation_amount",company_id:`eq.${env.BOSSA_COMPANY_ID}`,order:"id.asc"});const byAllocationId=new Map(checkedAllocations.map(x=>[x.id,x]));if(conflictUpdates.some(x=>x.allocationToReduce&&cents(byAllocationId.get(x.allocationToReduce.id)?.allocation_amount)!==cents(x.bill.billValue)))throw new Error("KOPER_ALLOCATION_REDUCTION_VERIFICATION_FAILED");}
 for(const {payable,bill,amount,overallocated} of conflictUpdates){const note=overallocated?`Divergência Koper: valor ${bill.billValue.toFixed(2)}; apropriação existente superior. Valor original preservado até revisão. · ${payable.notes??""}`:payable.notes;await requestSupabase("payables",{method:"PATCH",body:{amount,due_date:bill.dueDate,status:bill.isPaid?"paid":"open",paid_at:bill.isPaid?bill.paymentDate:null,paid_amount:bill.isPaid?(bill.paymentValue??bill.billValue):null,paid_account_name:bill.isPaid?"Koper (sincronização)":null,...(overallocated?{notes:note}:{})},query:new URLSearchParams({id:`eq.${payable.id}`,company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_id:`eq.koper_bill:${bill.billId}`,amount:`eq.${payable.amount}`,due_date:`eq.${payable.due_date}`,status:`eq.${payable.status}`}),prefer:"return=minimal"});}
 for(const {payable,bill} of paymentUpdates)await requestSupabase("payables",{method:"PATCH",body:{status:"paid",paid_at:bill.paymentDate,paid_amount:bill.paymentValue??bill.billValue,paid_account_name:"Koper (sincronização)"},query:new URLSearchParams({id:`eq.${payable.id}`,company_id:`eq.${env.BOSSA_COMPANY_ID}`,status:"eq.open",source_id:`eq.koper_bill:${bill.billId}`}),prefer:"return=minimal"});
 const checked=await all<Payable>("payables",{select:"id,source_id,project_id,supplier_id,amount,due_date,status,paid_at,paid_amount,notes",company_id:`eq.${env.BOSSA_COMPANY_ID}`,source_system:"eq.koper_flow",order:"id.asc"});const checkMap=new Map(checked.filter(x=>x.source_id).map(x=>[x.source_id!,x]));
 if(creates.some(row=>{const p=checkMap.get(String(row.source_id));return !p||cents(p.amount)!==cents(row.amount)||p.project_id!==row.project_id||p.supplier_id!==row.supplier_id;})||conflictUpdates.some(({bill,amount,payable})=>{const p=checkMap.get(`koper_bill:${bill.billId}`);return !p||cents(p.amount)!==cents(amount)||p.due_date!==bill.dueDate||p.status!==(bill.isPaid?"paid":"open")||p.project_id!==payable.project_id;})||paymentUpdates.some(({bill})=>checkMap.get(`koper_bill:${bill.billId}`)?.status!=="paid"))throw new Error("KOPER_DAILY_POST_VERIFICATION_FAILED");
 console.log("KOPER_DAILY_SYNC_RESULT",JSON.stringify({createdOrPresent:creates.length,suppliersCreatedOrPresent:newSuppliers.size,conflictsUpdated:conflictUpdates.length,allocationsReduced:conflictUpdates.filter(x=>x.allocationToReduce).length,overallocatedConflicts:conflictUpdates.filter(x=>x.overallocated).length,paymentsUpdated:paymentUpdates.length,verified:true,exceptions:exceptions.length,remainingDetails:newBills.length-selected.length}));
 }
}catch(error){console.error("KOPER_DAILY_SYNC_FAILED",JSON.stringify({message:error instanceof Error?error.message.slice(0,500):String(error)}));process.exitCode=1;}
